### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by codingdosg** [alibaba/sealer#1005]
[root@238_178 ~]$ sealer run kubernetes:v1.19.8 --masters 192.168.238.xxx --nodes ""  --passwd xxxxxxxx
2022-01-01 08:44:23 [INFO] [local.go:238] Start to create a new cluster
Start to Pull Image kubernetes:v1.19.8
931c62b6d883: pull completed
991491d3025b: pull completed
c1aa4aff818d: pull completed
d2c72ca0b588: pull completed
Success to Pull Image kubernetes:v1.19.8
Error: mount rootfs failed <nil>,copy rootfs failed open /var/lib/sealer/data/my-cluster/rootfs/Kubefile: no such file or directory
Usage:
  sealer run [flags]

Examples:

create default cluster:
	sealer run registry.cn-qingdao.aliyuncs.com/sealer-io/kubernetes:v1.19.8

create cluster by cloud provider, just set the number of masters or nodes,and default provider is ALI_CLOUD:
	sealer run registry.cn-qingdao.aliyuncs.com/sealer-io/kubernetes:v1.19.8 --masters 3 --nodes 3 --provider ALI_CLOUD

create cluster by docker container, set the number of masters or nodes, and set provider "CONTAINER":
	sealer run registry.cn-qingdao.aliyuncs.com/sealer-io/kubernetes:v1.19.8 --masters 3 --nodes 3 --provider CONTAINER

create cluster to your baremetal server, appoint the iplist:
	sealer run registry.cn-qingdao.aliyuncs.com/sealer-io/kubernetes:v1.19.8 --masters 192.168.0.2,192.168.0.3,192.168.0.4 \
		--nodes 192.168.0.5,192.168.0.6,192.168.0.7
create a cluster with custom environment variables:
	sealer run -e DashBoardPort=8443 mydashboard:latest registry.cn-qingdao.aliyuncs.com/sealer-io/kubernetes:v1.19.8 --masters 3 --nodes 3

Flags:
  -e, --env strings          set custom environment variables
  -h, --help                 help for run
  -m, --masters string       set Count or IPList to masters
  -n, --nodes string         set Count or IPList to nodes
  -p, --passwd string        set cloud provider or baremetal server password
      --pk string            set baremetal server private key (default "/root/.ssh/id_rsa")
      --pk-passwd string     set baremetal server  private key password
      --podcidr string       set default pod CIDR network. example '10.233.0.0/18'
      --provider ALI_CLOUD   set infra provider, example ALI_CLOUD, the local server need ignore this
      --svccidr string       set default service CIDR network. example '10.233.64.0/18'
  -u, --user string          set baremetal server username (default "root")

Global Flags:
      --config string   config file (default is $HOME/.sealer.json)
  -d, --debug           turn on debug mode

mount rootfs failed <nil>,copy rootfs failed open /var/lib/sealer/data/my-cluster/rootfs/Kubefile: no such file or directory

**Comment by kakaZhou719** [comment]
try http://sealer.cool/docs/help/faq.html#how-to-clean-host-environment-manually-when-sealer-apply-failed to trouble shooting
