### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by codingdosg** [alibaba/sealer#1006]
[root@192 sealer]$ kubectl get pods -A
NAMESPACE              NAME                                         READY   STATUS             RESTARTS   AGE
calico-system          calico-kube-controllers-5689d4dfdf-2x28l     0/1     CrashLoopBackOff   2          38s
calico-system          calico-node-2mwvv                            1/1     Running            0          38s
calico-system          calico-typha-7cbc5d8d4-5gkqc                 1/1     Running            0          39s
kube-system            coredns-597c5579bc-cj5qq                     0/1     Running            0          44s
kube-system            coredns-597c5579bc-stpzv                     0/1     Running            0          44s
kube-system            etcd-192.168.238.178                         0/1     Running            0          64s
kube-system            kube-apiserver-192.168.238.178               1/1     Running            0          64s
kube-system            kube-controller-manager-192.168.238.178      1/1     Running            0          64s
kube-system            kube-proxy-4xcpv                             1/1     Running            0          44s
kube-system            kube-scheduler-192.168.238.178               0/1     Running            0          64s
kubernetes-dashboard   dashboard-metrics-scraper-79c5968bdc-p6qf6   1/1     Running            0          44s
kubernetes-dashboard   kubernetes-dashboard-9f9799597-xctjf         0/1     CrashLoopBackOff   1          44s
tigera-operator        tigera-operator-86c4fc874f-6mwjh             1/1     Running            0          44s

CrashLoopBackOff

**Comment by kakaZhou719** [comment]
seams we dont cached all the docker images, the sealer version 0.6 will fix this issue.

**Comment by fanux** [comment]
@codingdosg try 0.6 version, if already has this issue, reopen it.
