### ISSUE TITLE
A serious functional defect: When adding a node, because of the problem of reading the local clusterfile, diff logic judges that all nodes have executed node join logic.

### ISSUE THREAD

**Issue by lllwan** [alibaba/sealer#1012]
It's terrible! This almost reset our production cluster. 
When we try to add a few points to the cluster, we find that actually all existing nodes have been changed, so we urgently stop sealer, but still cause the docker of cluster nodes to be reinstalled and restarted.
The reason is analyzed: when the logic of adding nodes judges diff, the old node data is empty, resulting in diff feedback that all nodes need to execute join logic。
So I think:

1. The pre verification should be improved to ensure that there is no error. If an error occurs, it will not continue to be executed.

2. For example, for risky operations such as join and delete, clear prompts should be given and the user should confirm them again.

**Comment by fanux** [comment]
How to reproduce this issue?

**Comment by yj-cloud** [comment]
Maybe it's better to create a configmap when deploying cluster than storing a local  clusterfile. It can reduce dependence on local environment.

**Comment by fanux** [comment]
> Maybe it's better to store clusterfile by creating a configmap after deploying cluster than a local clusterfile. It can reduce dependence on local environment.

Agree, but should care about if kubeconfig not exist, sealer found that cluster not exist and create a new one.

**Comment by yj-cloud** [comment]
> > Maybe it's better to store clusterfile by creating a configmap after deploying cluster than a local clusterfile. It can reduce dependence on local environment.
> 
> Agree, but should care about if kubeconfig not exist, sealer found that cluster not exist and create a new one.

Could we develop a operator in kubernetes cluster for Clusterfile CRD  to update cluster? The operator is just for updating the local cluster.  We can add worker nodes, delete worker nodes or update cluster image by using `kubectl` to update Clusterfile CRD.  Modifying a cluster is as simple as modifying a pod.

**Comment by lllwan** [comment]
When SSH is not the default port, diff logic makes a difference set between the current cluster node list and the node list in the clusterfile (which has been added to the IP list attached to the join command) to remove the difference, but the problem is: when SSH is not the default port, the submission format is similar:/ Sealer join -- nodes 192.168.1.1:10022 at this time, the diff logic will misjudge, because the node IP taken from the cluster will not contain SSH ports.

**Comment by bxy4543** [comment]
@lllwan the cluster V2 separate port and IP as separate parameters
```
spec:
  image: kubernetes:v1.19.8
  ssh:
    passwd: xxx
    user: root
    port: 22
  hosts:
  - ips: [192.168.56.3]
    roles: [master]
    ssh:
      port: 23
```
