### ISSUE TITLE
no need to set host password  when exec sealer run on master0

### ISSUE THREAD

**Issue by kakaZhou719** [alibaba/sealer#1037]
## Issue Description

Type: *feature request*

### Describe what feature you want

For example, I have logged in to a machine which as my master0 node, and my cluster only have this one node.

and then I just want to initialize the machine. At this time, I don’t need to enter the password and ip addresses . cmd "sealer run " will success .

Example : "sealer run  kubernetes:v1.19.8"

**Comment by neo502721** [comment]
how choose the master ip if the master0 node have multiple IP?

**Comment by kakaZhou719** [comment]
@neo502721 , i think we dont care about ip addr, just copy rootfs file and run init, will start the cluster.

**Comment by fanux** [comment]
This is a convenience feature for single node test
