### ISSUE TITLE
error cri

### ISSUE THREAD

**Issue by clcc2019** [alibaba/sealer#1044]
<img width="1500" alt="image" src="https://user-images.githubusercontent.com/46099295/148044696-0b8ad80d-e141-46fc-8d87-2631cada483b.png">
<img width="1504" alt="image" src="https://user-images.githubusercontent.com/46099295/148044770-4b38e5c7-7fca-4713-85ea-d42239a4307a.png">

I upgraded the cluster to 1.20, and node used containerd when it was running, which made it impossible to join the cluster. How do I modify it to use docker

**Comment by mahmut-Abi** [comment]
Maybe you should stop docker service. Because k8s v1.19.8 use docker for cri, but v1.20 use containerd.

**Comment by clcc2019** [comment]
> Maybe you should stop docker service. Because k8s v1.19.8 use docker for cri, but v1.20 use containerd.

But we still want to use docker runtime

**Comment by fanux** [comment]
0.6.1 already support the kubeadm config in Clusterfile. You need to build your own CloudImage.
