### ISSUE TITLE
whats the main propose of sealer exec ?

### ISSUE THREAD

**Issue by kakaZhou719** [alibaba/sealer#1048]
#### What happened:

follow the example, the command line result is not echoed.whats the main propose of sealer exec ? I understand it should be able to execute commands remotely，and show the result.

![image](https://user-images.githubusercontent.com/83740799/148481986-78d220dd-da5c-489d-9b9c-8907624466b5.png)

#### Environment:

- sealer version (use `sealer version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by bxy4543** [comment]
The command return information has been optimized, so the --debug parameter is required to display information

**Comment by fanux** [comment]
Should not using debug by default, should open the ssh.CmdAsync stdoutput.
