### ISSUE TITLE
Sealer delete node needs to be stable enough to be as error-free as possible

### ISSUE THREAD

**Issue by bxy4543** [alibaba/sealer#1050]
sealer delete may also fail when executed after an installation failure, so sealer delete needs to be stable enough.

**Comment by neo502721** [comment]
Hi @bxy4543 , can you assign to me?

**Comment by bxy4543** [comment]
> Hi @bxy4543 , can you assign to me?

sure, thank you for your contribution

**Comment by neo502721** [comment]
Hi @bxy4543, I read the source code for the sealer delete process. Sealer delete will return failed if there is no cluster file under $HOME/.sealer folder. Then it mast do some clean work manually based on the faq description. http://sealer.cool/docs/help/faq.html#how-to-clean-host-environment-manually-when-sealer-apply-failed
So, how about add clean works to the delete process  when the cluster file inexistence such as follow:
- umount rootfs or apply mount if it existed
- delete rootfs directory if it existed
- delete kubernetes directory if it existed
- delete docker registry if it existed
- kubeadm reset
- delete kube config and kubelet if it existed

**Comment by bxy4543** [comment]
@neo502721 
I think we only need to think about Clusterfile when it exists.

You listed clean works correctly. need a little tweaking:
- delete docker registry if it existed
- kubeadm reset force, if it existed
- delete kubernetes directory if it existed
- delete kube config and kubelet if it existed
- if rootfs existed {
exec rootfs/scripts/clean.sh if it existed
umount rootfs dir and umount mount dir if it mounted
delete rootfs directory if it existed
}

**Comment by neo502721** [comment]
> @neo502721 I think we only need to think about Clusterfile when it exists.
> 
> You listed clean works correctly. need a little tweaking:
> 
> * delete docker registry if it existed
> * kubeadm reset force, if it existed
> * delete kubernetes directory if it existed
> * delete kube config and kubelet if it existed
> * if rootfs existed {
>   exec rootfs/scripts/clean.sh if it existed
>   umount rootfs dir and umount mount dir if it mounted
>   delete rootfs directory if it existed
>   }

I found all those process already exists when the Clusterfile exists scenario. Maybe only need a small change like add `rm -rf /usr/bin/kube*` about RemoteCleanMasterOrNode. 
https://github.com/alibaba/sealer/blob/331b8bc729e0da3078e788a1b7a495fd99d15851/pkg/runtime/masters.go#L57
So, this issue want to refactor the delete process or anything else？

**Comment by bxy4543** [comment]
yes, just a little bit of optimization is enough.
- Need to make sure that delete is also successful after installation error.
For example, if the rootfs directory does not exist, executing the $rootfs/scripts/clean.sh step in unmountRootfs will report an error, and skip it if it is necessary to judge that the rootfs does not exist.
https://github.com/alibaba/sealer/blob/331b8bc729e0da3078e788a1b7a495fd99d15851/pkg/filesystem/filesystem.go#L236
- add rm -rf /usr/bin/kube*
