### ISSUE TITLE
sealer run  failed to set trusted.overlay.opaque, err: operation not permitted

### ISSUE THREAD

**Issue by neo502721** [alibaba/sealer#1053]
sealer run kubernetes:v1.19.8 --masters 192.168.3.37
2022-01-07 15:15:06 [INFO] [local.go:238] Start to create a new cluster
Error: mount rootfs failed copy rootfs failed failed to set trusted.overlay.opaque, err: operation not permitted

#### Environment:

- sealer version (v0.6.1`):
- Cloud provider or hardware configuration:  OpenStack VM
- OS (ubuntu1~16.04.5):
- Kernel (4.4.0-104-generic):
- Install tools:
- Others:

**Comment by kakaZhou719** [comment]
@neo502721 ,please give us more info: `sealer inspect kubernetes:v1.19.8` .and `df -h | grep sealer `.

**Comment by neo502721** [comment]
> @neo502721 ,please give us more info: `sealer inspect kubernetes:v1.19.8` .and `df -h | grep sealer `.

root@uecp034:~# sealer inspect kubernetes:v1.19.8
kind: Image
metadata:
  annotations:
    sea.aliyun.com/ClusterFile: |
      apiVersion: sealer.cloud/v2
      kind: Cluster
      metadata:
        creationTimestamp: null
        name: my-cluster
      spec:
        image: kubernetes-clusterv2:v1.19.8
        ssh:
          passwd: Sealer123
          pk: xxx
          pkPasswd: xxx
          port: "22"
          user: root
      status: {}
  creationTimestamp: null
spec:
  id: b66008857a37af483e6e79085c7af45e7f96949fff005212ccfb04a276fed7b0
  layers:
  - id: sha256:61f2252f21454c39ec65dc86ddb05e8cf3519b3e4e024267c6598d01476ab994
    type: COPY
    value: . .
  - id: sha256:a8d197c0285c852a91aa686fdf861831a76118a4a8b79748620c3be77a2e30c3
    type: COPY
    value: etc .
  - type: CMD
    value: kubectl apply -f etc/tigera-operator.yaml
  - type: CMD
    value: kubectl apply -f etc/custom-resources.yaml
  - id: sha256:1dfe57535815de8a9210b5f78942c5bae837815246677b427f38070613285e5c
    type: BASE
    value: registry cache
  platform: {}
  sealer_version: latest
status: {}

root@uecp034:~# 
root@uecp034:~# df -h | grep sealer
overlay          59G  5.8G   51G  11% /var/lib/sealer/data/my-cluster/rootfs
overlay          59G  5.8G   51G  11% /var/lib/sealer/data/my-cluster/moun

**Comment by kakaZhou719** [comment]
```
root@uecp034:~# df -h | grep sealer
overlay          59G  5.8G   51G  11% /var/lib/sealer/data/my-cluster/rootfs
overlay          59G  5.8G   51G  11% /var/lib/sealer/data/my-cluster/moun
```

seems this host already mount rootfs. please flow faq [http://sealer.cool/docs/help/faq.html#how-to-clean-host-environment-manually-when-sealer-apply-failed](url) to do some clean work. and we will strengthen the cleanup function in the next sealer version.

**Comment by neo502721** [comment]
> 

Thanks for your help. 
I try to run sealer delete. But there is no /root/.sealer dir.

**Comment by kakaZhou719** [comment]
If not, it won't affect your re-run process. just go ahead.

**Comment by neo502721** [comment]
> If not, it won't affect your re-run process. just go ahead.

the cluster create succ, Thank you very much. 
I want to do some contribution to cleanup function, is there anything I can do?

**Comment by kakaZhou719** [comment]
> > If not, it won't affect your re-run process. just go ahead.
> 
> the cluster create succ, Thank you very much. I want to do some contribution to cleanup function, is there anything I can do?

refer to issue : https://github.com/alibaba/sealer/issues/1050。 If you have any questions, please contact me。

**Comment by neo502721** [comment]
> > > If not, it won't affect your re-run process. just go ahead.
> > 
> > 
> > the cluster create succ, Thank you very much. I want to do some contribution to cleanup function, is there anything I can do?
> 
> refer to issue : [https://github.com/alibaba/sealer/issues/1050。](https://github.com/alibaba/sealer/issues/1050%E3%80%82) If you have any questions, please contact me。

OK，I will check it. And read the source code. Thanks again
