### ISSUE TITLE
sealer build lost container image layer blob

### ISSUE THREAD

**Issue by kakaZhou719** [alibaba/sealer#1066]
#### What happened:
sealer build lost container image layer blob data, below is my build log that is show some layer already exists, actually ,docker not installed on my machine.

![image](https://user-images.githubusercontent.com/83740799/148743488-9a6ba6d6-def9-4c61-8d5e-4b5b9a4fd1f1.png)

tree registry save dir: only have manifests  , blob data not found.

![image](https://user-images.githubusercontent.com/83740799/148743531-ae674c1d-5010-4777-bed3-2a5c970ac7cf.png)

#### Environment:

- sealer version (use `sealer version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by shy-Xu** [comment]
Those layers exist in the output cloudImage.
