### ISSUE TITLE
validate auth info before building a image

### ISSUE THREAD

**Issue by justadogistaken** [alibaba/sealer#108]
#### What happened:
sealer build will push image after building done. And sealer build -t cloudfs:xxx will be push to "registry.cn-qingdao.aliyuncs.com" by default.
#### What you expected to happen:
pushing to "registry.cn-qingdao.aliyuncs.com" by default is weird. I think registry url should be specified when push a image.
#### Environment:
- sealer version (use `sealer version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by fanux** [comment]
Check user permission before builds, if user doesn't have push access, return error tells him to specify the URL

**Comment by ly-wjj** [comment]
I will fix it

**Comment by ly-wjj** [comment]
@fanux @kakaZhou719 #338 pull request has resolved the issue. Can this issue be closed?
