### ISSUE TITLE
Executing sealer delete will pull the image

### ISSUE THREAD

**Issue by bxy4543** [alibaba/sealer#109]
#### What happened:

![image](https://user-images.githubusercontent.com/69408038/118585538-afc37b00-b7cb-11eb-8ca4-7c35fa0b9293.png)

#### What you expected to happen:

sealer run kubernetes:v1.16.9 -m 1 -n 1
then sealer delete -f /root/.sealer/my-cluster/Clusterfile

#### Environment:
- sealer version (use `sealer version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by fanux** [comment]
1. don't need apply masters and nodes https://github.com/alibaba/sealer/blob/main/apply/default_applier.go#L136
2. reset interface implementation https://github.com/alibaba/sealer/blob/main/runtime/runtime.go#L83
3. just call deleteMasters and deleteNodes in reset interface 
https://github.com/alibaba/sealer/blob/main/runtime/runtime.go#L100

**Comment by fanux** [comment]
https://github.com/alibaba/sealer/blob/main/runtime/init.go#L86 caused this issue.

![image](https://user-images.githubusercontent.com/8912557/118768030-153d6780-b8b1-11eb-91c2-bc2c1eea83f5.png)

![image](https://user-images.githubusercontent.com/8912557/118768123-3736ea00-b8b1-11eb-84e6-2a1df4664c67.png)

**Comment by fanux** [comment]
Should get metadata from cloudrootfs in /var/lib/sealer/data/<cluster-name>/Metadata, not get it from the image.

**Comment by justadogistaken** [comment]
GetFileFromBaseImage aims to get ClusterFile from image?

**Comment by fanux** [comment]
> GetFileFromBaseImage aims to get ClusterFile from image?

aims to get rootfs metadata, like kubernetes version.

https://github.com/alibaba/sealer/blob/main/docs/api/cloudrootfs.md#metadata

**Comment by cuisongliu** [comment]
https://github.com/alibaba/sealer/pull/81/files#diff-366435ef0ac4d6827890dc13216bb41b7ebf2a0cb5262c9155d177d37fb61715R88

fix it
