### ISSUE TITLE
Support ip range

### ISSUE THREAD

**Issue by fanux** [alibaba/sealer#1102]
```
sealer delete --masters 192.168.0.7-192.168.0.10 --nodes 192.168.0.11-192.168.0.13
```

**Comment by zsyaoo** [comment]
https://github.com/alibaba/sealer/blob/a367ba250303395611c61ab836afc010dd9b2097/apply/scale.go#L129

**Comment by bxy4543** [comment]
ip range is already supported for scale;
but sealer run need support this:
`sealer run --masters 192.168.0.7-192.168.0.10 --nodes 192.168.0.11-192.168.0.13`
