### ISSUE TITLE
如何制作kubernetes离线安装包？ 

### ISSUE THREAD

**Issue by longting** [alibaba/sealer#1161]
比如构建kubernetes1.23.tar.gz包？ 包括arm和amd，有教程文档吗？ sealer可以实现吗？

**Comment by kakaZhou719** [comment]
@longting , read doc here: docs/site/src/docs/advanced/define-cloudimage.md
@Stevent-fei ,add automatic build cloud image doc here for user reference .

**Comment by kakaZhou719** [comment]
@longting ,we have  pr the autobuild  script see : https://github.com/alibaba/sealer/blob/main/hack/autobuild.sh. and i will close this issue.
