### ISSUE TITLE
sealer build:  failed to create overlay mount : device or resource busy

### ISSUE THREAD

**Issue by fanux** [alibaba/sealer#1166]
```
[root@iZuf62m0thccqv1j3rnbfbZ test]# sealer build -t test .
2022-02-18 14:16:40 [INFO] [base_image.go:51] get mount dir :/var/lib/sealer/tmp/.DTmp-933110466 success 
2022-02-18 14:16:40 [INFO] [build_image.go:85] run build layer: COPY imageList manifests
2022-02-18 14:16:40 [INFO] [build_image.go:118] exec all build instructs success !
Pulling image: adp-registry.cn-shanghai.cr.aliyuncs.com/cloud-middleware/harmonycloud-cn-redis-1-5-6-2:middleware_redis-exporter-v0.34.1-0ca3820f
Pulling image: adp-registry.cn-shanghai.cr.aliyuncs.com/cloud-middleware/harmonycloud-cn-redis-1-5-6-2:middleware_redis-init-v1.3.2-1-ab8e9196
Pulling image: adp-registry.cn-shanghai.cr.aliyuncs.com/cloud-middleware/harmonycloud-cn-redis-1-5-6-2:middleware_operator-manager-v1.5.6-fedead5a
Pulling image: adp-registry.cn-shanghai.cr.aliyuncs.com/cloud-middleware/harmonycloud-cn-redis-1-5-6-2:middleware_operator-test-framework-v0.3-4287e2ab
Pulling image: adp-registry.cn-shanghai.cr.aliyuncs.com/cloud-middleware/harmonycloud-cn-redis-1-5-6-2:middleware_redis-cli-v5-port-5.0.8-4e754357
Error: save domain adp-registry.cn-shanghai.cr.aliyuncs.com image error: get cloud-middleware/harmonycloud-cn-redis-1-5-6-2 tag descriptor error: unknown tag=middleware_redis-exporter-v0.34.1-0ca3820f, try "docker login" if you are using a private registry
```

Kubefile and imageList:
```
[root@iZuf62m0thccqv1j3rnbfbZ test]# cat Kubefile 
FROM kubernetes:v1.19.8
COPY imageList manifests
[root@iZuf62m0thccqv1j3rnbfbZ test]# cat imageList 
adp-registry.cn-shanghai.cr.aliyuncs.com/cloud-middleware/harmonycloud-cn-redis-1-5-6-2:middleware_redis-exporter-v0.34.1-0ca3820f
adp-registry.cn-shanghai.cr.aliyuncs.com/cloud-middleware/harmonycloud-cn-redis-1-5-6-2:middleware_redis-init-v1.3.2-1-ab8e9196
adp-registry.cn-shanghai.cr.aliyuncs.com/cloud-middleware/harmonycloud-cn-redis-1-5-6-2:middleware_operator-manager-v1.5.6-fedead5a
adp-registry.cn-shanghai.cr.aliyuncs.com/cloud-middleware/harmonycloud-cn-redis-1-5-6-2:middleware_operator-test-framework-v0.3-4287e2ab
adp-registry.cn-shanghai.cr.aliyuncs.com/cloud-middleware/harmonycloud-cn-redis-1-5-6-2:middleware_redis-cli-v5-port-5.0.8-4e754357
```

This caused by sealer not support ACR tmp token.  
```
[root@iZuf62m0thccqv1j3rnbfbZ sealer_project]# cat ~/.docker/config.json 
{
	"auths": {
		"adp-registry.cn-shanghai.cr.aliyuncs.com": {
			"auth": "Y3JfdGVtcF91c2VyOmV5SnBibk4wWVc1alpVbGtJam9pWTNKcExXRjJjVEp4Tld0cmRYQnJlRGMzYVdNaUxDSjBhVzFsSWpvaU1UWTBOVEUzTURjMU56QXdNQ0lzSW5SNWNHVWlPaUp6ZFdJaUxDSjFjMlZ5U1dRaU9pSXlORGN4TlRBMk16STNORFF4TWpnek5qY2lmUToxNmEzY2EyZjdmZGVhYWM2NDIyMTU5MjI1YTZmNjlkYjg5ZGRkNWY5"
		},
```

**Comment by fanux** [comment]
```
[root@iZuf62m0thccqv1j3rnbfbZ test]# sealer build -t test .
Start to Pull Image kubernetes:v1.19.8
a8d197c0285c: pull completed 
61f2252f2145: pull completed 
1dfe57535815: pull completed 
Success to Pull Image kubernetes:v1.19.8
2022-02-18 14:30:41 [INFO] [build_image.go:85] run build layer: COPY imageList manifests
2022-02-18 14:30:41 [INFO] [build_image.go:118] exec all build instructs success !
Pulling image: registry.cn-beijing.aliyuncs.com/private-test/nginx:latest
c316d5a335a5: Download complete 
5eb5b503b376: Download complete 
1ae07ab881bd: Download complete 
78091884b7be: Download complete 
091c283c6a66: Download complete 
55de5851019b: Download complete 
b559bad762be: Download complete 
Status: images save success
Error: failed to mount target /var/lib/sealer/tmp/.DTmp-241558564:error creating overlay mount to /var/lib/sealer/tmp/.DTmp-241558564: device or resource busy
```

**Comment by kakaZhou719** [comment]
the kernel log :

[49442.637685] overlayfs: lowerdir is in-use as upperdir/workdir of another mount, mount with '-o index=off' to override exclusive upperdir protection.
[49565.106995] overlayfs: lowerdir is in-use as upperdir/workdir of another mount, mount with '-o index=off' to override exclusive upperdir protection.
[50062.766185] overlayfs: lowerdir is in-use as upperdir/workdir of another mount, mount with '-o index=off' to override exclusive upperdir protection.
[50308.776545] overlayfs: lowerdir is in-use as upperdir/workdir of another mount, mount with '-o index=off' to override exclusive upperdir protection.


> ```
> [root@iZuf62m0thccqv1j3rnbfbZ test]# sealer build -t test .
> Start to Pull Image kubernetes:v1.19.8
> a8d197c0285c: pull completed 
> 61f2252f2145: pull completed 
> 1dfe57535815: pull completed 
> Success to Pull Image kubernetes:v1.19.8
> 2022-02-18 14:30:41 [INFO] [build_image.go:85] run build layer: COPY imageList manifests
> 2022-02-18 14:30:41 [INFO] [build_image.go:118] exec all build instructs success !
> Pulling image: registry.cn-beijing.aliyuncs.com/private-test/nginx:latest
> c316d5a335a5: Download complete 
> 5eb5b503b376: Download complete 
> 1ae07ab881bd: Download complete 
> 78091884b7be: Download complete 
> 091c283c6a66: Download complete 
> 55de5851019b: Download complete 
> b559bad762be: Download complete 
> Status: images save success
> Error: failed to mount target /var/lib/sealer/tmp/.DTmp-241558564:error creating overlay mount to /var/lib/sealer/tmp/.DTmp-241558564: device or resource busy
> ```
> 
> ```
> [root@iZuf62m0thccqv1j3rnbfbZ test]# cat imageList 
> registry.cn-beijing.aliyuncs.com/private-test/nginx:latest
> [root@iZuf62m0thccqv1j3rnbfbZ test]# 
> [root@iZuf62m0thccqv1j3rnbfbZ test]# cat Kubefile 
> FROM kubernetes:v1.19.8
> COPY imageList manifests
> ```
> 
> [moby/moby#37970](https://github.com/moby/moby/issues/37970)

**Comment by kakaZhou719** [comment]
thats because  overlay index=on as default config on kernels  > 4.13.  

`cat /sys/module/overlay/parameters/index `
 `Y `
