### ISSUE TITLE
Request for a officially support image of kubernetes 1.20+

### ISSUE THREAD

**Issue by ggaaooppeenngg** [alibaba/sealer#1167]
## Issue Description

Type: *feature request*

### Describe what feature you want
1.19 maybe a little old for some components like knative 1.0 requires 1.20+.

**Comment by kakaZhou719** [comment]
hi , @ggaaooppeenngg , @Stevent-fei will handle this issue at the end of this week.

**Comment by clcc2019** [comment]
> 

We make v1.20.15 cluster image, we can shared

**Comment by fanux** [comment]
@ggaaooppeenngg which version do you want?  We have github action to auto build any version base image in one hour.

**Comment by Stevent-fei** [comment]
imagebuild success, image name: kubernetes:v1.20.15

**Comment by ggaaooppeenngg** [comment]
Is GPU cloud build supported?
