### ISSUE TITLE
failed while pushing the image to the private registry repo. 

### ISSUE THREAD

**Issue by wh-afra** [alibaba/sealer#1170]
Hi 

Sealer is an amazing tool , and  I am trying to use it to  build my own cluster deployment .

when pushing the image to private registry , i met with the error as following
manifest invalid: manifest invalid

I have tried the docker push .... on the same machine ,it is ok .

I am not sure that the problem is the bug of the sealer .
however ,could  you give  me some advice?

thank you .

#### Environment:

- sealer version 0.6.1
- OS ubuntu Ubuntu 18.04.5 LTS
- Kernel Linux T-SH-GITE015 4.15.0-136-generic
- Install tools:  docker version: 20.10.12
- Others: registry repo: jfrog artifactory 6.12.2

**Comment by kakaZhou719** [comment]
could you pls share your push cmd ?
