### ISSUE TITLE
sealer run **Get "https://apiserver.cluster.local:6443/version?timeout=32s": connection refused**

### ISSUE THREAD

**Issue by katepangLiu** [alibaba/sealer#1175]
#### What happened:

```
sealer run kubernetes:v1.19.8 --masters 192.168.12.129 --passwd xxxxxx
Error: Get "https://apiserver.cluster.local:6443/version?timeout=32s": dial tcp 10.103.97.2:6443: connect: connection refused
```

#### What you expected to happen:
Init k8s cluster successfully.

#### Environment:

- sealer version:  
`{"gitVersion":"v0.6.1","gitCommit":"8c079bd","buildDate":"2022-01-06 02:57:07","goVersion":"go1.16.12","compiler":"gc","platform":"linux/amd64"}`
- OS (e.g: `cat /etc/os-release`):
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- Kernel (e.g. `uname -a`):
``
Linux miffy.katepang 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
``

**Comment by fanux** [comment]
Clean your host:

1. kubeadm reset and  rm -rf ~/.kube, rm -rf .sealer
2. check etc/hosts, delete apiserver.cluster.local item.

**Comment by katepangLiu** [comment]
> Clean your host:
> 
> 1. kubeadm reset and  rm -rf ~/.kube, rm -rf .sealer
> 2. check etc/hosts, delete apiserver.cluster.local item.

Thanks,  `rm -rf .sealer`  work for you.
