### ISSUE TITLE
kubernetes-v1.20.15 lvscare 镜像拉取失败

### ISSUE THREAD

**Issue by ceunfish** [alibaba/sealer#1188]
#### What happened:
内网环境部署，lvscare 镜像拉取失败。

#### Environment:

- sealer version (use `sealer version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by fanux** [comment]
Duplicate with https://github.com/alibaba/sealer/issues/1186

**Comment by fanux** [comment]
We will fix it today, @Stevent-fei

**Comment by Stevent-fei** [comment]
resolve
