### ISSUE TITLE
can not init kube master

### ISSUE THREAD

**Issue by fanspace** [alibaba/sealer#1195]
#### What happened:

[preflight] Some fatal errors occurred:
	[ERROR ImagePull]: failed to pull image sea.hub:5000/library/kube-apiserver:v1.19.8: output: Error response from daemon: Get "https://sea.hub:5000/v2/": x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0
, error: exit status 1
	[ERROR ImagePull]: failed to pull image sea.hub:5000/library/kube-controller-manager:v1.19.8: output: Error response from daemon: Get "https://sea.hub:5000/v2/": x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0
, error: exit status 1
	[ERROR ImagePull]: failed to pull image sea.hub:5000/library/kube-scheduler:v1.19.8: output: Error response from daemon: Get "https://sea.hub:5000/v2/": x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0
, error: exit status 1
	[ERROR ImagePull]: failed to pull image sea.hub:5000/library/kube-proxy:v1.19.8: output: Error response from daemon: Get "https://sea.hub:5000/v2/": x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0
, error: exit status 1
	[ERROR ImagePull]: failed to pull image sea.hub:5000/library/pause:3.2: output: Error response from daemon: Get "https://sea.hub:5000/v2/": x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0
, error: exit status 1
	[ERROR ImagePull]: failed to pull image sea.hub:5000/library/etcd:3.4.13-0: output: Error response from daemon: Get "https://sea.hub:5000/v2/": x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0
, error: exit status 1
	[ERROR ImagePull]: failed to pull image sea.hub:5000/library/coredns:1.7.0: output: Error response from daemon: Get "https://sea.hub:5000/v2/": x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0
, error: exit status 1
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
error execution phase preflight
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run.func1
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:235
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).visitAll
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:422
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:207
k8s.io/kubernetes/cmd/kubeadm/app/cmd.NewCmdInit.func1
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/init.go:149
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:842
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:950
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:887
k8s.io/kubernetes/cmd/kubeadm/app.Run
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:50
main.main
	_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:25
runtime.main
	/usr/local/go/src/runtime/proc.go:204
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1374

Error: failed to init master0 init master0 failed, error: [ssh][192.168.0.111]run command failed [kubeadm init --config=/var/lib/sealer/data/my-cluster/rootfs/kubeadm-config.yaml --upload-certs -v 6 --ignore-preflight-errors=SystemVerification]. Please clean and reinstall

#### How to reproduce it (as minimally and precisely as possible):

sealer run kubernetes:v1.19.8 --masters 192.168.0.111 --nodes 192.168.0.112,192.168.0.113 --passwd xxxxxx

#### Environment:

- sealer version (use `sealer version`): 0.6.1
- Cloud provider or hardware configuration: vm
- OS (e.g: `cat /etc/os-release`): ubuntu 20
- Kernel (e.g. `uname -a`): 5.4.0-96-generic
- Install tools:
- Others:

**Comment by kakaZhou719** [comment]
@fanspace ,yes its a bug at the version 0.6.1, and the code tree of main already fixed this.  see for more details : https://github.com/alibaba/sealer/commit/2992f876e4144cfa0a45d0c33b29f58e467512e7

**Comment by fanux** [comment]
@fanspace we will release 0.7 this week.
