### ISSUE TITLE
Clusterfile中的密码是明文存储的不太安全

### ISSUE THREAD

**Issue by ceunfish** [alibaba/sealer#1201]
## Issue Description

Type: *feature request*

### Describe what feature you want
Clusterfile中的密码，希望能够加密存储增强安全。

**Comment by fanux** [comment]
How about if Spec.ssh.passwd not exist, prompt to let user input from stdin

**Comment by neo502721** [comment]
How about encrypt the passwd in ClusterFile and replace it. We can save the secret key in sealer code.  Decrypt the encrypted password before using it again.

**Comment by fanux** [comment]
@neo502721 I think it is indeed safer than the current way, you are willing to provide this feature?

**Comment by neo502721** [comment]
Yes, I'm willing to.

> @neo502721 I think it is indeed safer than the current way, you are willing to provide this feature?

**Comment by neo502721** [comment]
Hi, I'm sorry it took so long. The code development is almost complete. I will create a pr after test.
