### ISSUE TITLE
Kubefile env not work

### ISSUE THREAD

**Issue by wanggd0313** [alibaba/sealer#1212]
# Kubefile is as follow:
FROM registry.cn-qingdao.aliyuncs.com/sealer-io/kubernetes:{{.Image.KubernetesVersion}}
# Prepare Helm and cnbaas plugin
COPY helm /bin
COPY helm-cnbaas-plugin /home/cnbaas
COPY cnbaas-base /home/cnbaas
#COPY plugins/cnbaas-catalog.yaml plugin
COPY install.sh /home/cnbaas
COPY cnbaas-base/imageList manifests
CMD chmod 700 home/cnbaas/install.sh
CMD home/cnbaas/install.sh ${cnbaas_helm} ${cnbaas_chartmuseum} ${cnbaas_kyverno}

# Sealer run cmd
	sealer pull adp-registry.cn-shanghai.cr.aliyuncs.com/cnbaas-sealer/cnbaas:cnbaas-base-v1.19.8
	sealer run adp-registry.cn-shanghai.cr.aliyuncs.com/cnbaas-sealer/cnbaas:cnbaas-base-v1.19.8  \
		-e cnbaas_helm='helm' \
		-e cnbaas_chartmuseum='chartmuseum' \
		-e cnbaas_kyverno='kyverno' \
		--masters xxxx--passwd xxxx

**Comment by bxy4543** [comment]
```shell
sealer run adp-registry.cn-shanghai.cr.aliyuncs.com/cnbaas-sealer/cnbaas:cnbaas-base-v1.19.8  \
	--cmd-args cnbaas_helm='helm' \
	--cmd-args cnbaas_chartmuseum='chartmuseum' \
	--cmd-args cnbaas_kyverno='kyverno' \
	--masters xxxx--passwd xxxx
```
The CMD command need to be used with the cmd-args parameter.
docs:  https://github.com/alibaba/sealer/blob/main/docs/site/src/docs/getting-started/build-cloudimage.md#build-arg

**Comment by wanggd0313** [comment]
Well done. with you comment, I try it successfully.
sealer run adp-registry.cn-shanghai.cr.aliyuncs.com/cnbaas-sealer/cnbaas:cnbaas-base-v1.19.8  \
	--cmd-args cnbaas_helm=helm,cnbaas_chartmuseum=chartmuseum,cnbaas_kyverno=kyverno \
	--masters xxxx--passwd xxxx
