### ISSUE TITLE
v0.7.0 join node faild

### ISSUE THREAD

**Issue by clcc2019** [alibaba/sealer#1216]
<img width="1493" alt="image" src="https://user-images.githubusercontent.com/46099295/156875264-e340a45d-21cf-426e-8935-67006875ba75.png">

**Comment by bxy4543** [comment]
The new version updates the cloud image (including the seautil tool) and requires a re-download of the cloud images

**Comment by clcc2019** [comment]
> The new version updates the cloud image (including the seautil tool) and requires a re-download of the cloud images

ok
