### ISSUE TITLE
sealer部署集群组件后期重要组件可以单独升级或者手动升级

### ISSUE THREAD

**Issue by lklkxcxc** [alibaba/sealer#1219]
## Issue Description

Type: *feature request*
集群组件单独升级

### Describe what feature you want
sealer部署集群后，主要组件后期可以单独升级，比如docker ，k8s组件出现bug时可以进行修复，另外应对社区停止更新后可以人工接管集群的后续维护

**Comment by fanux** [comment]
sealer already support upgrade feature. For example, if kubernetes v1.19.8 component has bug, we will release a new version CloudImage like v1.20.3.  you are just using `sealer upgrade --image kubernetes:v1.20.3` to upgrade your cluster.

If you want to upgrade any component manually, just follow kubeadm workflow~
