### ISSUE TITLE
可否提供如下的功能需求

### ISSUE THREAD

**Issue by zhaosonghai** [alibaba/sealer#123]
1、支持使用本地docker，可以支持docker自定义参数，包括registry-mirrors，data-root、insecure-registries等；
2、支持批量清理本地集群的功能；
3、支持自定义镜像名称，使用本地仓库地址可以拉取到部署的镜像；

**Comment by cuisongliu** [comment]
please using english? @zhaosonghai 

1. sealer custom the docker engine ,so not support local docker
2. in development feature clean feature

**Comment by fanux** [comment]
1. docker自定义参数可以支持，但是必须用sealer提供的docker，配置文件也有一些注意事项，这个我们文档中描述
2. 清理本地集群是基本功能，目前在测试阶段 请 @cuisongliu 尽快发布
3. 这里的镜像是指容器镜像还是集群镜像？

**Comment by zhaosonghai** [comment]
集群镜像

**Comment by fanux** [comment]
嗯 集群镜像肯定是支持私有仓库的，如果有问题我们第一优先级解决。
