### ISSUE TITLE
直接运行报错：failed invalid CIDR address

### ISSUE THREAD

**Issue by imdingtalk** [alibaba/sealer#1251]
直接运行：
sealer run kubernetes:v1.19.9 --masters 10.1.3.109 --passwd 1

-->

`runtimeRequestTimeout: 2m0s
serializeImagePulls: true
staticPodPath: /etc/kubernetes/manifests
streamingConnectionIdleTimeout: 4h0m0s
syncFrequency: 1m0s
volumeStatsAggPeriod: 1m0s" > kubeadm-config.yaml
Error: failed to gernerate cert generate certs failed generator cert config failed invalid CIDR address: 
Usage:
  sealer run [flags]

Examples:

create default cluster:
	sealer run registry.cn-qingdao.aliyuncs.com/sealer-io/kubernetes:v1.19.8

create cluster by cloud provider, just set the number of masters or nodes:
	sealer run registry.cn-qingdao.aliyuncs.com/sealer-io/kubernetes:v1.19.8 --masters 3 --nodes 3

create cluster to your baremetal server, appoint the iplist:
	sealer run registry.cn-qingdao.aliyuncs.com/sealer-io/kubernetes:v1.19.8 --masters 192.168.0.2,192.168.0.3,192.168.0.4 \
		--nodes 192.168.0.5,192.168.0.6,192.168.0.7

Flags:
  -h, --help               help for run
  -m, --masters string     set Count or IPList to masters
  -n, --nodes string       set Count or IPList to nodes
  -p, --passwd string      set cloud provider or baremetal server password
      --pk string          set baremetal server private key (default "/root/.ssh/id_rsa")
      --pk-passwd string   set baremetal server  private key password
      --podcidr string     set default pod CIDR network. example '10.233.0.0/18'
      --svccidr string     set default service CIDR network. example '10.233.64.0/18'
  -u, --user string        set baremetal server username (default "root")

Global Flags:
      --config string   config file (default is $HOME/.sealer.json)
  -d, --debug           turn on debug mode

failed to gernerate cert generate certs failed generator cert config failed invalid CIDR address:`

-->

#### Environment:

- sealer version (use `sealer version`):  {"gitVersion":"v0.5.1","gitCommit":"6f29651","buildDate":"2021-10-22 09:59:42","goVersion":"go1.14.15","compiler":"gc","platform":"linux/amd64"}
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):  CentOS-7
- Kernel (e.g. `uname -a`): Linux node02 5.4.167-1.el7.elrepo.x86_64 #1 SMP Fri Dec 17 08:30:33 EST 2021 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:
- image info： 1fca3804f77284b62172c57ddfcb6ec1c3c7d35c125e8684db94b296686a6ace | kubernetes:v1.19.9

**Comment by fanux** [comment]
Using sealer 0.7.0

**Comment by imdingtalk** [comment]
> Using sealer 0.7.0

```
sealer run kubernetes:v1.19.9 --masters 10.1.3.109 --passwd 1
......
......
failed to init master0 init master0 failed, error: [ssh][10.1.3.109]run command failed [kubeadm init --config=/var/lib/sealer/data/my-cluster/rootfs/etc/kubeadm.yml --upload-certs -v 0 --ignore-preflight-errors=SystemVerification]. Please clean and reinstall
```

**Comment by bxy4543** [comment]
What is the image ID?

**Comment by imdingtalk** [comment]
> What is the image ID?

1fca3804f77284b62172c57ddfcb6ec1c3c7d35c125e8684db94b296686a6ace | kubernetes:v1.19.9
