### ISSUE TITLE
运行sealer run示例报错

### ISSUE THREAD

**Issue by jokimina** [alibaba/sealer#1256]
#### Anything else we need to know?:
<img width="852" alt="image" src="https://user-images.githubusercontent.com/11460661/158791254-a2044981-f81c-4b77-a87f-2d08d18ce230.png">

#### Environment:

- sealer version (use `sealer version`): {"gitVersion":"v0.7.1","gitCommit":"2a4d201","buildDate":"2022-03-16 06:41:35","goVersion":"go1.16.14","compiler":"gc","platform":"linux/amd64"}
- Cloud provider or hardware configuration: 
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

https://github.com/alibaba/sealer/blob/main/apply/run.go#L96
貌似并无count相关判断, 是否尚未实现?

**Comment by kakaZhou719** [comment]
@jokimina , This feature is not implemented yet。at present ,sealer run only support  local run. "count" filed support apply k8s cluster at ali cloud.

**Comment by kakaZhou719** [comment]
#1291 fix this
