### ISSUE TITLE
CMD helm install ... failed

### ISSUE THREAD

**Issue by laotoutou** [alibaba/sealer#1257]
## Issue Description

sealer run xxx --masters xxx --nodes xxx --pk /root/.ssh/id_rsa
......
W0318 01:09:34.314665   21136 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
W0318 01:09:34.437303   21136 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
Error: Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": Post "https://ingress-nginx-controller-admission.ingress-system.svc:443/networking/v1/ingresses?timeout=10s": no endpoints available for service "ingress-nginx-controller-admission"
Error: failed to execute command(cd /var/lib/sealer/data/my-cluster/rootfs && helm install jindowin charts2/jindowin -n jd-apaas -f charts2/jindowin/values.yaml -f charts2/jindowin/values-tag.yaml -f charts2/jindowin/values-resource.yaml --create-namespace) on host(10.0.0.5): output(W0318 01:09:34.314665   21136 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
W0318 01:09:34.437303   21136 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
Error: Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": Post "https://ingress-nginx-controller-admission.ingress-system.svc:443/networking/v1/ingresses?timeout=10s": no endpoints available for service "ingress-nginx-controller-admission"), error(Process exited with status 1)
Usage:
  sealer run [flags]

Examples:

create cluster by cloud provider, just set the number of masters or nodes,and default provider is ALI_CLOUD:
	sealer run kubernetes:v1.19.8 --masters 3 --nodes 3 --provider ALI_CLOUD

create cluster by docker container, set the number of masters or nodes, and set provider "CONTAINER":
	sealer run kubernetes:v1.19.8 --masters 3 --nodes 3 --provider CONTAINER

create cluster to your baremetal server, appoint the iplist:
	sealer run kubernetes:v1.19.8 --masters 192.168.0.2,192.168.0.3,192.168.0.4 \
		--nodes 192.168.0.5,192.168.0.6,192.168.0.7 --passwd xxx
  Specify server SSH port :
  All servers use the same SSH port (default port: 22)：
	sealer run kubernetes:v1.19.8 --masters 192.168.0.2,192.168.0.3,192.168.0.4 \
	--nodes 192.168.0.5,192.168.0.6,192.168.0.7 --port 24 --passwd xxx
  Different SSH port numbers exist：
	sealer run kubernetes:v1.19.8 --masters 192.168.0.2,192.168.0.3:23,192.168.0.4:24 \
	--nodes 192.168.0.5:25,192.168.0.6:25,192.168.0.7:27 --passwd xxx
create a cluster with custom environment variables:
	sealer run -e DashBoardPort=8443 mydashboard:latest  --masters 192.168.0.2,192.168.0.3,192.168.0.4 \
	--nodes 192.168.0.5,192.168.0.6,192.168.0.7 --passwd xxx

Flags:
      --cmd-args strings     set args for image cmd instruction
  -e, --env strings          set custom environment variables
  -h, --help                 help for run
  -m, --masters string       set Count or IPList to masters
  -n, --nodes string         set Count or IPList to nodes
  -p, --passwd string        set cloud provider or baremetal server password
      --pk string            set baremetal server private key (default "/root/.ssh/id_rsa")
      --pk-passwd string     set baremetal server private key password
      --port string          set the sshd service port number for the server (default port: 22) (default "22")
      --provider ALI_CLOUD   set infra provider, example ALI_CLOUD, the local server need ignore this
  -u, --user string          set baremetal server username (default "root")

Global Flags:
      --config string   config file (default is $HOME/.sealer.json)
  -d, --debug           turn on debug mode

failed to execute command(cd /var/lib/sealer/data/my-cluster/rootfs && helm install jindowin charts2/jindowin -n jd-apaas -f charts2/jindowin/values.yaml -f charts2/jindowin/values-tag.yaml -f charts2/jindowin/values-resource.yaml --create-namespace) on host(10.0.0.5): output(W0318 01:09:34.314665   21136 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
W0318 01:09:34.437303   21136 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
Error: Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": Post "https://ingress-nginx-controller-admission.ingress-system.svc:443/networking/v1/ingresses?timeout=10s": no endpoints available for service "ingress-nginx-controller-admission"), error(Process exited with status 1)

### Describe what feature you want

helm install failed, because ingress-nginx is not ready yet（k8s and ingress-nginx  are installed by sealer）

### Additional context

so what should i do, please

**Comment by bxy4543** [comment]
```
#Kubefile
...
COPY wait-ingress.sh scripts
CMD sh wait-ingress.sh
CMD helm xxx
```
You can add a waiting for ingress script before executing helm

**Comment by laotoutou** [comment]
> 

good idea
