### ISSUE TITLE
build cloudImage error when pulling image from private harbor with https

### ISSUE THREAD

**Issue by lusains** [alibaba/sealer#1261]
#### What happened:

sealer version 0.7.1

1、vi a kubefile
 `FROM registry.cn-qingdao.aliyuncs.com/sealer-io/kubernetes:v1.19.8
COPY imageList manifests
#安装helm
COPY depends/helm/helm-v3.6.0-linux-amd64.tar.gz .
CMD tar zxvf helm-v3.6.0-linux-amd64.tar.gz && cp linux-amd64/helm /usr/bin && chmod +x /usr/bin/helm

#安装openebs-localpv
COPY depends/openebs/localpv/localpv-operator.yaml manifests/localpv/
CMD kubectl apply -f manifests/localpv/localpv-operator.yaml

#安装minio 标准S3的oss对象存储，minio依赖localpv
#COPY depends/minio manifests/
#CMD kubectl apply -f manifests/minio/minio-manifest.yaml

#安装mysql  依赖localpv
COPY depends/mysql manifests/
CMD kubectl apply -f manifests/mysql/mysql-manifest.yaml

#安装redis  依赖localpv
COPY depends/redis manifests/
CMD kubectl apply -f manifests/redis/redis-manifest.yaml

#安装 es
#安装harbor

#安装ingress-nginx
COPY depends/ingress-nginx manifests/
CMD kubectl apply -f manifests/ingress-nginx/ingress-nginx-manifest.yaml

#通过helm安装csp
COPY csp ./charts
CMD helm install csp charts/csp
`
2、sealer login my private harbor 
      
![image](https://user-images.githubusercontent.com/7510547/158977466-f69e1a8b-cc65-4fd1-9bdd-53dc085a1292.png)

3、build my cloudImage，log error info：
![image](https://user-images.githubusercontent.com/7510547/158977926-27fa0542-9275-4d30-96c1-b688c1e2b120.png)
   but with docker pulling the image successful；
4、try copy the harbor tls to /etc/pki/ca-trust/source/anchors/ but failed again

#### What you expected to happen:

build my cloudImage with lite can success

**Comment by fanux** [comment]
![image](https://user-images.githubusercontent.com/8912557/159395935-61467739-b6e4-4c48-9eef-bccfa80e1e26.png)
This image already exist in your registry?

**Comment by lusains** [comment]
I'am sure my private harbor contain these images~
