### ISSUE TITLE
ENV in script 未生效

### ISSUE THREAD

**Issue by BussanQ** [alibaba/sealer#1277]
ENV in script 未生效
![image](https://user-images.githubusercontent.com/10459811/160521882-680bd193-d59a-454a-97b2-1f2b308cc21e.png)
修改init.sh 为

```#!/bin/bash
# Install docker
chmod a+x docker.sh
path=${docker_dir:-/var/lib/docker}
sh docker.sh $path
chmod a+x init-kube.sh
sh init-kube.sh
```

重新build 镜像
执行sealer run -e docker_dir=/home/docker myKubernetes:v1.19.8 -m xx -p xx 
测试执行init.sh的时候并未读取到环境变量 docker_dir

sealer version 0.7.1

**Comment by Stevent-fei** [comment]
fixed

**Comment by Mr-lixh** [comment]
@Stevent-fei shell中包含&&操作时，envProcessor的wrapperShell依旧不起作用，是否可以使用export env&& shell操作？
<img width="1348" alt="image" src="https://user-images.githubusercontent.com/54052826/161435155-1861bc2d-a453-447d-a2fa-cae52544323f.png">

**Comment by Stevent-fei** [comment]
you can use : export env&& env shell
