### ISSUE TITLE
A uniform case format should be maintained for the plugin enum value 

### ISSUE THREAD

**Issue by Starnop** [alibaba/sealer#1282]
## Issue Description

Type: *feature request*

The plugin type enumerated value are all capitalized except taint, and this is clearly unreasonable.

FYI

> https://github.com/alibaba/sealer/blob/main/pkg/plugin/plugin.go#L39-L48

> const (
	// Plugin used for golang so file to find the related symbol
	Plugin             = "Plugin"
	PluginType         = "PluginType"
	EtcdPlugin         = "ETCD"
	LabelPlugin        = "LABEL"
	ShellPlugin        = "SHELL"
	TaintPlugin        = "Taint"
	HostNamePlugin     = "HOSTNAME"
	ClusterCheckPlugin = "CLUSTERCHECK"
)

### Describe what feature you want

A uniform case format should be maintained for the plugin enum value 

### Additional context
I think it should be fixed ASAP.

**Comment by kakaZhou719** [comment]
@Stevent-fei , also need to modify the related doc.
