### ISSUE TITLE
ubuntu 21.10 ARM64 use sealer   run  fail

### ISSUE THREAD

**Issue by bxvs888** [alibaba/sealer#1288]
#### How to reproduce it (as minimally and precisely as possible):

./imagebuild  v1.23.5 arm64 
cloudImage

  sealer run kubernetes:v1.23.5 --masters 192.168.64.18 --nodes 192.168.64.19,192.168.64.20  --passwd 123456

#### Environment:

- sealer version (use `sealer version`): 0.7.1.arm64
- Cloud provider or hardware configuration:  
- OS (e.g: `cat /etc/os-release`): ubuntu linux for arm64 21.10
- Kernel (e.g. `uname -a`): Linux k8s0 5.13.0-35-generic #40-Ubuntu SMP Mon Mar 7 08:06:10 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
- Install tools: docker
- Others:

log

copying files to 192.168.64.20: 33/33 
2022-04-02 14:04:55 [INFO] [kube_certs.go:234] APIserver altNames :  {map[apiserver.cluster.local:apiserver.cluster.local k8s0:k8s0 kubernetes:kubernetes kubernetes.default:kubernetes.default kubernetes.default.svc:kubernetes.default.svc kubernetes.default.svc.cluster.local:kubernetes.default.svc.cluster.local localhost:localhost] map[10.103.97.2:10.103.97.2 10.96.0.1:10.96.0.1 127.0.0.1:127.0.0.1 172.16.0.181:172.16.0.181 192.168.64.18:192.168.64.18]}
2022-04-02 14:04:55 [INFO] [kube_certs.go:254] Etcd altnames : {map[k8s0:k8s0 localhost:localhost] map[127.0.0.1:127.0.0.1 192.168.64.18:192.168.64.18 ::1:::1]}, commonName : k8s0
2022-04-02 14:04:55 [INFO] [kube_certs.go:262] sa.key sa.pub already exist
2022-04-02 14:04:56 [INFO] [kubeconfig.go:277] [kubeconfig] Using existing kubeconfig file: "/var/lib/sealer/data/my-cluster/admin.conf"

2022-04-02 14:04:56 [INFO] [kubeconfig.go:277] [kubeconfig] Using existing kubeconfig file: "/var/lib/sealer/data/my-cluster/controller-manager.conf"

2022-04-02 14:04:56 [INFO] [kubeconfig.go:277] [kubeconfig] Using existing kubeconfig file: "/var/lib/sealer/data/my-cluster/scheduler.conf"

2022-04-02 14:04:56 [INFO] [kubeconfig.go:277] [kubeconfig] Using existing kubeconfig file: "/var/lib/sealer/data/my-cluster/kubelet.conf"

init-registry.sh: 1: opyright: not found
+ dirname init-registry.sh
+ cd .
+ REGISTRY_PORT=5000
+ VOLUME=/var/lib/sealer/data/my-cluster/rootfs/registry
+ REGISTRY_DOMAIN=sea.hub
+ container=sealer-registry
+ pwd
+ dirname /var/lib/sealer/data/my-cluster/rootfs/scripts
+ rootfs=/var/lib/sealer/data/my-cluster/rootfs
+ config=/var/lib/sealer/data/my-cluster/rootfs/etc/registry_config.yml
+ htpasswd=/var/lib/sealer/data/my-cluster/rootfs/etc/registry_htpasswd
+ certs_dir=/var/lib/sealer/data/my-cluster/rootfs/certs
+ image_dir=/var/lib/sealer/data/my-cluster/rootfs/images
+ mkdir -p /var/lib/sealer/data/my-cluster/rootfs/registry
+ [ -f /var/lib/sealer/data/my-cluster/rootfs/images/registry.tar ]
+ docker load -q -i /var/lib/sealer/data/my-cluster/rootfs/images/registry.tar
Loaded image: registry:2.7.1
+ docker ps -aq -f name=sealer-registry
+ [ a41a81287869 ]
+ docker rm -f sealer-registry
sealer-registry
+ regArgs=-d --restart=always --net=host --name sealer-registry -v /var/lib/sealer/data/my-cluster/rootfs/certs:/certs -v /var/lib/sealer/data/my-cluster/rootfs/registry:/var/lib/registry -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/sea.hub.crt -e REGISTRY_HTTP_TLS_KEY=/certs/sea.hub.key
+ [ -f /var/lib/sealer/data/my-cluster/rootfs/etc/registry_config.yml ]
+ sed -i s/5000/5000/g /var/lib/sealer/data/my-cluster/rootfs/etc/registry_config.yml
+ regArgs=-d --restart=always --net=host --name sealer-registry -v /var/lib/sealer/data/my-cluster/rootfs/certs:/certs -v /var/lib/sealer/data/my-cluster/rootfs/registry:/var/lib/registry -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/sea.hub.crt -e REGISTRY_HTTP_TLS_KEY=/certs/sea.hub.key     -v /var/lib/sealer/data/my-cluster/rootfs/etc/registry_config.yml:/etc/docker/registry/config.yml
+ [ -f /var/lib/sealer/data/my-cluster/rootfs/etc/registry_htpasswd ]
+ docker run -d --restart=always --net=host --name sealer-registry -v /var/lib/sealer/data/my-cluster/rootfs/certs:/certs -v /var/lib/sealer/data/my-cluster/rootfs/registry:/var/lib/registry -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/sea.hub.crt -e REGISTRY_HTTP_TLS_KEY=/certs/sea.hub.key -v /var/lib/sealer/data/my-cluster/rootfs/etc/registry_config.yml:/etc/docker/registry/config.yml registry:2.7.1
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
7b7f45fb4abf10d7f12b4cf9bb3235025cc928453a10ac6cfa897daa3c3cf87e
192.168.64.18 sea.hub
192.168.64.18 apiserver.cluster.local
2022-04-02 14:04:58 [INFO] [init.go:250] start to init master0...

**Comment by kakaZhou719** [comment]
@bxvs888 , read this form log: "init-registry.sh: 1: opyright: not found". seams the auto build scripts has some problems .

**Comment by kakaZhou719** [comment]
@Stevent-fei ,please fix this.

**Comment by bxvs888** [comment]
@kakaZhou719  @Stevent-fei  发现rootfs 中bin 目录seautil,conntrack,crictl,nerdctl  不是arm64 结构

root@k8s0:/var/lib/sealer/data/my-cluster/rootfs/bin# file *
conntrack:                        ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=335d8670140158b282cb5c7ce3af852ed8046a22, stripped
containerd-rootless-setuptool.sh: POSIX shell script, ASCII text executable
containerd-rootless.sh:           POSIX shell script, ASCII text executable
crictl:                           ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=qMZl85i0bEBUbXC8oGDg/cZr2CSyy_b49jN9KeaWB/I-cb5UdI5KFIv7_mABsn/jAE91wvSElyZkUgGMnt7, not stripped
kubeadm:                          ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, Go BuildID=92-TyECt5l7aXjJYkI3X/eyw252JArAC4v5apG8H9/AVP668ly1eWppMFqRlLD/PYbgZgcLJnB9Rq8nyxEd, stripped
kubectl:                          ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, Go BuildID=9M0nGjTqdsyZUa5KNB0A/oDFarysKJrk4-st0A4BS/Ck6gTJOjdW7hvUVH-1jc/ioR1ML8BtfIXVOULjI96, stripped
kubelet:                          ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, BuildID[sha1]=12192aae368bfcbed2b8f461cdc4dda2f548d58c, for GNU/Linux 3.7.0, stripped
nerdctl:                          ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=IpbYKy2h-00B83fo6vIM/fLJ8zOM25GMWLeeA7Jbb/Zt4ya9TRFG6MMIa3ngHK/AgzMiWx3bJ794nOHMLqG, stripped
seautil:                          ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=9MN6MJteayopWbi4qnmh/yRU_KjqXSC-V6jazv1Ek/FdXhIZDwpOltVfzRoDie/aFbssxEib9O0ATc1ZTf5, stripped
root@k8s0:/var/lib/sealer/data/my-cluster/rootfs/bin#

**Comment by kakaZhou719** [comment]
@bxvs888 ,yes its truly a bug,@Stevent-fei will fix this later.

**Comment by bxvs888** [comment]
thanks

**Comment by bxy4543** [comment]
v0.8.2 fixed
