### ISSUE TITLE
ubuntu 21.10 arm64 sealer 0.8 run fail Error response from daemon: manifest for sea.hub:5000/coredns:v1.8.6 not found: manifest unknown: manifest unknown

### ISSUE THREAD

**Issue by bxvs888** [alibaba/sealer#1299]
+ dirname init-registry.sh
+ cd .
+ REGISTRY_PORT=5000
+ VOLUME=/var/lib/sealer/data/my-cluster/rootfs/registry
+ REGISTRY_DOMAIN=sea.hub
+ container=sealer-registry
+ pwd
+ dirname /var/lib/sealer/data/my-cluster/rootfs/scripts
+ rootfs=/var/lib/sealer/data/my-cluster/rootfs
+ config=/var/lib/sealer/data/my-cluster/rootfs/etc/registry_config.yml
+ htpasswd=/var/lib/sealer/data/my-cluster/rootfs/etc/registry_htpasswd
+ certs_dir=/var/lib/sealer/data/my-cluster/rootfs/certs
+ image_dir=/var/lib/sealer/data/my-cluster/rootfs/images
+ mkdir -p /var/lib/sealer/data/my-cluster/rootfs/registry
+ load_images
+ [ -f /var/lib/sealer/data/my-cluster/rootfs/images/registry.tar ]
+ docker load -q -i /var/lib/sealer/data/my-cluster/rootfs/images/registry.tar
Loaded image: registry:2.7.1
+ docker ps -aq -f name=sealer-registry
+ [ d5a42ace61e5 ]
+ docker rm -f sealer-registry
sealer-registry
+ regArgs=-d --restart=always --net=host --name sealer-registry -v /var/lib/sealer/data/my-cluster/rootfs/certs:/certs -v /var/lib/sealer/data/my-cluster/rootfs/registry:/var/lib/registry -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/sea.hub.crt -e REGISTRY_HTTP_TLS_KEY=/certs/sea.hub.key
+ [ -f /var/lib/sealer/data/my-cluster/rootfs/etc/registry_config.yml ]
+ sed -i s/5000/5000/g /var/lib/sealer/data/my-cluster/rootfs/etc/registry_config.yml
+ regArgs=-d --restart=always --net=host --name sealer-registry -v /var/lib/sealer/data/my-cluster/rootfs/certs:/certs -v /var/lib/sealer/data/my-cluster/rootfs/registry:/var/lib/registry -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/sea.hub.crt -e REGISTRY_HTTP_TLS_KEY=/certs/sea.hub.key     -v /var/lib/sealer/data/my-cluster/rootfs/etc/registry_config.yml:/etc/docker/registry/config.yml
+ [ -f /var/lib/sealer/data/my-cluster/rootfs/etc/registry_htpasswd ]
+ docker run -d --restart=always --net=host --name sealer-registry -v /var/lib/sealer/data/my-cluster/rootfs/certs:/certs -v /var/lib/sealer/data/my-cluster/rootfs/registry:/var/lib/registry -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/sea.hub.crt -e REGISTRY_HTTP_TLS_KEY=/certs/sea.hub.key -v /var/lib/sealer/data/my-cluster/rootfs/etc/registry_config.yml:/etc/docker/registry/config.yml registry:2.7.1
e183a6bec8feb13f7c2a4734096d9dd9110feb8581eb3b9d0b7d0b50fcdc2e8c
+ check_registry
+ n=1
init-registry.sh: 44: cannot open =: No such file
2022-04-07 11:49:41 [INFO] [init.go:250] start to init master0...
W0407 11:49:41.535029    4569 strict.go:55] error unmarshaling configuration schema.GroupVersionKind{Group:"kubeadm.k8s.io", Version:"v1beta3", Kind:"ClusterConfiguration"}: error unmarshaling JSON: while decoding JSON: json: unknown field "type"
[init] Using Kubernetes version: v1.23.5
[preflight] Running pre-flight checks
	[WARNING FileExisting-socat]: socat not found in system path
error execution phase preflight: [preflight] Some fatal errors occurred:
	[ERROR Port-10250]: Port 10250 is in use
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher
Error: failed to init master0 init master0 failed, error: [ssh][192.168.64.24]run command failed [kubeadm init --config=/var/lib/sealer/data/my-cluster/rootfs/etc/kubeadm.yml --upload-certs -v 0 --ignore-preflight-errors=SystemVerification]. Please clean and reinstall
Usage:
  sealer run [flags]

Examples:

create cluster to your bare metal server, appoint the iplist:
	sealer run kubernetes:v1.19.8 --masters 192.168.0.2,192.168.0.3,192.168.0.4 \
		--nodes 192.168.0.5,192.168.0.6,192.168.0.7 --passwd xxx

specify server SSH port :
  All servers use the same SSH port (default port: 22)：
	sealer run kubernetes:v1.19.8 --masters 192.168.0.2,192.168.0.3,192.168.0.4 \
	--nodes 192.168.0.5,192.168.0.6,192.168.0.7 --port 24 --passwd xxx

  Different SSH port numbers exist：
	sealer run kubernetes:v1.19.8 --masters 192.168.0.2,192.168.0.3:23,192.168.0.4:24 \
	--nodes 192.168.0.5:25,192.168.0.6:25,192.168.0.7:27 --passwd xxx

create a cluster with custom environment variables:
	sealer run -e DashBoardPort=8443 mydashboard:latest  --masters 192.168.0.2,192.168.0.3,192.168.0.4 \
	--nodes 192.168.0.5,192.168.0.6,192.168.0.7 --passwd xxx

Flags:
      --cluster-name string   set cluster name (default "my-cluster")
      --cmd-args strings      set args for image cmd instruction
  -e, --env strings           set custom environment variables
  -h, --help                  help for run
  -m, --masters string        set Count or IPList to masters
  -n, --nodes string          set Count or IPList to nodes
  -p, --passwd string         set cloud provider or baremetal server password
      --pk string             set baremetal server private key (default "/root/.ssh/id_rsa")
      --pk-passwd string      set baremetal server private key password
      --port uint16           set the sshd service port number for the server (default port: 22) (default 22)
      --provider ALI_CLOUD    set infra provider, example ALI_CLOUD, the local server need ignore this
  -u, --user string           set baremetal server username (default "root")

Global Flags:
      --config string   config file (default is $HOME/.sealer.json)
  -d, --debug           turn on debug mode

failed to init master0 init master0 failed, error: [ssh][192.168.64.24]run command failed [kubeadm init --config=/var/lib/sealer/data/my-cluster/rootfs/etc/kubeadm.yml --upload-certs -v 0 --ignore-preflight-errors=SystemVerification]. Please clean and reinstall

#### What happened:
 
./imagebuild v1.23.5 arm64 

  sealer run kubernetes:v1.23.5-alpine --masters 192.168.64.24 --nodes 192.168.64.25 --passwd 123456

#### Environment:

- sealer version (use `sealer version`): 0.8.0
- Cloud provider or hardware configuration: 
- OS (e.g: `cat /etc/os-release`): ubuntu 21.10 arm64
- Kernel (e.g. `uname -a`): Linux k0 5.13.0-35-generic #40-Ubuntu SMP Mon Mar 7 08:06:10 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
- Install tools: sealer 0.8.0
- Others:

**Comment by bxy4543** [comment]
```shell
sealer delete -a
```
environment is not clean, delete and run again

**Comment by bxvs888** [comment]
全新的操作系统也一样的。

 2022-04-07 12:22:14 [INFO] [init.go:250] start to init master0...
W0407 12:22:14.614750    9712 strict.go:55] error unmarshaling configuration schema.GroupVersionKind{Group:"kubeadm.k8s.io", Version:"v1beta3", Kind:"ClusterConfiguration"}: error unmarshaling JSON: while decoding JSON: json: unknown field "type"
[init] Using Kubernetes version: v1.23.5
发现是运行这个
kubeadm init --config=/var/lib/sealer/data/my-cluster/rootfs/etc/kubeadm.yml --upload-certs -v 0 --ignore-preflight-errors=SystemVerification
造成的。
/var/lib/sealer/data/my-cluster/rootfs/etc/kubeadm.yml 内容：

apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 192.168.64.24
  bindPort: 6443
nodeRegistration:
  criSocket: /var/run/dockershim.sock
  taints: null

---
apiServer:
  certSANs:
  - 127.0.0.1
  - apiserver.cluster.local
  - 10.103.97.2
  - 192.168.64.24
  - 127.0.0.1
  - apiserver.cluster.local
  - 10.103.97.2
  - 172.16.0.181
  extraArgs:
    audit-log-format: json
    audit-log-maxage: "7"
    audit-log-maxbackup: "10"
    audit-log-maxsize: "100"
    audit-log-path: /var/log/kubernetes/audit.log
    audit-policy-file: /etc/kubernetes/audit-policy.yml
    enable-aggregator-routing: "true"
    etcd-servers: https://192.168.64.24:2379
    feature-gates: TTLAfterFinished=true,EphemeralContainers=true
  extraVolumes:
  - hostPath: /etc/kubernetes
    mountPath: /etc/kubernetes
    name: audit
    pathType: DirectoryOrCreate
  - hostPath: /var/log/kubernetes
    mountPath: /var/log/kubernetes
    name: audit-log
    pathType: DirectoryOrCreate
  - hostPath: /etc/localtime
    mountPath: /etc/localtime
    name: localtime
    pathType: File
    readOnly: true
apiVersion: kubeadm.k8s.io/v1beta3
controlPlaneEndpoint: apiserver.cluster.local:6443
controllerManager:
  extraArgs:
    experimental-cluster-signing-duration: 876000h
    feature-gates: TTLAfterFinished=true,EphemeralContainers=true
  extraVolumes:
  - hostPath: /etc/localtime
    mountPath: /etc/localtime
    name: localtime
    pathType: File
    readOnly: true
dns:
  type: ""
etcd:
  local:
    dataDir: ""
    extraArgs:
      listen-metrics-urls: http://0.0.0.0:2381
imageRepository: sea.hub:5000
kind: ClusterConfiguration
kubernetesVersion: v1.23.5
networking:
  podSubnet: 100.64.0.0/10
  serviceSubnet: 10.96.0.0/22
scheduler:
  extraArgs:
    feature-gates: TTLAfterFinished=true,EphemeralContainers=true
  extraVolumes:
  - hostPath: /etc/localtime
    mountPath: /etc/localtime
    name: localtime
    pathType: File
    readOnly: true

---
apiVersion: kubelet.config.k8s.io/v1beta1
authentication:
  anonymous:
    enabled: false
  webhook:
    cacheTTL: 2m0s
    enabled: true
  x509:
    clientCAFile: /etc/kubernetes/pki/ca.crt
authorization:
  mode: Webhook
  webhook:
    cacheAuthorizedTTL: 5m0s
    cacheUnauthorizedTTL: 30s
cgroupDriver: cgroupfs
cgroupsPerQOS: true
clusterDomain: cluster.local
configMapAndSecretChangeDetectionStrategy: Watch
containerLogMaxFiles: 5
containerLogMaxSize: 10Mi
contentType: application/vnd.kubernetes.protobuf
cpuCFSQuota: true
cpuCFSQuotaPeriod: 100ms
cpuManagerPolicy: none
cpuManagerReconcilePeriod: 10s
enableControllerAttachDetach: true
enableDebuggingHandlers: true
enforceNodeAllocatable:
- pods
eventBurst: 10
eventRecordQPS: 5
evictionHard:
  imagefs.available: 15%
  memory.available: 100Mi
  nodefs.available: 10%
  nodefs.inodesFree: 5%
evictionPressureTransitionPeriod: 5m0s
failSwapOn: true
fileCheckFrequency: 20s
hairpinMode: promiscuous-bridge
healthzBindAddress: 127.0.0.1
healthzPort: 10248
httpCheckFrequency: 20s
imageGCHighThresholdPercent: 85
imageGCLowThresholdPercent: 80
imageMinimumGCAge: 2m0s
iptablesDropBit: 15
iptablesMasqueradeBit: 14
kind: KubeletConfiguration
kubeAPIBurst: 10
kubeAPIQPS: 5
logging: {}
makeIPTablesUtilChains: true
maxOpenFiles: 1000000
maxPods: 110
nodeLeaseDurationSeconds: 40
nodeStatusReportFrequency: 10s
nodeStatusUpdateFrequency: 10s
oomScoreAdj: -999
podPidsLimit: -1
port: 10250
registryBurst: 10
registryPullQPS: 5
rotateCertificates: true
runtimeRequestTimeout: 2m0s
serializeImagePulls: true
shutdownGracePeriod: 0s
shutdownGracePeriodCriticalPods: 0s
staticPodPath: /etc/kubernetes/manifests
streamingConnectionIdleTimeout: 4h0m0s
syncFrequency: 1m0s
volumeStatsAggPeriod: 1m0s

---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
bindAddress: ""
bindAddressHardFail: false
clientConnection:
  acceptContentTypes: ""
  burst: 0
  contentType: ""
  kubeconfig: ""
  qps: 0
clusterCIDR: ""
configSyncPeriod: 0s
conntrack:
  maxPerCore: null
  min: null
  tcpCloseWaitTimeout: null
  tcpEstablishedTimeout: null
detectLocalMode: ""
enableProfiling: false
healthzBindAddress: ""
hostnameOverride: ""
iptables:
  masqueradeAll: false
  masqueradeBit: null
  minSyncPeriod: 0s
  syncPeriod: 0s
ipvs:
  excludeCIDRs:
  - 10.103.97.2/32
  minSyncPeriod: 0s
  scheduler: ""
  strictARP: false
  syncPeriod: 0s
  tcpFinTimeout: 0s
  tcpTimeout: 0s
  udpTimeout: 0s
kind: KubeProxyConfiguration
metricsBindAddress: ""
mode: ipvs
nodePortAddresses: null
oomScoreAdj: null
portRange: ""
showHiddenMetricsForVersion: ""
udpIdleTimeout: 0s
winkernel:
  enableDSR: false
  networkName: ""
  sourceVip: ""

**Comment by bxvs888** [comment]
@[bxy4543](https://github.com/bxy4543)

**Comment by bxvs888** [comment]
@bxy4543 

root@k0:/opt/k8s# kubeadm init --config=/var/lib/sealer/data/my-cluster/rootfs/etc/kubeadm.yml --upload-certs -v 0 --ignore-preflight-errors=SystemVerification --v=5 时发现时 pull coredns:v1.8.6 下载不回来。少一层路径：

docker pull sea.hub:5000/coredns/coredns:v1.8.6 可以正常
docker pull sea.hub:5000/coredns:v1.8.6  找不到


I0407 12:39:52.369679   13821 initconfiguration.go:248] loading configuration from "/var/lib/sealer/data/my-cluster/rootfs/etc/kubeadm.yml"
W0407 12:39:52.370851   13821 strict.go:55] error unmarshaling configuration schema.GroupVersionKind{Group:"kubeadm.k8s.io", Version:"v1beta3", Kind:"ClusterConfiguration"}: error unmarshaling JSON: while decoding JSON: json: unknown field "type"
I0407 12:39:52.376288   13821 certs.go:522] validating certificate period for CA certificate
I0407 12:39:52.376340   13821 certs.go:522] validating certificate period for front-proxy CA certificate
[init] Using Kubernetes version: v1.23.5
[preflight] Running pre-flight checks
I0407 12:39:52.376479   13821 checks.go:578] validating Kubernetes and kubeadm version
I0407 12:39:52.376508   13821 checks.go:171] validating if the firewall is enabled and active
I0407 12:39:52.382405   13821 checks.go:206] validating availability of port 6443
I0407 12:39:52.382682   13821 checks.go:206] validating availability of port 10259
I0407 12:39:52.382716   13821 checks.go:206] validating availability of port 10257
I0407 12:39:52.382728   13821 checks.go:283] validating the existence of file /etc/kubernetes/manifests/kube-apiserver.yaml
I0407 12:39:52.382735   13821 checks.go:283] validating the existence of file /etc/kubernetes/manifests/kube-controller-manager.yaml
I0407 12:39:52.382739   13821 checks.go:283] validating the existence of file /etc/kubernetes/manifests/kube-scheduler.yaml
I0407 12:39:52.382743   13821 checks.go:283] validating the existence of file /etc/kubernetes/manifests/etcd.yaml
I0407 12:39:52.382762   13821 checks.go:433] validating if the connectivity type is via proxy or direct
I0407 12:39:52.382775   13821 checks.go:472] validating http connectivity to first IP address in the CIDR
I0407 12:39:52.382788   13821 checks.go:472] validating http connectivity to first IP address in the CIDR
I0407 12:39:52.382793   13821 checks.go:107] validating the container runtime
I0407 12:39:52.481829   13821 checks.go:133] validating if the "docker" service is enabled and active
I0407 12:39:52.495011   13821 checks.go:332] validating the contents of file /proc/sys/net/bridge/bridge-nf-call-iptables
I0407 12:39:52.495070   13821 checks.go:332] validating the contents of file /proc/sys/net/ipv4/ip_forward
I0407 12:39:52.495090   13821 checks.go:654] validating whether swap is enabled or not
I0407 12:39:52.495123   13821 checks.go:373] validating the presence of executable conntrack
I0407 12:39:52.495137   13821 checks.go:373] validating the presence of executable ip
I0407 12:39:52.495145   13821 checks.go:373] validating the presence of executable iptables
I0407 12:39:52.495154   13821 checks.go:373] validating the presence of executable mount
I0407 12:39:52.495162   13821 checks.go:373] validating the presence of executable nsenter
I0407 12:39:52.495170   13821 checks.go:373] validating the presence of executable ebtables
I0407 12:39:52.495252   13821 checks.go:373] validating the presence of executable ethtool
I0407 12:39:52.495323   13821 checks.go:373] validating the presence of executable socat
	[WARNING FileExisting-socat]: socat not found in system path
I0407 12:39:52.495358   13821 checks.go:373] validating the presence of executable tc
I0407 12:39:52.495371   13821 checks.go:373] validating the presence of executable touch
I0407 12:39:52.495380   13821 checks.go:521] running all checks
I0407 12:39:52.598321   13821 checks.go:404] checking whether the given node name is valid and reachable using net.LookupHost
I0407 12:39:52.598420   13821 checks.go:620] validating kubelet version
I0407 12:39:52.665442   13821 checks.go:133] validating if the "kubelet" service is enabled and active
I0407 12:39:52.673072   13821 checks.go:206] validating availability of port 10250
I0407 12:39:52.673150   13821 checks.go:206] validating availability of port 2379
I0407 12:39:52.673163   13821 checks.go:206] validating availability of port 2380
I0407 12:39:52.673175   13821 checks.go:246] validating the existence and emptiness of directory /var/lib/etcd
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
I0407 12:39:52.673231   13821 checks.go:842] using image pull policy: IfNotPresent
I0407 12:39:52.693789   13821 checks.go:851] image exists: sea.hub:5000/kube-apiserver:v1.23.5
I0407 12:39:52.715405   13821 checks.go:851] image exists: sea.hub:5000/kube-controller-manager:v1.23.5
I0407 12:39:52.736690   13821 checks.go:851] image exists: sea.hub:5000/kube-scheduler:v1.23.5
I0407 12:39:52.757191   13821 checks.go:851] image exists: sea.hub:5000/kube-proxy:v1.23.5
I0407 12:39:52.777470   13821 checks.go:851] image exists: sea.hub:5000/pause:3.6
I0407 12:39:52.797626   13821 checks.go:851] image exists: sea.hub:5000/etcd:3.5.1-0
I0407 12:39:52.829280   13821 checks.go:859] pulling: sea.hub:5000/coredns:v1.8.6
[preflight] Some fatal errors occurred:
	[ERROR ImagePull]: failed to pull image sea.hub:5000/coredns:v1.8.6: output: Error response from daemon: manifest for sea.hub:5000/coredns:v1.8.6 not found: manifest unknown: manifest unknown
, error: exit status 1
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
error execution phase preflight
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run.func1
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:235
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).visitAll
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:421
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:207
k8s.io/kubernetes/cmd/kubeadm/app/cmd.newCmdInit.func1
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/init.go:153
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:856
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:974
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:902
k8s.io/kubernetes/cmd/kubeadm/app.Run
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:50
main.main
	_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:25
runtime.main
	/usr/local/go/src/runtime/proc.go:255
runtime.goexit
	/usr/local/go/src/runtime/asm_arm64.s:1133

**Comment by bxvs888** [comment]
可能那里替换 sea.hub:5000 的截取有问题，
  正常情况：
  sea.hub:5000/kube-apiserver:v1.23.5
  sea.hub:5000/kube-controller-manager:v1.23.5
  sea.hub:5000/kube-scheduler:v1.23.5
  sea.hub:5000/kube-proxy:v1.23.5
  sea.hub:5000/pause:3.6
  sea.hub:5000/etcd:3.5.1-0
 sea.hub:5000/coredns/coredns:v1.8.6
目前错误情况：
  sea.hub:5000/kube-apiserver:v1.23.5
  sea.hub:5000/kube-controller-manager:v1.23.5
  sea.hub:5000/kube-scheduler:v1.23.5
  sea.hub:5000/kube-proxy:v1.23.5
  sea.hub:5000/pause:3.6
  sea.hub:5000/etcd:3.5.1-0
 sea.hub:5000/coredns:v1.8.6

最后一个coredns截取错误
![image](https://user-images.githubusercontent.com/298322/162126014-a918d66f-a584-4e78-8753-09926047ebc7.png)

**Comment by bxvs888** [comment]
@bxy4543  手动补一个 docker tag coredns/coredns:1.8.6 sea.hub:5000/coredns:v1.8.6 就成功了。

**Comment by bxy4543** [comment]
![image](https://user-images.githubusercontent.com/69408038/162347944-e42fd997-d141-424e-8f2c-6461fe30b743.png)
looks like there's something wrong with kubeadm.

**Comment by bxy4543** [comment]
v0.8.2 fixed
