### ISSUE TITLE
Report Null pointer error when install application 

### ISSUE THREAD

**Issue by sfeng1996** [alibaba/sealer#1315]
#### What happened:
report error when install application，the image without base

error：
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x242c53b]

goroutine 1 [running]:
github.com/alibaba/sealer/apply/processor.InstallProcessor.RunConfig(0x312d0d8, 0x42f6680, 0x30eb2c0, 0xc000831aa0, 0x0, 0x0, 0x0, 0x0, 0xc0000fe200, 0x0, ...)
	/home/runner/work/sealer/sealer/src/github.com/alibaba/sealer/apply/processor/install.go:58 +0x3b
github.com/alibaba/sealer/apply/processor.(*Executor).Execute(0xc00067db88, 0xc0000fe200, 0x30db760, 0xc000698280)
	/home/runner/work/sealer/sealer/src/github.com/alibaba/sealer/apply/processor/interface.go:45 +0x94
github.com/alibaba/sealer/apply/applydriver.(*Applier).installApp(0xc0003a0d80, 0xc000667ef0, 0x47)
	/home/runner/work/sealer/sealer/src/github.com/alibaba/sealer/apply/applydriver/local.go:281 +0xf3
github.com/alibaba/sealer/apply/applydriver.(*Applier).reconcileCluster(0xc0003a0d80, 0x0, 0x0)
	/home/runner/work/sealer/sealer/src/github.com/alibaba/sealer/apply/applydriver/local.go:155 +0x5e5
github.com/alibaba/sealer/apply/applydriver.(*Applier).Apply(0xc0003a0d80, 0x1c, 0x310e4b0)
	/home/runner/work/sealer/sealer/src/github.com/alibaba/sealer/apply/applydriver/local.go:76 +0x54
github.com/alibaba/sealer/sealer/cmd.glob..func1(0x420e840, 0xc00062f2c0, 0x0, 0x3, 0x0, 0x0)
	/home/runner/work/sealer/sealer/src/github.com/alibaba/sealer/sealer/cmd/apply.go:37 +0x77
github.com/spf13/cobra.(*Command).execute(0x420e840, 0xc00062f290, 0x3, 0x3, 0x420e840, 0xc00062f290)
	/home/runner/work/sealer/sealer/src/github.com/alibaba/sealer/vendor/github.com/spf13/cobra/command.go:852 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0x42103c0, 0x20, 0x6, 0x7)
	/home/runner/work/sealer/sealer/src/github.com/alibaba/sealer/vendor/github.com/spf13/cobra/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/work/sealer/sealer/src/github.com/alibaba/sealer/vendor/github.com/spf13/cobra/command.go:897
github.com/alibaba/sealer/sealer/cmd.Execute()
	/home/runner/work/sealer/sealer/src/github.com/alibaba/sealer/sealer/cmd/root.go:46 +0x31
main.main()
	/home/runner/work/sealer/sealer/src/github.com/alibaba/sealer/sealer/main.go:26 +0x35

```

#### Environment:

- sealer version (use `sealer version`):
```
{"gitVersion":"v0.8.2","gitCommit":"30ce682","buildDate":"2022-04-12 11:28:17","goVersion":"go1.16.15","compiler":"gc","platform":"linux/amd64"}
```

**Comment by sfeng1996** [comment]
> #### What happened:
> report error when install application，the image without base
> 
> error：
> 
> ```
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x242c53b]
> 
> goroutine 1 [running]:
> github.com/alibaba/sealer/apply/processor.InstallProcessor.RunConfig(0x312d0d8, 0x42f6680, 0x30eb2c0, 0xc000831aa0, 0x0, 0x0, 0x0, 0x0, 0xc0000fe200, 0x0, ...)
> 	/home/runner/work/sealer/sealer/src/github.com/alibaba/sealer/apply/processor/install.go:58 +0x3b
> github.com/alibaba/sealer/apply/processor.(*Executor).Execute(0xc00067db88, 0xc0000fe200, 0x30db760, 0xc000698280)
> 	/home/runner/work/sealer/sealer/src/github.com/alibaba/sealer/apply/processor/interface.go:45 +0x94
> github.com/alibaba/sealer/apply/applydriver.(*Applier).installApp(0xc0003a0d80, 0xc000667ef0, 0x47)
> 	/home/runner/work/sealer/sealer/src/github.com/alibaba/sealer/apply/applydriver/local.go:281 +0xf3
> github.com/alibaba/sealer/apply/applydriver.(*Applier).reconcileCluster(0xc0003a0d80, 0x0, 0x0)
> 	/home/runner/work/sealer/sealer/src/github.com/alibaba/sealer/apply/applydriver/local.go:155 +0x5e5
> github.com/alibaba/sealer/apply/applydriver.(*Applier).Apply(0xc0003a0d80, 0x1c, 0x310e4b0)
> 	/home/runner/work/sealer/sealer/src/github.com/alibaba/sealer/apply/applydriver/local.go:76 +0x54
> github.com/alibaba/sealer/sealer/cmd.glob..func1(0x420e840, 0xc00062f2c0, 0x0, 0x3, 0x0, 0x0)
> 	/home/runner/work/sealer/sealer/src/github.com/alibaba/sealer/sealer/cmd/apply.go:37 +0x77
> github.com/spf13/cobra.(*Command).execute(0x420e840, 0xc00062f290, 0x3, 0x3, 0x420e840, 0xc00062f290)
> 	/home/runner/work/sealer/sealer/src/github.com/alibaba/sealer/vendor/github.com/spf13/cobra/command.go:852 +0x472
> github.com/spf13/cobra.(*Command).ExecuteC(0x42103c0, 0x20, 0x6, 0x7)
> 	/home/runner/work/sealer/sealer/src/github.com/alibaba/sealer/vendor/github.com/spf13/cobra/command.go:960 +0x375
> github.com/spf13/cobra.(*Command).Execute(...)
> 	/home/runner/work/sealer/sealer/src/github.com/alibaba/sealer/vendor/github.com/spf13/cobra/command.go:897
> github.com/alibaba/sealer/sealer/cmd.Execute()
> 	/home/runner/work/sealer/sealer/src/github.com/alibaba/sealer/sealer/cmd/root.go:46 +0x31
> main.main()
> 	/home/runner/work/sealer/sealer/src/github.com/alibaba/sealer/sealer/main.go:26 +0x35
> ```
> 
> #### Environment:
> * sealer version (use `sealer version`):
> 
> ```
> {"gitVersion":"v0.8.2","gitCommit":"30ce682","buildDate":"2022-04-12 11:28:17","goVersion":"go1.16.15","compiler":"gc","platform":"linux/amd64"}
> ```

@kakaZhou719 Can you release a new version as soon as possible? I need it urgently，thanks

**Comment by kakaZhou719** [comment]
@sfeng1996 ，yes, sure, main branch already fixed this issue. but have process to release the new version. i will reply you later.

**Comment by bxy4543** [comment]
@sfeng1996 v0.8.3 fixed
