### ISSUE TITLE
support to show remote registry image list

### ISSUE THREAD

**Issue by kakaZhou719** [alibaba/sealer#1319]
## Issue Description

`sealer login registry.cn-qingdao.aliyuncs.com -u *** -p ***`

`sealer images --remote` 

Or:  `sealer search dashboard:v1`

Type: *feature request*

**Comment by yuzhichang** [comment]
@kakaZhou719 Why this is closed withou PR? The registry currently is a black-box, not accessable via browser, not list-able or searchable via `sealer` CLI.

**Comment by kakaZhou719** [comment]
@yuzhichang , you could use `sealer search` command to browse the images.
