### ISSUE TITLE
error creating overlay mount to /var/lib/sealer/tmp/.DTmp-030492001: too many levels of symbolic links

### ISSUE THREAD

**Issue by qq510521** [alibaba/sealer#1330]
I made an error in sealer build

command：
sealer build -m lite -t kubernetes:v1.19.8 .

ERROR：
failed to mount target /var/lib/sealer/tmp/.DTmp-030492001:error creating overlay mount to /var/lib/sealer/tmp/.DTmp-030492001: too many levels of symbolic links

#### Environment:

- sealer version (use `sealer version`):v0.8.3
- Cloud provider or hardware configuration:
- OS :CentOS Linux release 7.2.1511 (Core)
- Kernel (e.g. `uname -a`):5.4.8-1.el7.elrepo.x86_64

**Comment by kakaZhou719** [comment]
@qq510521 ,seems the build context has some error.  FYI: https://www.baeldung.com/linux/too-many-levels-of-symlinks

**Comment by qq510521** [comment]
> @qq510521，似乎构建上下文有一些错误。仅供参考：[https ://www.baeldung.com/linux/too-many-levels-of-symlinks](https://www.baeldung.com/linux/too-many-levels-of-symlinks)

thanks，Because the ‘’Kubefile‘’ has a duplicate
