### ISSUE TITLE
sealer run local vm cluster failed :  Conflict container name

### ISSUE THREAD

**Issue by katepangLiu** [alibaba/sealer#141]
#### What happened:
```
sealer run kubernetes:v1.19.9 --masters 192.168.71.136 --nodes 192.168.71.137,192.168.71.139 --passwd ***

logs:

...
Loaded image: registry:2.7.1
+ docker run -d --restart=always --name sealer-registry -p 5000:5000 -v /var/lib/sealer/data/my-cluster/registry:/var/lib/registry registry:2.7.1
docker: Error response from daemon: Conflict. The container name "/sealer-registry" is already in use by container "f07b3e271f95683e554c1c1b88a41375ae26c85193e348100b3a6af200b741c9". You have to remove (or rename) that container to be able to reuse that name.
...

2021-05-21 10:11:14 [EROR] init master0 failed, error: [ssh][192.168.71.136]run command failed [kubeadm init --config=/var/lib/sealer/data/my-cluster/kubeadm-config.yaml --upload-certs -v 0 --ignore-preflight-errors=SystemVerification], Process exited with status 1. Please clean and reinstall

```

#### What you expected to happen:
setup a k8s cluster
#### Environment:
- sealer version:   {"gitVersion":"v0.1.4","gitCommit":"9090fa8","buildDate":"2021-05-19 08:00:19","goVersion":"go1.14.15","compiler":"gc","platform":"linux/amd64"} 
- Cloud provider or hardware configuration:  win10 + vmware
- OS : CentOS Linux 7
- Kernel :   3.10.0-1160.el7.x86_64
- Install tools:
- Others:

**Comment by katepangLiu** [comment]
Actually, there is no container named  "/sealer-registry"

```
[root@mickey sealer]# docker image list
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
registry            2.7.1               1fd8e1b0bb7e        5 weeks ago         26.2MB
[root@mickey sealer]# 
[root@mickey sealer]# 
[root@mickey sealer]# docker container list
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
[root@mickey sealer]# 
[root@mickey sealer]# 
```

**Comment by justadogistaken** [comment]
how about "docker container list -a"

**Comment by fanux** [comment]
Using docker ps -a

**Comment by katepangLiu** [comment]
OK, I rm the container and retry, then succeed.
Maybe I left out the real problem, I  excute `sealer run ...` three times on a pure system.
1. Failed,  but I forgot to record the error log
2. Failed,  caused by The Container "sealer-registry"
3. Success, rm sealer-registry

**Comment by katepangLiu** [comment]
But now  all calico-node pods is CrashLoopBackOff, because the eth0 doesn't exist.
Why sealer need a inteaface  named eth0 ,  I remember that sealos didn't need it.
```
[root@mickey sealer]# kubectl get pods -A
NAMESPACE     NAME                                       READY   STATUS            
kube-system   calico-kube-controllers-5565b777b6-8b4xt   0/1     ContainerCreating 
kube-system   calico-node-95v25                          0/1     CrashLoopBackOff  
kube-system   calico-node-db9h8                          0/1     CrashLoopBackOff  
kube-system   calico-node-f9gpz                          0/1     CrashLoopBackOff  
kube-system   coredns-597c5579bc-8n2gh                   0/1     ContainerCreating 
kube-system   coredns-597c5579bc-qppr5                   0/1     ContainerCreating 
kube-system   etcd-mickey.katepang                       1/1     Running           
kube-system   kube-apiserver-mickey.katepang             1/1     Running           
kube-system   kube-controller-manager-mickey.katepang    1/1     Running           
kube-system   kube-lvscare-miffy.katepang                1/1     Running           
kube-system   kube-lvscare-stuart.katepang               1/1     Running           
kube-system   kube-proxy-57g8w                           1/1     Running           
kube-system   kube-proxy-ljv89                           1/1     Running           
kube-system   kube-proxy-nzxnh                           1/1     Running           
kube-system   kube-scheduler-mickey.katepang             1/1     Running           
[root@mickey sealer]# 
[root@mickey sealer]# 
[root@mickey sealer]# 
[root@mickey sealer]# kubectl logs calico-node-95v25 -n kube-system
2021-05-21 02:45:31.841 [INFO][9] startup.go 256: Early log level set to info
2021-05-21 02:45:31.841 [INFO][9] startup.go 272: Using NODENAME environment for no
2021-05-21 02:45:31.841 [INFO][9] startup.go 284: Determined node name: mickey.kate
2021-05-21 02:45:31.842 [INFO][9] k8s.go 228: Using Calico IPAM
2021-05-21 02:45:31.842 [INFO][9] startup.go 316: Checking datastore connection
2021-05-21 02:45:31.848 [INFO][9] startup.go 340: Datastore connection verified
2021-05-21 02:45:31.848 [INFO][9] startup.go 95: Datastore is ready
2021-05-21 02:45:31.851 [INFO][9] customresource.go 100: Error getting resource Keyorg calicoversion)
2021-05-21 02:45:31.855 [INFO][9] startup.go 382: Initialize BGP data
2021-05-21 02:45:31.857 [WARNING][9] startup.go 594: Unable to auto-detect an IPv4 
2021-05-21 02:45:31.857 [WARNING][9] startup.go 404: Couldn't autodetect an IPv4 ad
2021-05-21 02:45:31.857 [INFO][9] startup.go 210: Clearing out-of-date IPv4 address
2021-05-21 02:45:31.863 [WARNING][9] startup.go 1057: Terminating
Calico node failed to start

[root@mickey sealer]# ifconfig
docker0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 172.17.255.255
        inet6 fe80::42:dfff:fe5d:66a7  prefixlen 64  scopeid 0x20<link>
        ether 02:42:df:5d:66:a7  txqueuelen 0  (Ethernet)
        RX packets 22355  bytes 683423457 (651.7 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 12772  bytes 925369 (903.6 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

ens33: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.71.136  netmask 255.255.255.0  broadcast 192.168.71.255
        inet6 fe80::a265:6ec1:9f58:95b4  prefixlen 64  scopeid 0x20<link>
        ether 00:0c:29:7c:75:b4  txqueuelen 1000  (Ethernet)
        RX packets 1205377  bytes 665295642 (634.4 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 5083588  bytes 10502638502 (9.7 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 1090114  bytes 3115411513 (2.9 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1090114  bytes 3115411513 (2.9 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

vethac34c71: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::100d:aeff:fe66:491a  prefixlen 64  scopeid 0x20<link>
        ether 12:0d:ae:66:49:1a  txqueuelen 0  (Ethernet)
        RX packets 22355  bytes 683736427 (652.0 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 12780  bytes 926025 (904.3 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

```

**Comment by fanux** [comment]
you need specify the network interface name in Clusterfile, then sealer apply -f Clusterfile, sealer run don't support this argument now.

**Comment by fanux** [comment]
```
apiVersion: sealer.aliyun.com/v1alpha1
kind: Cluster
metadata:
  name: my-cluster
spec:
  image: registry.cn-qingdao.aliyuncs.com/sealer-io/kubernetes:v1.19.9
  provider: BAREMETAL
  ssh:
    passwd:
    pk: xxx
    pkPasswd: xxx
    user: root
  network:
    interface: ens33
    cniName: calico
    podCIDR: 100.64.0.0/10
    svcCIDR: 10.96.0.0/22
    withoutCNI: false
  certSANS:
    - aliyun-inc.com
    - 10.0.0.2
    
  masters:
    ipList:
     - 172.20.125.234
     - 172.20.126.5
     - 172.20.126.6
  nodes:
    ipList:
     - 172.20.126.8
     - 172.20.126.9
     - 172.20.126.10
```
like this

**Comment by fanux** [comment]
https://github.com/alibaba/sealer/issues/143

**Comment by cuisongliu** [comment]
#136  this feature can apply cni not change nodes

**Comment by katepangLiu** [comment]
> But now all calico-node pods is CrashLoopBackOff, because the eth0 doesn't exist.
> Why sealer need a inteaface named eth0 , I remember that sealos didn't need it.
> 
> ```
> [root@mickey sealer]# kubectl get pods -A
> NAMESPACE     NAME                                       READY   STATUS            
> kube-system   calico-kube-controllers-5565b777b6-8b4xt   0/1     ContainerCreating 
> kube-system   calico-node-95v25                          0/1     CrashLoopBackOff  
> kube-system   calico-node-db9h8                          0/1     CrashLoopBackOff  
> kube-system   calico-node-f9gpz                          0/1     CrashLoopBackOff  
> kube-system   coredns-597c5579bc-8n2gh                   0/1     ContainerCreating 
> kube-system   coredns-597c5579bc-qppr5                   0/1     ContainerCreating 
> kube-system   etcd-mickey.katepang                       1/1     Running           
> kube-system   kube-apiserver-mickey.katepang             1/1     Running           
> kube-system   kube-controller-manager-mickey.katepang    1/1     Running           
> kube-system   kube-lvscare-miffy.katepang                1/1     Running           
> kube-system   kube-lvscare-stuart.katepang               1/1     Running           
> kube-system   kube-proxy-57g8w                           1/1     Running           
> kube-system   kube-proxy-ljv89                           1/1     Running           
> kube-system   kube-proxy-nzxnh                           1/1     Running           
> kube-system   kube-scheduler-mickey.katepang             1/1     Running           
> [root@mickey sealer]# 
> [root@mickey sealer]# 
> [root@mickey sealer]# 
> [root@mickey sealer]# kubectl logs calico-node-95v25 -n kube-system
> 2021-05-21 02:45:31.841 [INFO][9] startup.go 256: Early log level set to info
> 2021-05-21 02:45:31.841 [INFO][9] startup.go 272: Using NODENAME environment for no
> 2021-05-21 02:45:31.841 [INFO][9] startup.go 284: Determined node name: mickey.kate
> 2021-05-21 02:45:31.842 [INFO][9] k8s.go 228: Using Calico IPAM
> 2021-05-21 02:45:31.842 [INFO][9] startup.go 316: Checking datastore connection
> 2021-05-21 02:45:31.848 [INFO][9] startup.go 340: Datastore connection verified
> 2021-05-21 02:45:31.848 [INFO][9] startup.go 95: Datastore is ready
> 2021-05-21 02:45:31.851 [INFO][9] customresource.go 100: Error getting resource Keyorg calicoversion)
> 2021-05-21 02:45:31.855 [INFO][9] startup.go 382: Initialize BGP data
> 2021-05-21 02:45:31.857 [WARNING][9] startup.go 594: Unable to auto-detect an IPv4 
> 2021-05-21 02:45:31.857 [WARNING][9] startup.go 404: Couldn't autodetect an IPv4 ad
> 2021-05-21 02:45:31.857 [INFO][9] startup.go 210: Clearing out-of-date IPv4 address
> 2021-05-21 02:45:31.863 [WARNING][9] startup.go 1057: Terminating
> Calico node failed to start
> 
> [root@mickey sealer]# ifconfig
> docker0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
>         inet 172.17.0.1  netmask 255.255.0.0  broadcast 172.17.255.255
>         inet6 fe80::42:dfff:fe5d:66a7  prefixlen 64  scopeid 0x20<link>
>         ether 02:42:df:5d:66:a7  txqueuelen 0  (Ethernet)
>         RX packets 22355  bytes 683423457 (651.7 MiB)
>         RX errors 0  dropped 0  overruns 0  frame 0
>         TX packets 12772  bytes 925369 (903.6 KiB)
>         TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
> 
> ens33: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
>         inet 192.168.71.136  netmask 255.255.255.0  broadcast 192.168.71.255
>         inet6 fe80::a265:6ec1:9f58:95b4  prefixlen 64  scopeid 0x20<link>
>         ether 00:0c:29:7c:75:b4  txqueuelen 1000  (Ethernet)
>         RX packets 1205377  bytes 665295642 (634.4 MiB)
>         RX errors 0  dropped 0  overruns 0  frame 0
>         TX packets 5083588  bytes 10502638502 (9.7 GiB)
>         TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
> 
> lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
>         inet 127.0.0.1  netmask 255.0.0.0
>         inet6 ::1  prefixlen 128  scopeid 0x10<host>
>         loop  txqueuelen 1000  (Local Loopback)
>         RX packets 1090114  bytes 3115411513 (2.9 GiB)
>         RX errors 0  dropped 0  overruns 0  frame 0
>         TX packets 1090114  bytes 3115411513 (2.9 GiB)
>         TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
> 
> vethac34c71: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
>         inet6 fe80::100d:aeff:fe66:491a  prefixlen 64  scopeid 0x20<link>
>         ether 12:0d:ae:66:49:1a  txqueuelen 0  (Ethernet)
>         RX packets 22355  bytes 683736427 (652.0 MiB)
>         RX errors 0  dropped 0  overruns 0  frame 0
>         TX packets 12780  bytes 926025 (904.3 KiB)
>         TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
> ```

I reset all the vms, and retry,  when I first time excute `sealer run`, it happened again:
**docker: Error response from daemon: driver failed programming external connectivity on endpoint sealer-registry**

```
# FirstTime: Failed
sealer apply -f katepangCluster.yaml  

++ dirname init-registry.sh
+ cd .
+ REGISTRY_PORT=5000
+ VOLUME=/var/lib/sealer/data/katepang/registry
+ container=sealer-registry
+ mkdir -p /var/lib/sealer/data/katepang/registry
+ docker load -q -i ../images/registry.tar
Loaded image: registry:2.7.1
+ docker run -d --restart=always --name sealer-registry -p 5000:5000 -v /var/lib/sealer/data/katepang/registry:/var/lib/registry registry:2.7.1
13d18fdd4698fed8135268947df5a00add2c6c43cd4798cea9a5b9e4cc6c0f61
docker: Error response from daemon: driver failed programming external connectivity on endpoint sealer-registry (bedda87f1e505ea6b10aafe235744003a031bbdddb5d6bd57dfcb678090a77b0):  (iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 5000 -j DNAT --to-destination 172.17.0.2:5000 ! -i docker0: iptables: No chain/target/match by that name.
(exit status 1)).
+ true

# rm the container registry
docker ps -a
docker rm ...

# SecondTime: Succeed
sealer apply -f katepangCluster.yaml
```

**Comment by katepangLiu** [comment]
> OK, I rm the container and retry, then succeed.
> Maybe I left out the real problem, I excute `sealer run ...` three times on a pure system.
> 
> 1. Failed,  but I forgot to record the error log
> 2. Failed,  caused by The Container "sealer-registry"
> 3. Success, rm sealer-registry

I reset all the vms, and retry,  when I first time excute `sealer run`, it happened again:
**docker: Error response from daemon: driver failed programming external connectivity on endpoint sealer-registry**

```
# FirstTime: Failed
sealer apply -f katepangCluster.yaml  

++ dirname init-registry.sh
+ cd .
+ REGISTRY_PORT=5000
+ VOLUME=/var/lib/sealer/data/katepang/registry
+ container=sealer-registry
+ mkdir -p /var/lib/sealer/data/katepang/registry
+ docker load -q -i ../images/registry.tar
Loaded image: registry:2.7.1
+ docker run -d --restart=always --name sealer-registry -p 5000:5000 -v /var/lib/sealer/data/katepang/registry:/var/lib/registry registry:2.7.1
13d18fdd4698fed8135268947df5a00add2c6c43cd4798cea9a5b9e4cc6c0f61
docker: Error response from daemon: driver failed programming external connectivity on endpoint sealer-registry (bedda87f1e505ea6b10aafe235744003a031bbdddb5d6bd57dfcb678090a77b0):  (iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 5000 -j DNAT --to-destination 172.17.0.2:5000 ! -i docker0: iptables: No chain/target/match by that name.
(exit status 1)).
+ true

# rm the container registry
docker ps -a
docker rm ...

# SecondTime: Succeed
sealer apply -f katepangCluster.yaml
```

**Comment by fanux** [comment]
try  `sysctl -w net.ipv4.ip_forward=1`

**Comment by fanux** [comment]
https://github.com/alibaba/sealer/issues/145

**Comment by fanux** [comment]
@katepangLiu could you add my dingtalk or wechat: fangnux

**Comment by cuisongliu** [comment]
see  #67

**Comment by cuisongliu** [comment]
use `registry-vpc.cn-beijing.aliyuncs.com/sealer-io/cloudrootfs:v1.19.9-alpha.1` fix it.
