### ISSUE TITLE
sealer run support --interface

### ISSUE THREAD

**Issue by fanux** [alibaba/sealer#143]
Support the network interface name.

**Comment by katepangLiu** [comment]
How about we name it RunArgs.netInterface

**Comment by jmpcyc** [comment]
Hi @fanux , I can fix this job.

**Comment by fanux** [comment]
@katepangLiu I think net-interface is too long, we can using -h command to show out what --interface means.

**Comment by cuisongliu** [comment]
#136  care this feature

**Comment by fanux** [comment]
https://github.com/alibaba/sealer/blob/main/sealer/cmd/run.go#L52  just set cluster.Spec.Network.Interface @jmpcyc
