### ISSUE TITLE
sealer push image override

### ISSUE THREAD

**Issue by cuisongliu** [alibaba/sealer#151]
#### What happened:
<img width="1498" alt="image" src="https://user-images.githubusercontent.com/4150905/119282458-50061d80-bc6c-11eb-8000-1846097d1f9b.png">

#### Environment:
- sealer version (use `sealer version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by justadogistaken** [comment]
It seems that you may changed you layer data, which result in hash changed

**Comment by cuisongliu** [comment]
but I don't change layer ,I tag a image only.

**Comment by justadogistaken** [comment]
Which image you tagged on? Could you post the image metadata?

**Comment by cuisongliu** [comment]
```
kind: Image
metadata:
  annotations:
    sea.aliyun.com/ClusterFile: "apiVersion: zlink.aliyun.com/v1alpha1\nkind: Cluster\nmetadata:\n
      \ name: my-cluster\nspec:\n  image: seadent/cloudrootfs:v1.19.9-alpha.6\n  provider:
      ALI_CLOUD\n  ssh:\n    passwd: Seadent123\n    pk: xxx\n    pkPasswd: xxx\n
      \   user: root\n  network:\n    interface: eth.*|en.*\n    cniName: calico\n
      \   podCIDR: 100.64.0.0/10\n    svcCIDR: 10.96.0.0/22\n    withoutCNI: false\n
      \ certSANS:\n    - aliyun-inc.com\n    - 10.0.0.2\n    \n  masters:\n    cpu:
      4\n    memory: 4\n    count: 3\n    systemDisk: 100\n    dataDisks:\n    - 100\n
      \ nodes:\n    cpu: 4\n    memory: 4\n    count: 3\n    systemDisk: 100\n    dataDisks:\n
      \   - 100\n\n"
  creationTimestamp: null
  name: registry-vpc.cn-hongkong.aliyuncs.com/sealyun/kubernetes-amd64:v1.19.9
spec:
  hash: ""
  id: 8233ad647e35d6ec32d98efe45467cb5
  layers:
  - hash: sha256:181d80302bd2e6e28caf80286d70bdb225472d1ba822e75b8a3d9e28259bd6ed
    type: COPY
    value: . .
  mergedLayer: ""
status: {}
```

registry.cn-hongkong.aliyuncs.com/sealyun/kubernetes-amd64:v1.19.9

**Comment by justadogistaken** [comment]
It's weird, I pulled registry.cn-hongkong.aliyuncs.com/sealyun/kubernetes-amd64:v1.19.9, and tag it, then pushed it successfully. Is there any operation might change your layer?

**Comment by cuisongliu** [comment]
I use code is newest, you code is newest ?

**Comment by cuisongliu** [comment]
```
2021-05-25 15:38:34 [EROR] failed to push image registry.cn-qingdao.aliyuncs.com/sealer-io/cloudrootfs:v1.19.9-alpha.3: failed to push layer, err: layer digest changed, original: d43c62d86097bd10714f1eec82c249daf1f0e705a9f503d0418695cc65ad1385, current: 3f2f626ae69e5d1e2283ffd4a345c117e5b231c7e3892ac8bfda0c6d090fb7b5
```

I am  build in centos and push in ubuntu  , the digest not same in diffent system?

**Comment by justadogistaken** [comment]
jeez, maybe the ways of  file traverse are different among different os. Let me check it out.
