### ISSUE TITLE
need a specific interface to work with clusterfile 

### ISSUE THREAD

**Issue by kakaZhou719** [alibaba/sealer#154]
## Issue Description
as we konw ,sealer apply  and build steps all need to read or write cluster config from clusterfile .
but some times ,the clusterfile config is in raw status (read only).

meanwhile the location of clusterfile is mixed：
1. user context
2.  /tmp/Clusterfile
3. /root/.sealer/{}/Clusterfile
4. /var/lib/sealer/Clusterfile

content of clusterfile is mixed：

1. includ infra config
2. includ K8S config

Type: *feature request*

### Describe what feature you want
we need a specific interface to work with clusterfile and refactor our sealer code.

**Comment by fanux** [comment]
my suggestion:
1. deprecated the /tmp/Clusterfile
2. Using /var/lib/sealer/[my cluster]/Clusterfile as unique clusterfile (OR save it in etcd?)
3. Using edit command to update the cluster( Like kubectl edit pod ...)
```
# sealer get cluster
my-cluster1
my-cluster2

# sealer edit cluster my-cluster
```

**Comment by cuisongliu** [comment]
.sealer/[my cluster]/ dir and /var/lib/sealer/data/[my cluster] the means is same ? can we merge it.
