### ISSUE TITLE
rmi by image id

### ISSUE THREAD

**Issue by justadogistaken** [alibaba/sealer#157]
## Issue Description

Type: *feature request*
currently, we support delete image by name only, which provides ability of untagging when there are many images with same id. Thus we can't delete image just one step in some situations. I think provide a new feature for deleting image by image id is reasonable. 
### Describe what feature you want
```
[root@jiangnan001 ~]# sealer images
+----------------------------------+----------------------------------------------------------------------+
|             IMAGE ID             |                              IMAGE NAME                              |
+----------------------------------+----------------------------------------------------------------------+
| 8233ad647e35d6ec32d98efe45467cb5 | registry.cn-hongkong.aliyuncs.com/sealyun/kubernetes-amd64-1:v1.19.9 |
| 8233ad647e35d6ec32d98efe45467cb5 | registry.cn-hongkong.aliyuncs.com/sealyun/kubernetes-amd64:v1.19.9   |
```
sealer rmi 8233ad647e35d6ec32d98efe45467cb5 (failed, there are more than one image)
sealer rmi 8233ad647e35d6ec32d98efe45467cb5 -f (success)

**Comment by cuisongliu** [comment]
I think the print image shloud be more info, ex size ,create time and Metadata.

**Comment by fanux** [comment]
+1
