### ISSUE TITLE
non root user can not run sealer apply 

### ISSUE THREAD

**Issue by kakaZhou719** [alibaba/sealer#161]
#### What happened:
![image](https://user-images.githubusercontent.com/83740799/119343126-9be6b000-bcc8-11eb-9d87-33dd3f1bc403.png)

#### What you expected to happen:
any user can exec sealer  
#### Environment:
- sealer version (use `sealer version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by cuisongliu** [comment]
#160  fix it
