### ISSUE TITLE
failed to run sealer  login using non-root user

### ISSUE THREAD

**Issue by kakaZhou719** [alibaba/sealer#165]
#### What happened:
non root user can not login 

![image](https://user-images.githubusercontent.com/83740799/119431186-b65e6f00-bd44-11eb-9ca6-dc8370bc17d9.png)

#### Environment:
- sealer version (use `sealer version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by fanux** [comment]
`ll .` show the .docker dir permission.
