### ISSUE TITLE
init.sh exec queue

### ISSUE THREAD

**Issue by cuisongliu** [alibaba/sealer#176]
#### What happened:

https://github.com/alibaba/sealer/blob/4066e3fc20e99b875e749b47bc6a1031d89cd8ef/filesystem/filesystem.go#L136

why not join exec this script?? this way if a node change to master is error. old node shoud be delete node and do other.

#### Environment:
- sealer version (use `sealer version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by fanux** [comment]
So what do you mean? 😭
