### ISSUE TITLE
Can I customize the kubernetes version?

### ISSUE THREAD

**Issue by lllwan** [alibaba/sealer#177]
Good project！ I want to know how sealer manages dependencies and whether it can support the installation of custom kubernetes version clusters. Finally, will the iteration cost of tracking kubernetes community version be relatively high?

**Comment by lllwan** [comment]
I don't think sealer should lock the version. Instead, it should make a dependency list to support customized dependencies and package.

**Comment by fanux** [comment]
1. We will support kuberntes mainstream version
2. You can use the COPY command overwrite the cloudrootfs files, which is the recommended way.  https://github.com/alibaba/sealer/blob/main/docs/api/cloudrootfs.md
3. You can add my dingtalk or wechat : fangnux
