### ISSUE TITLE
Sealer run specified network interface name is invalid

### ISSUE THREAD

**Issue by charnet1019** [alibaba/sealer#180]
#### Environment:
- sealer version (use `sealer version`):  lastest code 
- Cloud provider or hardware configuration:  local vm
- OS (e.g: `cat /etc/os-release`): CentOS Linux release 7.9.2009
- Kernel (e.g. `uname -a`): 3.10.0-1160.25.1.el7.x86_64

exec command:
```
sealer run kubernetes:v1.19.9 --masters 192.168.2.5 -u root --passwd secret -i ens33 -d
```

calico start failed
![image](https://user-images.githubusercontent.com/18616254/119599019-b9c22b00-be16-11eb-886f-a166b405d4a9.png)

**Comment by cuisongliu** [comment]
cni interface is eth0 ??? try ip addr see you network interface

**Comment by charnet1019** [comment]
> cni interface is eth0 ??? try ip addr see you network interface

![image](https://user-images.githubusercontent.com/18616254/119605080-c2206300-be22-11eb-965d-c20a2d21ae22.png)

**Comment by cuisongliu** [comment]
-I ens33 this feature not finish ???

**Comment by fanux** [comment]
v0.1.4 seems not support --interface. The latest code in main branch has this feature.

**Comment by charnet1019** [comment]
> v0.1.4 seems not support --interface. The latest code in main branch has this feature.

Sorry, is lastest code.

**Comment by jmpcyc** [comment]
@fanux what about finding target link device according to master/node ip, then  user do not need  to use --interface in most cases.   #143

**Comment by fanux** [comment]
> @fanux what about finding target link device according to master/node ip, then user do not need to use --interface in most cases. #143

I think that is an awesome idea.

**Comment by fanux** [comment]
https://github.com/alibaba/sealer/issues/182

**Comment by charnet1019** [comment]
Fixed
