### ISSUE TITLE
I don't have account of aliyun.

### ISSUE THREAD

**Issue by fleeto** [alibaba/sealer#181]
#### What happened:

sealer build -t bingo/sealer-sample:v0.1
2021-05-26 11:38:46 [INFO] init image spec success! image id is 57b279e792eb5bb0d52ed482a32cb40b
2021-05-26 11:38:46 [WARN] failed to decode auth info, username and password would be empty, err: auth for registry.cn-qingdao.aliyuncs.com doesn't exist
2021-05-26 11:38:48 [INFO] read cluster file /var/lib/sealer/Clusterfile success !
2021-05-26 11:38:48 [EROR] please set accessKey and accessKeySecret ENV, example: export ACCESSKEYID=xxx export ACCESSKEYSECRET=xxx , how to get AK SK: https://ram.console.aliyun.com/manage/ak
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1afeccf]

goroutine 1 [running]:
github.com/alibaba/sealer/build.(*CloudBuilder).ApplyInfra(0xc000518270, 0x0, 0x0)
        /data/lab/sealer/sealer-0.1.4/build/cloud_builder.go:125 +0xaf
github.com/alibaba/sealer/build.(*CloudBuilder).Build(0xc000518270, 0x7ffdb55738c6, 0x18, 0x2131225, 0x1, 0x21367da, 0x8, 0xc00059fd40, 0xc00059fd18)
        /data/lab/sealer/sealer-0.1.4/build/cloud_builder.go:38 +0xeb
github.com/alibaba/sealer/sealer/cmd.glob..func2(0x3819360, 0xc000680020, 0x0, 0x2)
        /data/lab/sealer/sealer-0.1.4/sealer/cmd/build.go:48 +0xef
github.com/spf13/cobra.(*Command).execute(0x3819360, 0xc000680000, 0x2, 0x2, 0x3819360, 0xc000680000)
        /data/lab/sealer/sealer-0.1.4/vendor/github.com/spf13/cobra/command.go:854 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x381a860, 0x4473aa, 0x379a880, 0xc000000180)
        /data/lab/sealer/sealer-0.1.4/vendor/github.com/spf13/cobra/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /data/lab/sealer/sealer-0.1.4/vendor/github.com/spf13/cobra/command.go:895
github.com/alibaba/sealer/sealer/cmd.Execute()
        /data/lab/sealer/sealer-0.1.4/sealer/cmd/root.go:47 +0x31
main.main()
        /data/lab/sealer/sealer-0.1.4/sealer/main.go:21 +0x25

#### Environment:
- sealer version (use `sealer version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by fanux** [comment]
Show me your Kubefile, if has RUN or CMD command in Kubefile, sealer must run a temp cluster to exec those commands and cache container images. We   only support alicloud now.
