### ISSUE TITLE
failed to run sealer apply 

### ISSUE THREAD

**Issue by kakaZhou719** [alibaba/sealer#187]
#### What happened:
an error was encountered when i run sealer apply, it seems like excute kubeadm init failed . more details as below:

![image](https://user-images.githubusercontent.com/83740799/119635499-564ff180-be46-11eb-8152-37af47517f3b.png)
![image](https://user-images.githubusercontent.com/83740799/119635518-5a7c0f00-be46-11eb-88c3-7175bd7f04ff.png)

#### Environment:
- sealer version (use `sealer version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by cuisongliu** [comment]
#138   fix it .  
![image](https://user-images.githubusercontent.com/4150905/119652277-72f52500-be58-11eb-8417-0d9d5f742353.png)

**Comment by DesistDaydream** [comment]
I have a similar problem, different places are shown in the following figure.

![image](https://user-images.githubusercontent.com/39847025/119675359-8a8bd800-be6f-11eb-9566-28cc3d84cf0b.png)

The problem of using CLI flag or Clusterfile is the same

os:ubuntu 20.04
sealer:0.1.4

**Comment by fanux** [comment]
This is CLOUD mode or BAREMETAL?

**Comment by kakaZhou719** [comment]
CLOUD mode

**Comment by fanux** [comment]
How can I reproduce it?
