### ISSUE TITLE
x509 cert issues after apply

### ISSUE THREAD

**Issue by kakaZhou719** [alibaba/sealer#189]
#### What happened:

use non-root user to exec sealer apply , and run command: kubectl get nodes , i met X509 issue.

`Unable to connect to the server: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kubernetes")`

#### What you expected to happen:

do we need to exec chown for kubeconfig as kubeadm init suggest ？

![image](https://user-images.githubusercontent.com/83740799/119637244-0a05b100-be48-11eb-84b7-f48248faad82.png)

#### Environment:
- sealer version (use `sealer version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by cuisongliu** [comment]
root login ?

**Comment by kakaZhou719** [comment]
> root login ?

nop
