### ISSUE TITLE
add log flags to cobra command flagsets

### ISSUE THREAD

**Issue by touchuyht** [alibaba/sealer#193]
## Issue Description
In the sealer's logger directory, I found some log adapters which are fileLogger, consoleLogger and connLogger. The sealer just uses the console logger and it cannot be defined by setting sealer command line flags. So I suggest add flags which allows users to specify their adapters and add flags which can affect the log behavior. For example, the fileLogger has the Filename option and currently it cannot be set by command line flags. By adding the flag to the cobra command, users can define which file to save the sealer's log to.
Type: *feature request*

**Comment by bxy4543** [comment]
Logs are saved in /var/lib/sealer/log by default, and log configurations can be defined in the /root.sealer.json file.
