### ISSUE TITLE
when we need to apply cni

### ISSUE THREAD

**Issue by fanux** [alibaba/sealer#197]
Compare the current CNI config and desired config, if not same apply it.

**Comment by justadogistaken** [comment]
I guess it's vital to make the scene clear. define the "not same", .yaml not identical between two files, or cni name/version are different of something else. And where are current cni config and desired config from. I'm can't understand as an outsider.

**Comment by cuisongliu** [comment]
https://github.com/alibaba/sealer/pull/136  this pr is apply cni feature。

**Comment by cuisongliu** [comment]
need diff cni config ?

**Comment by fanux** [comment]
I think we need, but how can  we get the current CNI config.
