### ISSUE TITLE
How to customize the kubernetes mirror ？Provide customize kuberentes mirror docs

### ISSUE THREAD

**Issue by bryant-rh** [alibaba/sealer#205]
#### Environment:
- sealer version (use `sealer version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by fanux** [comment]
You can using COPY to overwrite the [cloudrootfs](https://github.com/alibaba/sealer/blob/main/docs/api/cloudrootfs.md) files.
Like this:

define your own kubeadm.yaml
```
FROM kubernetes:v1.19.9
COPY youkubeadm.yaml etc/kubeadm.yaml
```
build your own kubernetes mirror

Or you can update the cloudrootfs directly, then:

```
FROM scratch
COPY . .
```

**Comment by bryant-rh** [comment]
> It's my pleasure to invite you to join us :
> Sealer dingtalk group : 34619594
> Mail list : [sealer@list.alibaba-inc.com](mailto:sealer@list.alibaba-inc.com)
> Developer please add my dingtalk or wechat : fangnux

copy thanks
