### ISSUE TITLE
Does our sealer support non-root users

### ISSUE THREAD

**Issue by kakaZhou719** [alibaba/sealer#214]
#### What happened:

usually ,  not all user with root permission when he execute sealer command , so this will brings the following problems.

sealer images :failed, when local machine is not have sealer image.
sealer rmi,;sealer build;sealer pull ;sealer tag: cmd who need to write image or image metadata.

all of this error caused by  the same reason :  sealer images saved at '/var/lib' that its  permission  is 755, means non root can not write in.
![image](https://user-images.githubusercontent.com/83740799/119926275-a5fafe00-bfa9-11eb-9b4b-6e6e1328e5c3.png)
![image](https://user-images.githubusercontent.com/83740799/119926290-aabfb200-bfa9-11eb-839c-98359fb3b4a6.png)

![image](https://user-images.githubusercontent.com/83740799/119926262-a1364a00-bfa9-11eb-81ea-2c29d04d3c57.png)

#### Environment:
- sealer version (use `sealer version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by justadogistaken** [comment]
I think there is not way to support this feature completely. unless we put sealer file system under /home/{user} @fanux

**Comment by kakaZhou719** [comment]
> I think there is not way to support this feature completely. unless we put sealer file system under /home/{user} @fanux

agreed
