### ISSUE TITLE
This error occurred when creating a cluster

### ISSUE THREAD

**Issue by myxxhui** [alibaba/sealer#216]
#### What happened:
![image](https://user-images.githubusercontent.com/69575321/119938368-e3b65180-bfbe-11eb-9b5b-0f01c00ae527.png)

#### How to reproduce it (as minimally and precisely as possible):
sealer run kubernetes:v1.19.9 --masters   --passwd 
#### Environment:
- sealer version (use `sealer version`): v0.1.4
- Cloud provider or hardware configuration: exiting servers
- OS (e.g: `cat /etc/os-release`): CentOS Linux 7
- Kernel (e.g. `uname -a`): 3.10.0-1160.el7.x86_64
- Install tools:
- Others:

**Comment by fanux** [comment]
Maybe you need `kubeadm reset` before you install.

**Comment by fanux** [comment]
Using v0.1.5-rc or higher version.
