### ISSUE TITLE
Replace kubeadm command with kubeadm api 

### ISSUE THREAD

**Issue by touchuyht** [alibaba/sealer#217]
At present, sealer runtime uses kubeadm command to init k8s cluster or delete it. But the warning/error message dealing with command line feedback is not easy to deal with. I suggest we use kubeadm apis to do the dirty work for we can obtain a more detailed information of the cluster creating or deleting process and makes sealer more robust.
## Issue Description

Type: *feature request*

**Comment by justadogistaken** [comment]
Great! I think we can get more info and handle more complex transaction by doing so.

**Comment by fanux** [comment]
We can add a new runtime, totally not use kubeadm, we create static pod ourself

**Comment by justadogistaken** [comment]
@fanux kubeadm is highly stable, I think there is no need to take risk doing those job on our own

**Comment by justadogistaken** [comment]
@kakaZhou719 It's not hard to do this, but making scale too easy is a good thing? which is risky, especially scale down
