### ISSUE TITLE
Init failed

### ISSUE THREAD

**Issue by clcc2019** [alibaba/sealer#230]
![image](https://user-images.githubusercontent.com/46099295/120162427-f2a13c00-c22a-11eb-8c59-32acd80f00fe.png)

**Comment by fanux** [comment]
Your os support overlay2 or not?

**Comment by clcc2019** [comment]
> Your os support overlay2 or not?

This is centos7，Kernel 3.10x

**Comment by kakaZhou719** [comment]
@clcc2019 ，pls add more environment info:
- sealer version (use `sealer version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

**Comment by clcc2019** [comment]
> * sealer version
{"gitVersion":"v0.1.4","gitCommit":"9090fa8","buildDate":"2021-05-19 08:00:19","goVersion":"go1.14.15","compiler":"gc","platform":"linux/amd64"}

os

NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"


kernel

3.10.0-1160.25.1.el7.x86_64

**Comment by fanux** [comment]
You can delete /var/lib/sealer and  /tmp/my-cluster, and retry

**Comment by fanux** [comment]
OR wait for the v0.1.5 release.

**Comment by fanux** [comment]
v0.1.5-rc released, you can use this version. If not fixed，reopen this issue
