### ISSUE TITLE
 After the initialization is complete, can you provide a way to view the status of the cluster creation?

### ISSUE THREAD

**Issue by ly-wjj** [alibaba/sealer#238]
## Issue Description

Type: *feature request*

### Describe what feature you want
After the initialization is complete，I don't know what the cluster status is。
I think sealer can provide a way to view the cluster or after initialization, the local machine is configured with kubectl

**Comment by fanux** [comment]
Now you can using `kubectl get pod -A -w` to check it.

**Comment by fanux** [comment]
sealer will copy kubectl and kubeconfig to you host
