### ISSUE TITLE
sealer build many times at same cluster image

### ISSUE THREAD

**Issue by cuisongliu** [alibaba/sealer#24]
#### What happened:

build success , but can't push cluster image.  try again build.
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/4150905/116995627-e1890c00-ad0c-11eb-8dc1-2270d48c55d4.png">

cd /var/lib/seadent/metadata
ls -l 

<img width="1124" alt="image" src="https://user-images.githubusercontent.com/4150905/116995718-01203480-ad0d-11eb-9923-0cc3b5c9e24e.png">

#### What you expected to happen:

I think it build one image for same content.
#### Environment:
- sealer version (use `sealer version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by kakaZhou719** [comment]
@cuisongliu 
1,push failed : you need run sealer login to set your docker config json. 
2, build one image yaml file at a time?

**Comment by fanux** [comment]
Same file should has same layer hash to solve this issue I think. @justadogistaken
