### ISSUE TITLE
kubeadm init upload-certs failed.

### ISSUE THREAD

**Issue by justadogistaken** [alibaba/sealer#256]
I go sealer run registry.cn-qingdao.aliyuncs.com/sealer-io/kubernetes:v1.19.9.alpha.1
and failed at kubeadm init phase upload-certs --upload-certs
and then I go to the machine, do kubeadm init phase upload-certs --upload-certs -v 5, there comes error message "open /etc/kubernetes/admin.conf: no such file or directory"

**Comment by hackeren** [comment]
@justadogistaken I have met the same problem too. Could you show me how to handle this? Thanks in advance!

**Comment by justadogistaken** [comment]
@kakaZhou719 Do we have problems like this？ cc @hackeren
