### ISSUE TITLE
Optimize for layer store: Decouple layer digest and layer id

### ISSUE THREAD

**Issue by justadogistaken** [alibaba/sealer#266]
We've been taking digest(layer data) as layerid, it's ok at initiation period and keep the info in image.yaml, which is unique and consistent. But we encountered the problem of different compress digest in different env(majorly derived from header info), and there are no awesome approach to fix the issue well.
So I decide to change the decouple between layer id layer digest,  layer id would be consistent after initiation, but layer digest may change for some reasons. In the meanwhile, I use tar-split util to make sure the filesystem of the layer consistency, even though the layer digest has changed.
And the layer orders in image yaml and in registry description are equal, to make sure each layer can retrieve correct layer filesystem.
![image](https://user-images.githubusercontent.com/38838049/120951916-8a97ac00-c77c-11eb-9da1-d5e4d07e53d7.png)

**Comment by touchuyht** [comment]
And we might need to add a parent record in each layers metadata to make build cache mechanism easy to implement.
