### ISSUE TITLE
Copying files is too slow

### ISSUE THREAD

**Issue by clcc2019** [alibaba/sealer#271]
Files are copied every time the local test environment is initialized, use synchronization method?

**Comment by fanux** [comment]
Can you describe some details? 
Like what you did and how long it took? Or share us your Kubefile

**Comment by clcc2019** [comment]
![image](https://user-images.githubusercontent.com/46099295/121115279-7e2c5580-c847-11eb-8e9f-d4efbd4a43f7.png)
run copy file

**Comment by clcc2019** [comment]
> Can you describe some details?
> Like what you did and how long it took? Or share us your Kubefile

![image](https://user-images.githubusercontent.com/46099295/121115353-93a17f80-c847-11eb-9e50-f7b1207899ed.png)
run copy file

**Comment by fanux** [comment]
We will provide a remote mount feature in the future.

**Comment by fanux** [comment]
https://github.com/alibaba/sealer/issues/937

**Comment by mingmingshiliyu** [comment]
> We will provide a remote mount feature in the future.

the problem exists still!
