### ISSUE TITLE
pre/post check

### ISSUE THREAD

**Issue by fanux** [alibaba/sealer#272]
```
sealer check --pre
sealer check --post
```

We can add a check module, the interface is:
```
type Check interface {
    Check(cluster *v1.Cluster) error
}
```

Define a Node checker to check node is ready after install:

```
type NodeChecker struct {...}

func (n *NodeChecker)Check(cluster *v1.Cluster) error {
     // check if all the node is ready
}
```

Then we can register the checker to checkerList:

func init() {
  checklist = append(checklist, &NodeChecker{}, &PodChecker, &SvcChecker) 
}

**Comment by ly-wjj** [comment]
ok, I will do it.
pre is used to check whether system kernel version is correct .
post is used to check whether the cluster is healthy .

**Comment by kakaZhou719** [comment]
@fanux @ly-wjj ，do we need to divide this checker to more scenario like build checker and apply checker?   cmd looks like:  --module 'build,apply'  and  --type 'cloud or local'
