### ISSUE TITLE
集群多次初始化问题

### ISSUE THREAD

**Issue by clcc2019** [alibaba/sealer#278]
![image](https://user-images.githubusercontent.com/46099295/121107407-7619e900-c83a-11eb-9894-eb6d9ade10ab.png)
![image](https://user-images.githubusercontent.com/46099295/121107457-8b8f1300-c83a-11eb-8cc0-84b5db597ebb.png)

**Comment by clcc2019** [comment]
执行delete -f 不能完全清理节点上的资源，只有手动执行clean.sh清理有效，/var/lib/kubelet，/var/lib/docker等还存在设备或资源忙的问题，也只有手动umont

**Comment by clcc2019** [comment]
![image](https://user-images.githubusercontent.com/46099295/121109470-394ff100-c83e-11eb-857a-7dba883f95a2.png)

![image](https://user-images.githubusercontent.com/46099295/121109419-1b828c00-c83e-11eb-8d5d-05fed3aea3d0.png)

kubelet自启问题

**Comment by bxy4543** [comment]
#322
