### ISSUE TITLE
Pod network problem

### ISSUE THREAD

**Issue by clcc2019** [alibaba/sealer#282]
![image](https://user-images.githubusercontent.com/46099295/121116353-f7787800-c848-11eb-9df9-3e796c323777.png)

![image](https://user-images.githubusercontent.com/46099295/121116401-0eb76580-c849-11eb-99b0-1e1c37eb963e.png)
![image](https://user-images.githubusercontent.com/46099295/121116528-46bea880-c849-11eb-99f2-2561fe67a9b1.png)
Can't ping the outside

Pod cannot be accessed by service name

**Comment by justadogistaken** [comment]
Actually you can't ping service indeed.

**Comment by fanux** [comment]
cat /etc/resolv.conf 

you pod CIDR should not conflict to host name server.

**Comment by fanux** [comment]
> Actually you can't ping service indeed.

IPVS bind clusterip to the nic, so we really can ping the service

**Comment by clcc2019** [comment]
> Actually you can't ping service indeed.
![image](https://user-images.githubusercontent.com/46099295/121117269-7326f480-c84a-11eb-8c4b-9b28d007f9a3.png)
My pod cannot access the external domain name service now, this is fatal

**Comment by clcc2019** [comment]
> cat /etc/resolv.conf
> 
> you pod CIDR should not conflict to host name server.
![Uploading image.png…]()

**Comment by fanux** [comment]
Can you ping the pod on the other host? What is your infra? google cloud?

**Comment by clcc2019** [comment]
> Can you ping the pod on the other host? What is your infra? google cloud?
in google cloud

use delete -f my-calico.yaml，and apply -f my-calico.yaml，the network is connected

**Comment by fanux** [comment]
Can you share your my-calico.yaml?

**Comment by clcc2019** [comment]
> Can you share your my-calico.yaml?

https://docs.projectcalico.org/v3.10/manifests/calico.yaml

CALICO_IPV4POOL_CIDR is 10.244.0.0/16

**Comment by fanux** [comment]
I think the MTU caused this issue.  https://github.com/alibaba/sealer/pull/276
