### ISSUE TITLE
sealer join command

### ISSUE THREAD

**Issue by fanux** [alibaba/sealer#287]
BAREMETAL mod:
```
sealer join --master x.x.x.x --node x.x.x.x
```
CLOUD mod:
```
sealer join --master 2 --node 3 # 2,3 is the count of master or node.
```
1.  New an applier from file(.sealer/my-cluster/Clusterfile)
2. Add join IPs to the cluster object, or set the host count
3. applier.Apply()

**Comment by lllwan** [comment]
I'm going to do it
