### ISSUE TITLE
How to build only locally

### ISSUE THREAD

**Issue by clcc2019** [alibaba/sealer#292]
![image](https://user-images.githubusercontent.com/46099295/121295225-4265be80-c921-11eb-9419-3021d137f0aa.png)

**Comment by clcc2019** [comment]
![image](https://user-images.githubusercontent.com/46099295/121295662-041ccf00-c922-11eb-861c-8f16fff44f6e.png)

**Comment by kakaZhou719** [comment]
pls set arg -b local. this will build locally.
