### ISSUE TITLE
Push images to local registry failed

### ISSUE THREAD

**Issue by clcc2019** [alibaba/sealer#301]
![image](https://user-images.githubusercontent.com/46099295/121334863-a3ef5280-c94c-11eb-9d50-d6de4979ae3b.png)

![image](https://user-images.githubusercontent.com/46099295/121334941-b8cbe600-c94c-11eb-8029-fc50d9253937.png)

Close proxy config

**Comment by justadogistaken** [comment]
@clcc2019 how do you make the close config work in registry?

**Comment by justadogistaken** [comment]
I suggest that you mount the config into registry /etc/docker/registry/config.yml and restart the registry. You can't make the changes work if you don't restart the registry

**Comment by clcc2019** [comment]
> @clcc2019 how do you make the close config work in registry?

Close the proxy in the container, and then restart the container, I have now modified the registry start script

**Comment by justadogistaken** [comment]
> > @clcc2019 how do you make the close config work in registry?
> 
> Close the proxy in the container, and then restart the container, I have now modified the registry start script

How do you modify the registry start script. I' m able to push to the registry when I close cache ability
