### ISSUE TITLE
failed to exec sealer apply in virtual machine

### ISSUE THREAD

**Issue by bxy4543** [alibaba/sealer#303]
Clusterfile ：
apiVersion: sealer.aliyun.com/v1alpha1
kind: Cluster
metadata:
  name: my-cluster
spec:
  image: registry.cn-qingdao.aliyuncs.com/sealer-io/kubernetes:v1.19.9.alpha3
  provider: BAREMETAL
  ssh:
    passwd: *****
    pk: xxx
    pkPasswd: xxx
    user: root
  network:
   ~
  masters:
    ipList:
     - 192.168.56.113
  nodes:
    ipList:
     - 192.168.56.113
 
exec：
sealer apply -f Clusterfile

#### What happened:
...
2021-06-10 12:02:43 [INFO] [init.go:211] start to init master0...
[ssh][192.168.56.113]failed to run command [kubeadm init --config=/var/lib/sealer/data/my-cluster/rootfs/kubeadm-config.yaml --upload-certs -v 0 --ignore-preflight-errors=SystemVerification],output is: W0610 12:02:43.796604   15851 common.go:77] your configuration file uses a deprecated API spec: "kubeadm.k8s.io/v1beta1". Please use 'kubeadm config migrate --old-config old.yaml --new-config new.yaml', which will write the new, similar spec using a newer API version.
W0610 12:02:43.846230   15851 configset.go:348] WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io]
[init] Using Kubernetes version: v1.19.9
[preflight] Running pre-flight checks
        [WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/
        [WARNING FileExisting-socat]: socat not found in system path
        [WARNING Hostname]: hostname "master-01" could not be reached
        [WARNING Hostname]: hostname "master-01": lookup master-01 on 114.114.114.114:53: no such host
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
[certs] Using certificateDir folder "/etc/kubernetes/pki"
[certs] Using existing ca certificate authority
[certs] Using existing apiserver certificate and key on disk
[certs] Using existing apiserver-kubelet-client certificate and key on disk
[certs] Using existing front-proxy-ca certificate authority
[certs] Using existing front-proxy-client certificate and key on disk
[certs] Using existing etcd/ca certificate authority
[certs] Using existing etcd/server certificate and key on disk
[certs] Using existing etcd/peer certificate and key on disk
[certs] Using existing etcd/healthcheck-client certificate and key on disk
[certs] Using existing apiserver-etcd-client certificate and key on disk
[certs] Using the existing "sa" key
[kubeconfig] Using kubeconfig folder "/etc/kubernetes"
[kubeconfig] Using existing kubeconfig file: "/etc/kubernetes/admin.conf"
[kubeconfig] Using existing kubeconfig file: "/etc/kubernetes/kubelet.conf"
W0610 12:03:59.471329   15851 kubeconfig.go:242] a kubeconfig file "/etc/kubernetes/controller-manager.conf" exists already but has an unexpected API Server URL: expected: https://10.0.2.15:6443, got: https://apiserver.cluster.local:6443
[kubeconfig] Using existing kubeconfig file: "/etc/kubernetes/controller-manager.conf"
W0610 12:03:59.724431   15851 kubeconfig.go:242] a kubeconfig file "/etc/kubernetes/scheduler.conf" exists already but has an unexpected API Server URL: expected: https://10.0.2.15:6443, got: https://apiserver.cluster.local:6443
[kubeconfig] Using existing kubeconfig file: "/etc/kubernetes/scheduler.conf"
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[kubelet-start] Starting the kubelet
[control-plane] Using manifest folder "/etc/kubernetes/manifests"
[control-plane] Creating static Pod manifest for "kube-apiserver"
[control-plane] Creating static Pod manifest for "kube-controller-manager"
[control-plane] Creating static Pod manifest for "kube-scheduler"
[etcd] Creating static Pod manifest for local etcd in "/etc/kubernetes/manifests"
[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s
[kubelet-check] Initial timeout of 40s passed.

        Unfortunately, an error has occurred:
                timed out waiting for the condition

        This error is likely caused by:
                - The kubelet is not running
                - The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)

        If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
                - 'systemctl status kubelet'
                - 'journalctl -xeu kubelet'

        Additionally, a control plane component may have crashed or exited when started by the container runtime.
        To troubleshoot, list all containers using your preferred container runtimes CLI.

        Here is one example how you may list all Kubernetes containers running in docker:
                - 'docker ps -a | grep kube | grep -v pause'
                Once you have found the failing container, you can inspect its logs with:
                - 'docker logs CONTAINERID'

error execution phase wait-control-plane: couldn't initialize a Kubernetes cluster
To see the stack trace of this error execute with --v=5 or higher
2021-06-10 12:08:00 [EROR] [apply.go:34] init master0 failed, error: [ssh][192.168.56.113]run command failed [kubeadm init --config=/var/lib/sealer/data/my-cluster/rootfs/kubeadm-config.yaml --upload-certs -v 0 --ignore-preflight-errors=SystemVerification]. Please clean and reinstall

[root@master-01 ~]# cat /etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
192.168.56.113 apiserver.cluster.local
192.168.56.113 sea.hub

[root@master-01 ~]# systemctl status kubelet
● kubelet.service - kubelet: The Kubernetes Node Agent
   Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/kubelet.service.d
           └─10-kubeadm.conf
   Active: active (running) since 四 2021-06-10 13:35:08 CST; 13min ago
     Docs: http://kubernetes.io/docs/
  Process: 5951 ExecStartPre=/usr/bin/kubelet-pre-start.sh (code=exited, status=0/SUCCESS)
 Main PID: 5973 (kubelet)
    Tasks: 15
   Memory: 77.9M
   CGroup: /system.slice/kubelet.service
           └─5973 /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/ku...
6月 10 13:48:32 master-01 kubelet[5973]: I0610 13:48:32.381063    5973 kubelet.go:449] kubelet nodes not sync
6月 10 13:48:32 master-01 kubelet[5973]: E0610 13:48:32.706208    5973 kubelet.go:2134] Container runtime netwo...lized
6月 10 13:48:32 master-01 kubelet[5973]: I0610 13:48:32.854110    5973 kubelet.go:449] kubelet nodes not sync
6月 10 13:48:32 master-01 kubelet[5973]: I0610 13:48:32.930100    5973 kubelet.go:449] kubelet nodes not sync
6月 10 13:48:33 master-01 kubelet[5973]: I0610 13:48:33.414152    5973 kubelet.go:449] kubelet nodes not sync
6月 10 13:48:33 master-01 kubelet[5973]: I0610 13:48:33.853784    5973 kubelet.go:449] kubelet nodes not sync
6月 10 13:48:33 master-01 kubelet[5973]: I0610 13:48:33.929873    5973 kubelet.go:449] kubelet nodes not sync
6月 10 13:48:34 master-01 kubelet[5973]: I0610 13:48:34.381159    5973 kubelet.go:449] kubelet nodes not sync
6月 10 13:48:34 master-01 kubelet[5973]: I0610 13:48:34.895329    5973 kubelet.go:449] kubelet nodes not sync
6月 10 13:48:34 master-01 kubelet[5973]: I0610 13:48:34.930675    5973 kubelet.go:449] kubelet nodes not sync
Hint: Some lines were ellipsized, use -l to show in full.

[root@master-01 ~]# docker ps -a
CONTAINER ID        IMAGE                            COMMAND                  CREATED             STATUS                     PORTS               NAMES
8f92133309ae        1a4f1f05177f                     "kube-apiserver --ad…"   3 minutes ago       Exited (1) 2 minutes ago                       k8s_kube-apiserver_kube-apiserver-master-01_kube-system_b0040d124b1a7478ddbac720ef3492ee_6
469a2861f3cc        a8fd6520f73d                     "kube-controller-man…"   12 minutes ago      Up 12 minutes                                  k8s_kube-controller-manager_kube-controller-manager-master-01_kube-system_28b000d27a4c6961a32c6b0d142f5e3d_0
50e08a5b14b0        sea.hub:5000/library/pause:3.2   "/pause"                 12 minutes ago      Up 12 minutes                                  k8s_POD_kube-controller-manager-master-01_kube-system_28b000d27a4c6961a32c6b0d142f5e3d_0
864e0a4d6ee6        sea.hub:5000/library/pause:3.2   "/pause"                 12 minutes ago      Up 12 minutes                                  k8s_POD_kube-apiserver-master-01_kube-system_b0040d124b1a7478ddbac720ef3492ee_0
d65e229d3f2d        0369cf4303ff                     "etcd --advertise-cl…"   12 minutes ago      Up 12 minutes                                  k8s_etcd_etcd-master-01_kube-system_00f0242af4fba959de9e101dc2915b84_0
9ed6ec112499        sea.hub:5000/library/pause:3.2   "/pause"                 12 minutes ago      Up 12 minutes                                  k8s_POD_etcd-master-01_kube-system_00f0242af4fba959de9e101dc2915b84_0
16e4b00e9c1c        8f1e66e40394                     "kube-scheduler --au…"   12 minutes ago      Up 12 minutes                                  k8s_kube-scheduler_kube-scheduler-master-01_kube-system_b88945f180cd5301b477ccfb11f5ba72_0
51f00f4a39d5        sea.hub:5000/library/pause:3.2   "/pause"                 12 minutes ago      Up 12 minutes                                  k8s_POD_kube-scheduler-master-01_kube-system_b88945f180cd5301b477ccfb11f5ba72_0
e18881eb271d        registry:2.7.1                   "registry serve /etc…"   15 minutes ago      Up 15 minutes                                  sealer-registry

[root@master-01 ~]# docker logs 8f92133309ae
Flag --insecure-port has been deprecated, This flag will be removed in a future version.
I0610 13:45:34.192664       1 server.go:625] external host was not specified, using 10.0.2.15
I0610 13:45:34.193450       1 server.go:163] Version: v1.19.9
I0610 13:45:34.576830       1 plugins.go:158] Loaded 12 mutating admission controller(s) successfully in the following order: NamespaceLifecycle,LimitRanger,ServiceAccount,NodeRestriction,TaintNodesByCondition,Priority,DefaultTolerationSeconds,DefaultStorageClass,StorageObjectInUseProtection,RuntimeClass,DefaultIngressClass,MutatingAdmissionWebhook.I0610 13:45:34.576852       1 plugins.go:161] Loaded 10 validating admission controller(s) successfully in the following order: LimitRanger,ServiceAccount,Priority,PersistentVolumeClaimResize,RuntimeClass,CertificateApproval,CertificateSigning,CertificateSubjectRestriction,ValidatingAdmissionWebhook,ResourceQuota.
I0610 13:45:34.578250       1 plugins.go:158] Loaded 12 mutating admission controller(s) successfully in the following order: NamespaceLifecycle,LimitRanger,ServiceAccount,NodeRestriction,TaintNodesByCondition,Priority,DefaultTolerationSeconds,DefaultStorageClass,StorageObjectInUseProtection,RuntimeClass,DefaultIngressClass,MutatingAdmissionWebhook.I0610 13:45:34.578265       1 plugins.go:161] Loaded 10 validating admission controller(s) successfully in the following order: LimitRanger,ServiceAccount,Priority,PersistentVolumeClaimResize,RuntimeClass,CertificateApproval,CertificateSigning,CertificateSubjectRestriction,ValidatingAdmissionWebhook,ResourceQuota.
I0610 13:45:34.580778       1 client.go:360] parsed scheme: "endpoint"
I0610 13:45:34.580820       1 endpoint.go:68] ccResolverWrapper: sending new addresses to cc: [{https://192.168.56.113:2379  <nil> 0 <nil>}]
W0610 13:45:34.581191       1 clientconn.go:1223] grpc: addrConn.createTransport failed to connect to {https://192.168.56.113:2379  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 192.168.56.113:2379: connect: connection refused". Reconnecting...
I0610 13:45:35.586258       1 client.go:360] parsed scheme: "endpoint"
I0610 13:45:35.586354       1 endpoint.go:68] ccResolverWrapper: sending new addresses to cc: [{https://192.168.56.113:2379  <nil> 0 <nil>}]
W0610 13:45:35.587194       1 clientconn.go:1223] grpc: addrConn.createTransport failed to connect to {https://192.168.56.113:2379  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 192.168.56.113:2379: connect: connection refused". Reconnecting...
W0610 13:45:35.587242       1 clientconn.go:1223] grpc: addrConn.createTransport failed to connect to {https://192.168.56.113:2379  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 192.168.56.113:2379: connect: connection refused". Reconnecting...
W0610 13:45:36.614471       1 clientconn.go:1223] grpc: addrConn.createTransport failed to connect to {https://192.168.56.113:2379  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 192.168.56.113:2379: connect: connection refused". Reconnecting...
W0610 13:45:37.443694       1 clientconn.go:1223] grpc: addrConn.createTransport failed to connect to {https://192.168.56.113:2379  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 192.168.56.113:2379: connect: connection refused". Reconnecting...
W0610 13:45:38.025970       1 clientconn.go:1223] grpc: addrConn.createTransport failed to connect to {https://192.168.56.113:2379  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 192.168.56.113:2379: connect: connection refused". Reconnecting...
W0610 13:45:39.506680       1 clientconn.go:1223] grpc: addrConn.createTransport failed to connect to {https://192.168.56.113:2379  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 192.168.56.113:2379: connect: connection refused". Reconnecting...
W0610 13:45:40.822072       1 clientconn.go:1223] grpc: addrConn.createTransport failed to connect to {https://192.168.56.113:2379  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 192.168.56.113:2379: connect: connection refused". Reconnecting...
W0610 13:45:42.932425       1 clientconn.go:1223] grpc: addrConn.createTransport failed to connect to {https://192.168.56.113:2379  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 192.168.56.113:2379: connect: connection refused". Reconnecting...
W0610 13:45:45.105039       1 clientconn.go:1223] grpc: addrConn.createTransport failed to connect to {https://192.168.56.113:2379  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 192.168.56.113:2379: connect: connection refused". Reconnecting...
W0610 13:45:49.385187       1 clientconn.go:1223] grpc: addrConn.createTransport failed to connect to {https://192.168.56.113:2379  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 192.168.56.113:2379: connect: connection refused". Reconnecting...
W0610 13:45:51.688207       1 clientconn.go:1223] grpc: addrConn.createTransport failed to connect to {https://192.168.56.113:2379  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 192.168.56.113:2379: connect: connection refused". Reconnecting...
Error: context deadline exceeded

#### Environment:
- sealer version (use `sealer version`):
{"gitVersion":"latest","gitCommit":"6626091","buildDate":"2021-06-10 11:37:04","goVersion":"go1.16.4","compiler":"gc","platform":"linux/amd64"}
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
NAME="CentOS Linux"
VERSION="7 (Core)"
- Kernel (e.g. `uname -a`):
Linux master-01 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by bxy4543** [comment]
network configuration problems.

**Comment by trey03** [comment]
> network configuration problems.

hi bro , i have a same problem ,  how do you to solve this problem ?

**Comment by kakaZhou719** [comment]
@trey03 ，what’s your sealer version ? maybe its a bug and already fixed, try upgrade your sealer to solve it.

**Comment by trey03** [comment]
> @trey03 ，what’s your sealer version ? maybe its a bug and already fixed, try upgrade your sealer to solve it.

The problem in my case is to use elastic ip , i switch to eth0's IP is working now， tks!
