### ISSUE TITLE
apply问题

### ISSUE THREAD

**Issue by clcc2019** [alibaba/sealer#304]
![image](https://user-images.githubusercontent.com/46099295/121478843-03f10200-c9fc-11eb-8832-3a3d60deb471.png)

修改Clusterfile文件(加入节点)，执行apply，节点没有复制文件

**Comment by fanux** [comment]
How to reproduce it?

**Comment by clcc2019** [comment]
> How to reproduce it?

初始化集群后，修改集群

> How to reproduce it?

初始化集群后修改clusterfile ，加入节点，执行apply，新加的节点不会复制文件，

**Comment by clcc2019** [comment]
> > How to reproduce it?
> 
> 初始化集群后，修改集群
> 
> > How to reproduce it?
> 
> 初始化集群后修改clusterfile ，加入节点，执行apply，新加的节点不会复制文件，

删除/var/lib/sealer目录重新初始化集群才行
