### ISSUE TITLE
Time sync check

### ISSUE THREAD

**Issue by fanux** [alibaba/sealer#308]
check all  the node Time sync

```
if synced {
   return true
}
err := tryTosync();if err == nil {
   return true
}
return false
```

**Comment by tea403** [comment]
I can try it !

**Comment by tea403** [comment]
i do!

**Comment by fanux** [comment]
@zsyaoo would you continue work on this feature?

**Comment by oldthreefeng** [comment]
time sync is important and is first step to check and need syncd by sealer itself.  
just use ntp go sdk to implement this. so we need to find a good ntp sdk or just write it..
such as follows : 
https://github.com/beevik/ntp
https://github.com/vladimirvivien/go-ntp-client
