### ISSUE TITLE
build sealer with docker and upx sealer

### ISSUE THREAD

**Issue by hhstu** [alibaba/sealer#309]
sealer 二进制文件比较大，一开始想提一个 issue upx 压缩一下 sealer，但觉得要求构建的机器安装 upx有些过分，不如改成用docker 构建 sealer， docker 里装 upx 压缩 sealer。

**Comment by fanux** [comment]
We using github action to build sealer, so we can using upx to build it. I think add `make upx` in Makefile is a good idea. cc @cuisongliu
