### ISSUE TITLE
exec command failed Process exited with status

### ISSUE THREAD

**Issue by myxxhui** [alibaba/sealer#310]
#### What happened:
![image](https://user-images.githubusercontent.com/69575321/121627753-859f6900-caaa-11eb-92db-5433c2ef1a27.png)

#### Environment:
- sealer version (use `sealer version`):v0.1.5
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):centos 7.9
- Kernel (e.g. `uname -a`):3.10.0-1160.el7.x86_64 
- Install tools:
- Others:

**Comment by fanux** [comment]
Your node is clean before you install? Maybe you need `kubeadm reset` your node

**Comment by myxxhui** [comment]
My machine was clean before it was installed.

**Comment by fanux** [comment]
Pls provide your Clusterfile, or you run command

**Comment by myxxhui** [comment]
kind: Cluster
metadata:
  name: my-cluster
spec:
  image: registry.cn-qingdao.aliyuncs.com/sealer-io/kubernetes:v1.19.9.alpha.3
  provider: BAREMETAL
  ssh:
    # ssh的登录密码，如果使用的密钥登录则无需设置
    passwd: *****
    # ssh的私钥文件绝对路径，例如/root/.ssh/id_rsa
    pk: xxx
    # ssh的私钥文件密码，如果没有的话就设置为""
    pkPasswd: xxx
    # ssh登录用户
    user: root
  network:
    # 使用的网卡名称
    interface: ens33
    # 网络插件
    cniName: calico
    podCIDR: 100.64.0.0/10
    svcCIDR: 10.96.0.0/22
    withoutCNI: false
  certSANS:
    - aliyun-inc.com
    - 10.0.0.2

  masters:
    ipList:
     - 192.168.2.51
  nodes:
    ipList:
     - 192.168.2.52

**Comment by fanux** [comment]
Can you provide all the install logs?

**Comment by myxxhui** [comment]
It's all right now. That's why the machine wasn't cleaned up.

**Comment by fanux** [comment]
Fine, can you add my dingtalk or we chat: fangnux
