### ISSUE TITLE
exec command failed Process exited with status

### ISSUE THREAD

**Issue by myxxhui** [alibaba/sealer#315]
#### What happened:
![image](https://user-images.githubusercontent.com/69575321/121663825-65d36980-cad9-11eb-86ec-5ec8f7c7ab1e.png)

#### Environment:
- sealer version (use `sealer version`): v0.1.5
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):centos7
- Kernel (e.g. `uname -a`):3.10.0-862.3.2.el7.x86_64
- Install tools:
- Others:

**Comment by myxxhui** [comment]
Clusterfile
apiVersion: sealer.aliyun.com/v1alpha1
kind: Cluster
metadata:
  name: my-cluster
spec:
  image: registry.cn-qingdao.aliyuncs.com/sealer-io/kubernetes:v1.19.9.alpha.3
  provider: BAREMETAL
  ssh:
    # ssh的登录密码，如果使用的密钥登录则无需设置
    passwd: Hui123123
    # ssh的私钥文件绝对路径，例如/root/.ssh/id_rsa
    pk: 
    # ssh的私钥文件密码，如果没有的话就设置为""
    pkPasswd: 
    # ssh登录用户
    user: root
  network:
    # 使用的网卡名称
    interface: eth0
    # 网络插件
    cniName: calico
    podCIDR: 100.64.0.0/10
    svcCIDR: 10.96.0.0/22
    withoutCNI: false
  certSANS:
    - aliyun-inc.com
    - 10.0.0.2
    
  masters:
    ipList:
     - 172.31.35.165
  nodes:
    ipList:
     - 172.31.46.237
     - 172.31.47.51

**Comment by fanux** [comment]
1. reset all your nodes `kubeadm reset`
2. delete /var/lib/sealer/data/my-cluster
3. retry apply

**Comment by myxxhui** [comment]
![image](https://user-images.githubusercontent.com/69575321/121989639-07ef9c00-cdcf-11eb-966c-a28429b2e356.png)
![image](https://user-images.githubusercontent.com/69575321/121989675-19d13f00-cdcf-11eb-9a63-14d6dd66bfc6.png)
The same mistake heppened

**Comment by fanux** [comment]
You already delete /var/lib/sealer/data/my-cluster on all the hosts?

**Comment by myxxhui** [comment]
yes

**Comment by bxy4543** [comment]
> yes

Can you try v0.2.1 to  see if this problem occurs?
