### ISSUE TITLE
Build independent of kubernetes

### ISSUE THREAD

**Issue by lllwan** [alibaba/sealer#316]
## Issue Description
Step：
1. Run  registry
2. Parse the kubefile, extract the image address and pull it to the local， copy yaml file
3. Tag and push  image to local  registry
4. Check the foundation
5. If testing is needed, it can be verified by the compiled clusterimage of cloud service deployment.
Why not do that?
Type: *feature request*

**Comment by fanux** [comment]
The difficulty with local builds is that we don't know the manifests contain what images. Maybe we can run Kubernetes in a container, or run a fack apiserver to got the imageList.

**Comment by fanux** [comment]
Run kubernetes in docker like kind : https://github.com/kubernetes-sigs/kind

**Comment by bxy4543** [comment]
#434
