### ISSUE TITLE
定制集群拉起速度太慢

### ISSUE THREAD

**Issue by clcc2019** [alibaba/sealer#318]
copying files to 10.170.0.53: 124/885

我们通过修改文件定制了一个集群，加入了我们的应用镜像和charts包，通过这样构建的集群镜像run集群的时候复制文件过程非常慢，尝试将我们的应用镜像提出集群镜像打包，这样集群镜像包很小，但是run仍然很慢，除了镜像，其他文件并不大。如果run过程中出现失败，又会重新执行一遍copy file，本地构建测试镜像真的太蛋疼了

**Comment by fanux** [comment]
确实我们正在考虑使用fack k8s的技术支持本地构建镜像的能力，目前还是通过公有云构建最为方便，如果镜像特别大的时候可能才会出现复制慢的情况，未来我们也会写一个远程mount的功能不再需要拷贝文件以提升性能

**Comment by fanux** [comment]
可否加入钉钉群让我们了解一下详情？ 我账号：fangnux

**Comment by fanux** [comment]
如果文件很多可能快慢与内存大小会很有关系，现在已经支持了只向master0拷贝镜像数据，会减轻很大压力。
