### ISSUE TITLE
sealer 拉取 kubeadm 需要的镜像失败

### ISSUE THREAD

**Issue by togettoyou** [alibaba/sealer#319]
#### What happened:

kubeadm init 过程拉取镜像失败
![image](https://user-images.githubusercontent.com/55381228/121808808-d66eb780-cc8c-11eb-863a-cbb81c7f7a6f.png)

为什么拉取镜像是从本地拉取？

#### Environment:
- sealer version (use `sealer version`): v0.1.5
- Cloud provider or hardware configuration: 本地虚机
- OS (e.g: `cat /etc/os-release`): CentOS Linux 7 (Core)
- Kernel (e.g. `uname -a`): Linux localhost.localdomain 3.10.0-1160.24.1.el7.x86_64

**Comment by togettoyou** [comment]
我目前的解决办法是：
```
#!/bin/bash

## 使用如下脚本下载国内镜像，修改tag
set -e

KUBE_VERSION=v1.19.11
KUBE_PAUSE_VERSION=3.2
ETCD_VERSION=3.4.13-0
CORE_DNS_VERSION=1.7.0

ALIYUN_URL=registry.aliyuncs.com/google_containers
LOCAL_URL=sea.hub:5000/library

images=(kube-proxy:${KUBE_VERSION}
kube-scheduler:${KUBE_VERSION}
kube-controller-manager:${KUBE_VERSION}
kube-apiserver:${KUBE_VERSION}
pause:${KUBE_PAUSE_VERSION}
etcd:${ETCD_VERSION}
coredns:${CORE_DNS_VERSION})

for imageName in ${images[@]} ; do
  docker pull $ALIYUN_URL/$imageName
  docker tag  $ALIYUN_URL/$imageName $LOCAL_URL/$imageName
  docker rmi $ALIYUN_URL/$imageName
done
```

有办法原生支持吗？

**Comment by justadogistaken** [comment]
can you output the image id by sealer images?
and do you have the log for why registry does not start?

**Comment by togettoyou** [comment]
![image](https://user-images.githubusercontent.com/55381228/121812520-b0e8aa80-cc9a-11eb-92c9-4e065e2f5ee6.png)
@justadogistaken

**Comment by togettoyou** [comment]
![image](https://user-images.githubusercontent.com/55381228/121812562-daa1d180-cc9a-11eb-97c1-a6078127c258.png)

**Comment by togettoyou** [comment]
我再排查一下

**Comment by togettoyou** [comment]
哈哈，可以了，是我开了代理导致的，看到你说 registry 才反应过来，去看网络。

这个项目很赞呀👍
