### ISSUE TITLE
Only copy rootfs /registry dir to master0

### ISSUE THREAD

**Issue by fanux** [alibaba/sealer#320]
Now we copy /registry to all nodes.

**Comment by justadogistaken** [comment]
@fanux I guess this problem could be solved by not sending registry files?

**Comment by fanux** [comment]
What if execution machine is not master0?

**Comment by justadogistaken** [comment]
> What if execution machine is not master0?

and is it good to send registry to master0 only?

**Comment by fanux** [comment]
Remote mount it on master0 and copy it locally.
