### ISSUE TITLE
failed to push image layer hash changed.

### ISSUE THREAD

**Issue by fanux** [alibaba/sealer#334]
![image](https://user-images.githubusercontent.com/8912557/122500056-9c067100-d024-11eb-8768-054a9d82f708.png)

When I try to build a helm cloudImage:

Kubefile is : 
```
FROM kubernetes:v1.19.9
RUN wget https://get.helm.sh/helm-v3.6.0-linux-amd64.tar.gz && tar zxvf helm-v3.6.0-linux-amd64.tar.gz && mv linux-amd64/helm /usr/bin
```
```
sealer build -t sealer build -t registry.cn-qingdao.aliyuncs.com/sealer-apps/helm:v3.6.0 .
```

push image failed.

[root@iZ2vchi0m75ix9ffp3tt4yZ helm]# sealer version
{"gitVersion":"latest","gitCommit":"5896435","buildDate":"2021-06-18 10:34:23","goVersion":"go1.14.2","compiler":"gc","platform":"linux/amd64"}

**Comment by justadogistaken** [comment]
@fanux which branch does the sealer build from? Or does the branch contains commit-f807d7be879a6? The problem should be solved by f807d7be879a6.
