### ISSUE TITLE
When will it be supported to modify the calico version?

### ISSUE THREAD

**Issue by clcc2019** [alibaba/sealer#340]
Cannot modify the calico mirror version now

**Comment by fanux** [comment]
you can use without CNI flag and install it yourself now

**Comment by oldthreefeng** [comment]
we can use a metadata flag. when run `sealer build`. it use the calico version just name it v3.8.2.   then store it in metadata.
so when use `sealer run `, read the version in the metadata.
use the we can build any calico version you want, just build it like an real plugin. @fanux @clcc2019

**Comment by fanux** [comment]
@oldthreefeng now sealer has config feature, so I think we can put CNI in the guest layer.

```
FROM kubernetes:v1.19.9
COPY calico-crd.yaml .
CMD kubectl apply -f calico-crd.yaml
```

[config docs](https://github.com/alibaba/sealer/blob/main/docs/design/global-config.md#application-config)

**Comment by oldthreefeng** [comment]
so sealer build a pure kubernetes cluster even it does not contain an net work plugin?

**Comment by fanux** [comment]
Yes, we can build a CloudImage contains the calico CNI.

**Comment by fanux** [comment]
https://github.com/alibaba/sealer/tree/main/applications/calico/latest
