### ISSUE TITLE
Context useless for local build

### ISSUE THREAD

**Issue by justadogistaken** [alibaba/sealer#353]
I have a Kubefile:
```
FROM scratch
COPY kubeadm .
```
and I have kubeadm under ./bin

and I go sealer build -t test:v1 -c ./bin/

the result is error of "failed to exec layer &{ COPY kubeadm .}:stat kubeadm: no such file or directory"

**Comment by fanux** [comment]
@kakaZhou719 You need to set the context dir as build work dir.
