### ISSUE TITLE
need to add more checker

### ISSUE THREAD

**Issue by kakaZhou719** [alibaba/sealer#362]
## Issue Description

Type: *feature request*

### Describe what feature you want
we need more checker, such host info ,system info ,base software  and so on, for tracking user problem, or preparing sealer environment.
check list(need to update):
1,node network
2, node time sync
3,node CPU,mem,disk ,etc.
4,user privilege
5, sealer dir.

**Comment by fanux** [comment]
1. node network, check what?
2. the time sync feature will be provided in other PR
3. master CPU must > 2
4. needs what privilege?
5. check sealer dir details?

@kakaZhou719 I think we should provide more details in those checks, so developers can join us.

**Comment by wisheen** [comment]
1. os: os version, mem > 2G, cpu > 2, free disk > 20G, open file limit, etc
2. user: must root or sudo user  
3. network: host can be reached over ssh (port、password、sshd conf ),  firewall disable ? muliti network

**Comment by fanux** [comment]
@wisheen Would you like to provide these features? You can add the CPU mem checker first~

**Comment by wisheen** [comment]
> @wisheen Would you like to provide these features? You can add the CPU mem checker first~

OK, assign to me.  It might be a little slower，usually a bit busy  and just a Go language beginner

**Comment by fanux** [comment]
@wisheen ok, we provide one week for you to handle this feature~. We want this feature in release v0.3.0 on 2021.7.23, I will do my best to help you.

**Comment by wisheen** [comment]
@fanux I'm sorry. will be delayed.
The development environment took some time to setup，and study to learn about structure.
My question is:
1. check/service/pre_check.go design to check dependencies before cluster creation, when should call it?
   It is inconvenient to use sealer check --pre cmd
   Check it when join a node? sealer run, sealer join or seal apply
2. sealer run/join/apply, check all new hosts(masters and nodes) before Initializing host, or after ssh.WaitSSHReady(joinMasters or joinNodes) to check each one?
    It's better that check all beforfe Initializing host ?
