### ISSUE TITLE
what is the main benefit using sealer rather than ansible?

### ISSUE THREAD

**Issue by FingerLiu** [alibaba/sealer#364]
Is this a docs explain why use sealer rather than ansible

**Comment by fanux** [comment]
I think these two are completely solving different problems and should not be compared together. 
Some Kubernetes ansible install script just helps you install the cluster, sealer helps you to define your own cluster using Kubefile.
sealer is simple and fast, it also helps you to cache all the container images and package them in CloudImage.

**Comment by FingerLiu** [comment]
>  it also helps you to cache all the container images and package them in
CloudImage
Ansible can also do this through artifacts and it is more Configurable

中弈 ***@***.***> 于2021年7月1日周四 上午11:04写道：
