### ISSUE TITLE
 the process of mountroofs will be killed by the system When the image file is too large

### ISSUE THREAD

**Issue by ly-wjj** [alibaba/sealer#365]
#### What happened:

Machine configuration 2C4G

![image](https://user-images.githubusercontent.com/20943183/123916664-8134e480-d9b4-11eb-8b0e-fef6e64d8e51.png)

![image](https://user-images.githubusercontent.com/20943183/123916617-71b59b80-d9b4-11eb-89c0-8297f1d1f97c.png)

![image](https://user-images.githubusercontent.com/20943183/123916838-ac1f3880-d9b4-11eb-8dc1-7ac71b189e03.png)

#### Environment:
- sealer version (use `sealer version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by fanux** [comment]
Out of memory, the memory of the host is?

**Comment by ly-wjj** [comment]
> Out of memory, the memory of the host is?
 4G

**Comment by fanux** [comment]
The memory is too small to copy too many large files.
