### ISSUE TITLE
metrics-server is not ready

### ISSUE THREAD

**Issue by clcc2019** [alibaba/sealer#369]
![image](https://user-images.githubusercontent.com/46099295/124060918-8cdde500-da60-11eb-93d6-e51953cec991.png)
![image](https://user-images.githubusercontent.com/46099295/124061347-4c329b80-da61-11eb-8cef-6ea75d98a4ef.png)

**Comment by fanux** [comment]
10.148.0.9 is the node IP?
![image](https://user-images.githubusercontent.com/8912557/124081006-96297a80-da7d-11eb-8752-cd2ea8fd46c2.png)
This is the /var/log/messages？

**Comment by clcc2019** [comment]
> 10.148.0.9

10.148.0.9  is master ,this is metrics pod logs

**Comment by cuisongliu** [comment]
default not install metrics-server

**Comment by fanux** [comment]
We can provide a full monitor stack CloudImage later.
