### ISSUE TITLE
sealer push image id

### ISSUE THREAD

**Issue by cuisongliu** [alibaba/sealer#37]
## Issue Description

Type: *feature request*

### Additional context

<img width="1494" alt="image" src="https://user-images.githubusercontent.com/4150905/117330408-3c1a9780-aec8-11eb-9d58-e14bd7614211.png">

**Comment by fanux** [comment]
Docker is not supporting push an image using image ID, so we don't provide this feature too.

**Comment by fanux** [comment]
One image ID may have multiple names, we can't decide push witch one.
