### ISSUE TITLE
join node faild

### ISSUE THREAD

**Issue by clcc2019** [alibaba/sealer#373]
![image](https://user-images.githubusercontent.com/46099295/124078039-4b5a3380-da7a-11eb-8a69-99321ca9c7d9.png)

**Comment by fanux** [comment]
Clean the node first, using `kubeadm reset -f` on the node.

**Comment by clcc2019** [comment]
> Clean the node first, using `kubeadm reset -f` on the node.

this node is a new instance

**Comment by fanux** [comment]
What your sealer version and join command?

**Comment by fanux** [comment]
@bxy4543 try to reproduce and fix it.

**Comment by clcc2019** [comment]
> What your sealer version and join command?



> What your sealer version and join command?

sealer 0.2.0
sealer join -n 10.148.0.11

**Comment by bxy4543** [comment]
> > What your sealer version and join command?
> 
> > What your sealer version and join command?
> 
> sealer 0.2.0
> sealer join -n 10.148.0.11

10.148.0.11 Has anything been done on this node? Why is the /etc/kubernetes/manifast directory for new instance not empty.
You can try removing /etc/kubernetes/manifast and try sealer join again.

**Comment by bxy4543** [comment]
The /etc/kubernetes/manifast directory for join nodes cannot exist
