### ISSUE TITLE
sealer build generates empty layer when running in non-overlay filesystem

### ISSUE THREAD

**Issue by touchuyht** [alibaba/sealer#384]
#### What happened:
I was reading the source code in local_builder.go and found a logic error in execOtherLayer().
`func (l *LocalBuilder) execOtherLayer(layer *v1.Layer, lowLayers []string) error {
	tempTarget, err := utils.MkTmpdir()
	if err != nil {
		return fmt.Errorf("failed to create %s:%v", tempTarget, err)
	}
	tempUpper, err := utils.MkTmpdir()
	if err != nil {
		return fmt.Errorf("failed to create %s:%v", tempUpper, err)
	}
	defer utils.CleanDirs(tempTarget, tempUpper)

	if err = l.mountAndExecLayer(layer, tempTarget, tempUpper, lowLayers...); err != nil {
		return err
	}
	if err = l.calculateLayerHashAndPlaceIt(layer, tempUpper); err != nil {
		return err
	}
	return nil
}`
As shown above,  it creates two temp directories, 'tempTarget' for saving previous layers and 'tempUpper' for saving current layer's executing results. When the program runs into  err = l.mountAndExecLayer(layer, tempTarget, tempUpper, lowLayers...) and if the program is running in non-overlay environment, the changes of current layer is saved in tempTarget which will be deleted after the l.mountAndExecLayer() returns. So the empty directory 'tempUpper' is saved as a layer.
Besides, if a user writes an absolute path as run command's args, the result of the command cannot be saved as a layer but there is no warning either in the document or in the program mentioning about this. And if a user writes a 'kubectl apply -f someyaml.yaml' as cmd command's args, the image saved in the running k8s cluster will not be packaged into sealer images. In this case I think it can be provided as an option for user to decide whether to save the image in the final sealer image or not.

#### Environment:
- sealer version (use `sealer version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by kakaZhou719** [comment]
@touchuyht ,sorry for the long time to reply. very meticulous work. +1.

1. non-overlay environment cache empty directory  as a layer.
 at present , we only support the overlay filesystem to cache the build result.

2.  Kubefile "RUN  kubectl apply -f someyaml.yaml", will not cache docker image.

    we provide doc here to distinguish the "RUN" and "CMD",also we provide the cache options and without base options
in the sealer cmd.

wish you add more valuable suggestions for us。
