### ISSUE TITLE
Sealer lite build without kubernetes cluster instance

### ISSUE THREAD

**Issue by lllwan** [alibaba/sealer#398]
It is considered that sealer needs to support the function of caching images according to the custom image list. The reasons are as follows.

1. At present, the cost of pulling up the cluster to cache the image is high. Cache for core images that do not need to be changed frequently.

2. Users may want to build in some images that cannot be used in the delivery phase, such as some job tasks. When the business does not generate actual scheduling, sealer cannot capture the image address.

3. Give users freedom, so that users can even complete a very lightweight build through the known image list.

## Issue Description

Type: *feature request*

**Comment by fanux** [comment]
- [x] auto detect helm chart image list
- [x] auto detect yaml image list
- [ ] not support CRD image detect

work flow:
1. detect and get imagelist
2. run a registry container, send pull request to the registry 
3. got the registry mount dir

**Comment by fanux** [comment]
How do I know the manifests is a chart? copy it to $rootfs/charts dir, sealer only detects this dir and get helm chart image list.

**Comment by lllwan** [comment]
#426 support lite build
