### ISSUE TITLE
sealer add wrong domain for registry host info 

### ISSUE THREAD

**Issue by kakaZhou719** [alibaba/sealer#399]
#### What happened:

sealer run kubernetes:v1.19.9 -m **172.17.0.2:2218** -p XXXX

![image](https://user-images.githubusercontent.com/83740799/124578678-015dbd00-de81-11eb-9948-4b14e6eb0172.png)

#### What you expected to happen:

need to split the host with ip+port

#### Environment:
- sealer version (use `sealer version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by lllwan** [comment]
I'll fix it

**Comment by kakaZhou719** [comment]
besides， copy kubeconfig failed too after sealer apply. maybe all the host string need to do split. SSH interface use port 22 as default.
![image](https://user-images.githubusercontent.com/83740799/124581051-51d61a00-de83-11eb-89c0-8e1a06dca6fa.png)

**Comment by fanux** [comment]
@lllwan use the utils.GetHostIP(master0)

**Comment by lllwan** [comment]
#405
