### ISSUE TITLE
Instance health check

### ISSUE THREAD

**Issue by clcc2019** [alibaba/sealer#406]
![image](https://user-images.githubusercontent.com/46099295/124871494-afd73e80-dff6-11eb-8d8f-955f58f8ba63.png)

1、Instance root password error,  Command stuck
2、ssh connection failed, Command stuck

**Comment by bxy4543** [comment]
This is not a stuck command, if there is a problem with the network, then retry connecting to the server.

**Comment by clcc2019** [comment]
> This is not a stuck command, if there is a problem with the network, then retry connecting to the server.

the retry time too long? Can you quickly determine if an error is thrown and let the user handle it

**Comment by fanux** [comment]
![image](https://user-images.githubusercontent.com/8912557/125221304-9e45ad80-e2fa-11eb-9fb4-5250316ddddd.png)

Pending more than 10 second?

**Comment by bxy4543** [comment]
#410 Reduced retry ping time
