### ISSUE TITLE
the problems when installing  sealer in red-hot server

### ISSUE THREAD

**Issue by UniqueCh** [alibaba/sealer#412]
#### Environment:

- sealer version (use `sealer version`):0.2.1
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):Linux Server 7.2 (Paladin)
- Kernel (e.g. `uname -a`):Linux h07d11130.sqa.eu95 3.10.0-327.ali2008.alios7.x86_64
- Install tools:sealer run
- Others:

**Comment by fanux** [comment]
![image](https://user-images.githubusercontent.com/8912557/125234144-ac9fc380-e312-11eb-953a-dcfcafa4e5da.png)
Failed to start registry

**Comment by fanux** [comment]
Not support alios now, install docker failed.
