### ISSUE TITLE
Alios通过Sealer部署k8s的过程

### ISSUE THREAD

**Issue by UniqueCh** [alibaba/sealer#418]
sealer是ADP团队开源的集群镜像技术，可以把整个集群整体打包，实现分布式应用和k8s一起Build&Share&Run，介绍如下：[https://mp.weixin.qq.com/s/QcK7hhnz3xltM2GtmHnQXA](https://mp.weixin.qq.com/s/QcK7hhnz3xltM2GtmHnQXA)<br />当前版本v0.2.1不支持Alios（要求内核版本3.10以上或者centos,相关问题：[https://github.com/fanux/cloud-kernel/issues/12](https://github.com/fanux/cloud-kernel/issues/12)），在中弈同学、槐佳辉同学的支持下在Alios上安装成功，记录一下在Alios上安装k8s的流程。
<a name="fLKN1"></a>
## 背景 ：
刚开始尝试在本机mac系统上用sealer安装k8s集群，发现sealer不支持macOS，转去使用Alios；测试发现当前版本的sealer也不支持Alios，于是尝试重装Centos；但重装后Centos无法联外网，又转回Alios。**不支持alios的原因是在alios上脚本不会创建docker0，故需要修改脚本**；下面详细地记录了安装过程。<br />![image.png](https://cdn.nlark.com/yuque/0/2021/png/22013874/1626241337853-03cd4ea8-9195-417d-ab72-7919cd11a236.png#align=left&display=inline&height=151&margin=%5Bobject%20Object%5D&name=image.png&originHeight=302&originWidth=2734&size=577073&status=done&style=none&width=1367)
<a name="QI0ej"></a>
## 主机环境：
![image.png](https://cdn.nlark.com/yuque/0/2021/png/22013874/1626242341753-2d953196-3c0b-4132-b1b1-c04555d9ea98.png#align=left&display=inline&height=640&margin=%5Bobject%20Object%5D&name=image.png&originHeight=1280&originWidth=2512&size=1252951&status=done&style=none&width=1256)
<a name="ThoSE"></a>
## 安装步骤：
<a name="4E1mG"></a>
### 0. 注意：Sealer的安装需要干净的环境，没有k8s和docker 。
<a name="6fPbe"></a>
### 1. Install Sealer binaries
执行以下命令，如果需要 sudo可以拆分执行：
```bash
wget https://github.com/alibaba/sealer/releases/download/v0.2.1/sealer-v0.2.1-linux-amd64.tar.gz && \
tar zxvf sealer-v0.2.1-linux-amd64.tar.gz && mv sealer /usr/bin
```
<a name="2wpqZ"></a>
### 2. 修改脚本
<a name="2u6iD"></a>
#### a) 拉镜像，包括脚本文件，执行以下命令：
```bash
sudo sealer pull registry.cn-qingdao.aliyuncs.com/sealer-io/kubernetes:v1.19.9
```
<a name="z4C0e"></a>
#### b) 可以找到/var/lib/sealer/data/overlay2下的脚本；

- 要修改的脚本为''docker.sh"，和issue12中描述的不同，文件保存在"overlayr2/一大串字符/scripts"下，进入一大串字符的文件夹下，执行以下命令修改：

![image.png](https://cdn.nlark.com/yuque/0/2021/png/22013874/1626242426379-59b1ee7f-50b4-48d3-b556-05b6b4cf36df.png#align=left&display=inline&height=98&margin=%5Bobject%20Object%5D&name=image.png&originHeight=196&originWidth=2736&size=269491&status=done&style=none&width=1368)
```bash
sudo vi scripts/docker.sh
```

- 找到"docker.sh"的第27行，加上alios:
```diff
原来：centos|rhel|ol|sles)
改为：alios|centos|rhel|ol|sles)
```

- 修改"init.sh"，执行`sudo vi scripts/init.sh`，在第二行插入
```shell
modprobe br_netfilter
echo 1 > /proc/sys/net/bridge/bridge-nf-call-iptables
ip link add name docker0 type bridge
ip addr add dev docker0 172.17.0.1/16
```
modprobe:添加/删除Linux内核模块，echo 1：添加路由表，其他的命令是配置docker的网络
<a name="R58Ng"></a>
#### c)通过Sealer运行kubernetes

- 执行`sealer run kubernetes:v1.19.9 --masters 192.168.0.2 --passwd xxx`，其中master的ip是本机ip，通过`ifconfig`查看；passwd为本机密码，通过`sudo passwd root`设置。 **如果ip或者密码错误，会报错如下**：

![image.png](https://cdn.nlark.com/yuque/0/2021/png/22013874/1626242498060-e45da799-ff19-44a2-bb4e-0c0d181164ce.png#align=left&display=inline&height=171&margin=%5Bobject%20Object%5D&name=image.png&originHeight=342&originWidth=2748&size=920261&status=done&style=none&width=1374)

- 执行过程中可能出现 **[EROR] [run.go:55] failed to found ent nic，如下；**

![image.png](https://cdn.nlark.com/yuque/0/2021/png/22013874/1626242621086-3d107785-2ae4-4c8c-8e73-160e076aee05.png#align=left&display=inline&height=439&margin=%5Bobject%20Object%5D&name=image.png&originHeight=878&originWidth=2710&size=2306149&status=done&style=none&width=1355)<br />     可以通过`ifconfig`查看名称；<br />![image.png](https://cdn.nlark.com/yuque/0/2021/png/22013874/1626242706442-8a324e20-ea61-4603-94a6-39d23d0d11da.png#align=left&display=inline&height=723&margin=%5Bobject%20Object%5D&name=image.png&originHeight=1446&originWidth=2486&size=1463972&status=done&style=none&width=1243)<br />     重新执行命令：
```bash
sudo sealer run kubernetes:v1.19.9 --masters 192.168.0.2 --passwd xxx ----interface xxx
```
<a name="tCTNo"></a>
## 成功安装!
![image.png](https://cdn.nlark.com/yuque/0/2021/png/22013874/1626165133122-39c13c6e-3587-4c86-b050-b9e1302a51e2.png#align=left&display=inline&height=538&margin=%5Bobject%20Object%5D&name=image.png&originHeight=1076&originWidth=2404&size=1006184&status=done&style=none&width=1202)<br />安装的sealer版本：<br />![image.png](https://cdn.nlark.com/yuque/0/2021/png/22013874/1626168050678-d583e332-0568-482f-89fa-e3ec15743d30.png#align=left&display=inline&height=122&margin=%5Bobject%20Object%5D&name=image.png&originHeight=122&originWidth=856&size=35290&status=done&style=none&width=856)<br />安装的kube版本：<br />![image.png](https://cdn.nlark.com/yuque/0/2021/png/22013874/1626168084226-94683a52-7522-4c59-8f2b-950b92f795c1.png#align=left&display=inline&height=142&margin=%5Bobject%20Object%5D&name=image.png&originHeight=142&originWidth=2038&size=136481&status=done&style=none&width=2038)<br />安装的docker版本：<br />![image.png](https://cdn.nlark.com/yuque/0/2021/png/22013874/1626168106215-06febf42-3d46-4ca4-a687-0cb015b4fe2a.png#align=left&display=inline&height=370&margin=%5Bobject%20Object%5D&name=image.png&originHeight=370&originWidth=1552&size=124061&status=done&style=none&width=1552)<br />

**Comment by cuisongliu** [comment]
sealer pull registry.cn-beijing.aliyuncs.com/sealer-io/kubernetes:v1.19.9

**Comment by cuisongliu** [comment]
<img width="644" alt="image" src="https://user-images.githubusercontent.com/4150905/125546807-7ab500a6-b9c6-4b86-8116-b616a7fba70d.png">
我直接改的docker的脚本。毕竟init是所有的环境都执行的。但这个需要测试一下。
