### ISSUE TITLE
docker start Failed

### ISSUE THREAD

**Issue by clcc2019** [alibaba/sealer#427]
![image](https://user-images.githubusercontent.com/46099295/125736843-1cfe1631-1c49-464e-8716-d0f07cd1fcc9.png)

**Comment by clcc2019** [comment]
![image](https://user-images.githubusercontent.com/46099295/125737771-a75a5b15-d208-43e1-8b8e-047913813cd4.png)

**Comment by clcc2019** [comment]
![image](https://user-images.githubusercontent.com/46099295/125751392-791dcd00-2bd7-4847-b4a7-1db5885be1b9.png)

**Comment by justadogistaken** [comment]
@clcc2019 Could you provide /usr/lib/systemd/system/docker.service or /lib/systemd/system/docker.service?

**Comment by clcc2019** [comment]
> /usr/lib/systemd/system/docker.service

![image](https://user-images.githubusercontent.com/46099295/125754080-6a2428bd-c0be-40a9-a9e8-422d1d7fb4bf.png)

**Comment by justadogistaken** [comment]
@clcc2019 type `lsb_release -a` and `dockerd` to see what will happen.

**Comment by clcc2019** [comment]
> dockerd
@justadogistaken 
![image](https://user-images.githubusercontent.com/46099295/125773551-89ccb01f-cc7c-4ad8-aead-a35ec22d430c.png)

**Comment by clcc2019** [comment]
> lsb_release

![image](https://user-images.githubusercontent.com/46099295/125774616-5fae67df-141b-4cd2-a02d-56db1de12c2f.png)

**Comment by justadogistaken** [comment]
@clcc2019 I have a same linux vm, and no such errors occurred.  I found some solutions, could you follow the following approaches and see if it works?
1. rm -rf /var/lib/docker (will delete images) -> systemctl daemon-reload -> systemctl restart docker.
2. check on the host machine please with sysctl vm.overcommit_memory if memory overcommitment is enabled and set the value to 1 with sysctl vm.overcommit_memory=1 if not

**Comment by clcc2019** [comment]
> @clcc2019 I have a same linux vm, and no such errors occurred. I found some solutions, could you follow the following approaches and see if it works?
> 
> 1. rm -rf /var/lib/docker (will delete images) -> systemctl daemon-reload -> systemctl restart docker.
> 2. check on the host machine please with sysctl vm.overcommit_memory if memory overcommitment is enabled and set the value to 1 with sysctl vm.overcommit_memory=1 if not

I think it is caused by the files in the /etc/docker directory

**Comment by fanux** [comment]
@clcc2019 this issue fixed now? I will close this issue now if you already have this issue, reopen it
