### ISSUE TITLE
Cluster images failed to build

### ISSUE THREAD

**Issue by clcc2019** [alibaba/sealer#436]
![image](https://user-images.githubusercontent.com/46099295/126067724-9f9aedd9-63e1-4326-befa-effbdcb6c247.png)

**Comment by bxy4543** [comment]
Build successfully, copy is one of the image layers, rootfs was created when apply, you need to uninstall and apply with the image created by this build, rootfs will have the copy file.

**Comment by bxy4543** [comment]
Runtime upgrade image will be available in the future

**Comment by clcc2019** [comment]
> Build successfully, copy is one of the image layers, rootfs was created when apply, you need to uninstall and apply with the image created by this build, rootfs will have the copy file.

![image](https://user-images.githubusercontent.com/46099295/126092957-f1c43dba-ff26-420d-8489-6d8daf6cc978.png)
build failed
