### ISSUE TITLE
Can't the mirror cache be build into the cluster mirror?

### ISSUE THREAD

**Issue by clcc2019** [alibaba/sealer#466]
Can't the mirror cache be build into the cluster mirror?

**Comment by justadogistaken** [comment]
@clcc2019 I can't follow you. Could you describe the issue as detail as possible

**Comment by clcc2019** [comment]
> @clcc2019 I can't follow you. Could you describe the issue as detail as possible

When building a cluster, pull images to docker, whether these images can be packaged into the cluster in the offline environment

**Comment by kakaZhou719** [comment]
@clcc2019 pls see this PR,https://github.com/alibaba/sealer/pull/462

**Comment by fanux** [comment]
@clcc2019  docker image will be packaged into cloudImage.

**Comment by clcc2019** [comment]
> @clcc2019 docker image will be packaged into cloudImage.

Now the cached application image is not packaged into the cluster

**Comment by bxy4543** [comment]
#462
