### ISSUE TITLE
support edit clusterfile for sealer image 

### ISSUE THREAD

**Issue by kakaZhou719** [alibaba/sealer#485]
## Issue Description

Type: *feature request*

### Describe what feature you want
as we konw ,sealer save clusterfile at image metadata context.
in some build scene. we need to modify the default clusterfile like node number or some infra info for temporary use

work flow as below . 
1,sealer edit {your images}:
2,do some edit work
3, save and quit.this will save the latest modify at image metadata.

**Comment by fanux** [comment]
Why don't you copy a Clusterfile and overwrite it.
```
FROM xxx
COPY you-clusterfile.yaml Clusterfile
```
