### ISSUE TITLE
How to import nvidia plugin?

### ISSUE THREAD

**Issue by egliu** [alibaba/sealer#496]
Use kubefile?

**Comment by fanux** [comment]
https://github.com/RadeonOpenCompute/k8s-device-plugin  I think using kubefile to register GPU is pretty simple:

Like:
```
FROM kubernetes:v1.19.9
CMD kubectl create -f https://raw.githubusercontent.com/RadeonOpenCompute/k8s-device-plugin/master/k8s-ds-amdgpu-dp.yaml
```

**Comment by egliu** [comment]
> https://github.com/RadeonOpenCompute/k8s-device-plugin

What about Nvidia Device pulgin?
1. install nvidia-docker2
2. kubectl create -f nvidia-device-plugin.yml

**Comment by fanux** [comment]
We hacked the docker source code to cache the container images, so if you use nvidia-docker you lose the sealer cache feature.

@justadogistaken can we support nvidia Device plugin using containerd?

**Comment by egliu** [comment]
Done. Refer to this Kubefie.
COPY ./nvidia-container-cli .
COPY ./nvidia-container-runtime .
COPY ./nvidia-container-runtime-hook .
COPY ./libnvidia-container.so.1 .
COPY ./daemon.json .
COPY ./nvidia-device-plugin.yml .
CMD cp ./nvidia-container-* /usr/bin/
CMD chmod +x /usr/bin/nvidia-container-*
CMD cp ./libnvidia-container.so.1 /usr/lib64/
CMD cp ./daemon.json /etc/docker/
CMD kubectl taint nodes --all node-role.kubernetes.io/master-
CMD systemctl restart docker
CMD sleep 100
CMD kubectl apply -f ./nvidia-device-plugin.yml

**Comment by fanux** [comment]
@egliu you can use nvidia docker instead of the default docker bin file, but you will lose the container cache feature when building CloudImage.  You need to push the container images into the private registry and using the private registry image domain name.

**Comment by egliu** [comment]
> @egliu you can use nvidia docker instead of the default docker bin file, but you will lose the container cache feature when building CloudImage. You need to push the container images into the private registry and using the private registry image domain name.

Default docker binaries are not replaced, only nvidia related dependencies are added.
![image](https://user-images.githubusercontent.com/5033089/130048356-9334dd37-89d5-4153-9da6-83663ad3daa0.png)
![image](https://user-images.githubusercontent.com/5033089/130048526-73c8dc86-0bdb-4858-823e-82d8ef775c79.png)

**Comment by fanux** [comment]
@egliu awesome work, I think you can provide this base image for other developers.

**Comment by egliu** [comment]
@fanux Currently this is a rough solution, I'm working on adding nvidia binaries before k8s running. It seems modify docker.sh in rootfs/scripts is the only way. Please correct me if I am wrong.

**Comment by fanux** [comment]
Sealer support overwrites any file in rootfs, so that is fine.  if we support contained we also need to modify docker.sh to containerd.sh.  different CloudImage have different requirements.

**Comment by fanux** [comment]
@egliu could you provide GPU CloudImage? You can push CloudImage to the docker hub, then give us the image name.

**Comment by egliu** [comment]
Sure, will let you know if the image is ready.

**Comment by kakaZhou719** [comment]
@egliu ,thanks for your nice work, i build  GPU base image named "registry.cn-qingdao.aliyuncs.com/sealer-io/kubernetes-nvidia:v1.19.8", we can use sealer pull to download it.
