### ISSUE TITLE
Error: No such container: sealer-registry

### ISSUE THREAD

**Issue by fanux** [alibaba/sealer#497]
Check the container if already exist, then delete it

**Comment by cuisongliu** [comment]
https://github.com/alibaba/sealer/blob/fb2081bdcc77ddd4d88b1e309af86d3e5a043e27/filesystem/rootfs/docker/scripts/init-registry.sh#L41

need fix this script.

**Comment by oldthreefeng** [comment]
so we can do this.  if container is exit running or not. delete it ; otherwise run it. 

```
    if [ "$(docker ps -aq -f name=$container)" ]; then
        # cleanup
        docker rm $container -f
    fi
```
