### ISSUE TITLE
sealer install calico on calcio-system namespace ?

### ISSUE THREAD

**Issue by sfeng1996** [alibaba/sealer#507]
#### What happened:
when i use sealer to install k8s cluster, but calico is in calico-system namespace not in kube-system，and the calico image Download from the Internet(docker.io)

root@sfeng:/var/lib/sealer/data/overlay2# kubectl get pods -n calico-system
NAME                                       READY   STATUS    RESTARTS   AGE
calico-kube-controllers-5689d4dfdf-g5xcd   1/1     Running   0          72m
calico-node-dt65w                                         1/1     Running   0          72m
calico-typha-9499fc5b5-h4hdv                      1/1     Running   0          72m

Events:
  Type     Reason   Age                 From     Message
  ----     ------   ----                ----     -------
  Normal   Pulled   55m                 kubelet  Successfully pulled image "docker.io/calico/cni:v3.19.1" in 3m34.269801303s
  Warning  Failed   38m (x63 over 53m)  kubelet  Error: ImagePullBackOff
  Normal   BackOff  33m (x84 over 53m)  kubelet  Back-off pulling image "docker.io/calico/node:v3.19.1"
  Normal   Pulled   27m                 kubelet  Successfully pulled image "docker.io/calico/node:v3.19.1" in 4m19.352003181s

#### What you expected to happen:
sealer can offline install calico cni in kube-system namespace

#### Environment:
- sealer version (use `sealer version`):  v0.3.0
- Cloud provider or hardware configuration: 
- OS (e.g: `cat /etc/os-release`): 
       NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic`
- Kernel (e.g. `uname -a`):  4.15.0-152-generic
- Install tools:
- Others:

**Comment by fanux** [comment]
We will fix this issue in v0.3.3~

**Comment by SFeng-git** [comment]
> We will fix this issue in v0.3.3~

the calico in calico-system，How was it installed ？did sealer install it automatically ?

**Comment by bxy4543** [comment]
> > We will fix this issue in v0.3.3~
> 
> the calico in calico-system，How was it installed ？did sealer install it automatically ?

sealer caches the dependent image into the Cloud image when sealer build.

**Comment by SFeng-git** [comment]
> > > We will fix this issue in v0.3.3~
> > 
> > 
> > the calico in calico-system，How was it installed ？did sealer install it automatically ?
> 
> sealer caches the dependent image into the Cloud image when sealer build.

I used sealer  to deploy k8s-cluster last time, calico was not automatically installed. The same image was used. Why is calico automatically installed under calico-system this time

**Comment by fanux** [comment]
We updated the CloudImage, you can check the CloudImageID

**Comment by sfeng1996** [comment]
> We will fix this issue in v0.3.3~



> We will fix this issue in v0.3.3~

install calico to pull the image online. Have you fixed the bug? I installed it with version v0.4.0 sealer today and found that it still pulled the image online when installing calico

**Comment by bxy4543** [comment]
> > We will fix this issue in v0.3.3~
> 
> > We will fix this issue in v0.3.3~
> 
> install calico to pull the image online. Have you fixed the bug? I installed it with version v0.4.0 sealer today and found that it still pulled the image online when installing calico

sure, it pulls the image from the cache

**Comment by sfeng1996** [comment]
`Events:
  Type     Reason     Age   From               Message
  ----     ------     ----  ----               -------
  Normal   Scheduled  21s   default-scheduler  Successfully assigned calico-system/calico-node-cvgwm to sfeng
  Normal   Pulled     20s   kubelet            Container image "docker.io/calico/pod2daemon-flexvol:v3.19.1" already present on machine
  Normal   Created    20s   kubelet            Created container flexvol-driver
  Normal   Started    20s   kubelet            Started container flexvol-driver
  Normal   Pulled     19s   kubelet            Container image "docker.io/calico/cni:v3.19.1" already present on machine
  Normal   Created    19s   kubelet            Created container install-cni
  Normal   Started    19s   kubelet            Started container install-cni
  Normal   Pulled     18s   kubelet            Container image "docker.io/calico/node:v3.19.1" already present on machine
  Normal   Created    17s   kubelet            Created container calico-node
  Normal   Started    17s   kubelet            Started container calico-node
  Warning  Unhealthy  9s    kubelet            Readiness probe failed: calico/node is not ready: BIRD is not ready: Error querying BIRD: unable to connect to BIRDv4 socket: dial unix /var/run/calico/bird.ctl: connect: connection refused
`



Why check the event information and find that calico uses v3.19.1, but only v3.8.2 in registry
