### ISSUE TITLE
build container fail then find bug is delete infra NPE

### ISSUE THREAD

**Issue by hellomyboy** [alibaba/sealer#518]
#### What happened:
执行build -b container 时到最后一步会报这个错误，空指针
![image](https://user-images.githubusercontent.com/38347445/130168724-168e4cd6-a48e-45fd-9c7d-a75c621b511f.png)

#### How to reproduce it (as minimally and precisely as possible):
删除docker container
#### Environment:
- sealer version (use `sealer version`): 0.3.2
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by kakaZhou719** [comment]
@hellomyboy i will handle this issue.

**Comment by bxy4543** [comment]
$518
