### ISSUE TITLE
apply failed in E-government cloud

### ISSUE THREAD

**Issue by qqianding** [alibaba/sealer#539]
#### Question:
![error](https://user-images.githubusercontent.com/7676829/130896580-33b74e1e-b9f5-499e-b641-520d55982c7b.png)
master0:
![截屏2021-08-26 上午11 46 10](https://user-images.githubusercontent.com/7676829/130897315-e37a18b5-cff7-426a-bc9c-db2a449b9d96.png)
node0:
![截屏2021-08-26 上午11 46 19](https://user-images.githubusercontent.com/7676829/130897331-463aca15-c727-4db7-9f8d-607347f7f557.png)

#### Environment:
- sealer version (use `sealer version`): 
{"gitVersion":"v0.3.3","gitCommit":"7d87c15","buildDate":"2021-08-20 03:47:11","goVersion":"go1.14.15","compiler":"gc","platform":"linux/amd64"}
- OS (e.g: `cat /etc/os-release`):
![截屏2021-08-26 上午11 38 26](https://user-images.githubusercontent.com/7676829/130896682-3c9c886c-0c8f-4c18-8253-aa0f2b95b556.png)
- Kernel (e.g. `uname -a`): 
Linux izvy205vkg85k96l33i7lpz 3.10.0-1160.36.2.el7.x86_64 #1 SMP Wed Jul 21 11:57:15 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by justadogistaken** [comment]
@qqianding I think it might be env problem. Do you ever config proxy for the machine?
