### ISSUE TITLE
mount: special device overlay does not exist

### ISSUE THREAD

**Issue by FelixStarship** [alibaba/sealer#542]
2021-08-26 19:51:07 [EROR] [sshcmd.go:82] exec command failed Process exited with status 32
2021-08-26 19:51:07 [EROR] [apply.go:39] failed to encsure registry exec command failed 172.19.3.139 rm -rf /var/lib/sealer/tmp/upper /var/lib/sealer/tmp/work && mkdir -p /var/lib/sealer/tmp/upper /var/lib/sealer/tmp/work && mount -t overlay overlay -o lowerdir=/var/lib/sealer/data/overlay2/0e7104d47631da11b1314b76fbef7834724c56b3986683375a12fcdc8897f997:/var/lib/sealer/data/starship-cluster/rootfs/registry,upperdir=/var/lib/sealer/tmp/upper,workdir=/var/lib/sealer/tmp/work /var/lib/sealer/data/starship-cluster/rootfs/registry

**Comment by liyongcool** [comment]
I have the same problem

**Comment by bxy4543** [comment]
> I have the same problem，detail as follows
> 
> root@ubuntu01:~# sealer run registry.cn-qingdao.aliyuncs.com/sealer-apps/kubernetes:v1.19.9 -m 180.76.101.214 -n 180.76.181.216 -p N0la69587816
> 2021-09-06 08:23:56 [WARN] [current_cluster.go:51] current cluster not found, new kube build config failed: stat /root/.kube/config: no such file or directory, will create a new cluster
> 2021-09-06 08:23:56 [INFO] [default_image.go:55] image registry.cn-qingdao.aliyuncs.com/sealer-apps/kubernetes:v1.19.9 already exists
> copying files to 180.76.101.214: 0/221
> copying files to 180.76.101.214: 2/221
> copying files to 180.76.101.214: 4/221
> copying files to 180.76.101.214: 6/221
> copying files to 180.76.101.214: 16/221
> copying files to 180.76.101.214: 19/221
> copying files to 180.76.101.214: 132/221
> copying files to 180.76.101.214: 140/221
> copying files to 180.76.101.214: 142/221
> copying files to 180.76.181.216: 6/6
> copying files to 180.76.101.214: 151/221
> copying files to 180.76.181.216: 1/1
> 2021-09-06 08:25:03 [INFO] [sshcmd.go:49] [ssh][180.76.181.216] : cd /var/lib/sealer/data/my-cluster/rootfs && chmod +x scripts/* && cd scripts && bash init.sh
> 
> * storage=/var/lib/docker
> * mkdir -p /var/lib/docker
> * command_exists docker
> * command -v docker
>   copying files to 180.76.101.214: 153/221
>   copying files to 180.76.101.214: 154/221
>   ++ docker info
>   ++ grep Cg
> * cgroupDriver=' Cgroup Driver: cgroupfs
>   Cgroup Version: 1'
> * driver=1
> * echo 'driver is 1'
>   driver is 1
> * export criDriver=1
> * criDriver=1
>   modprobe: FATAL: Module nf_conntrack_ipv4 not found in directory /lib/modules/4.18.0-240.1.1.el8_3.x86_64
> 
> * Applying /usr/lib/sysctl.d/10-default-yama-scope.conf ...
>   kernel.yama.ptrace_scope = 0
> * Applying /usr/lib/sysctl.d/50-coredump.conf ...
>   kernel.core_pattern = |/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h %e
> * Applying /usr/lib/sysctl.d/50-default.conf ...
>   kernel.sysrq = 16
>   kernel.core_uses_pid = 1
>   kernel.kptr_restrict = 1
>   net.ipv4.conf.all.rp_filter = 1
>   net.ipv4.conf.all.accept_source_route = 0
>   net.ipv4.conf.all.promote_secondaries = 1
>   net.core.default_qdisc = fq_codel
>   fs.protected_hardlinks = 1
>   fs.protected_symlinks = 1
> * Applying /usr/lib/sysctl.d/50-libkcapi-optmem_max.conf ...
>   net.core.optmem_max = 81920
> * Applying /usr/lib/sysctl.d/50-pid-max.conf ...
>   kernel.pid_max = 4194304
> * Applying /etc/sysctl.d/99-kube.conf ...
>   vm.swappiness = 0
>   vm.overcommit_memory = 1
>   vm.panic_on_oom = 0
>   vm.dirty_background_ratio = 5
>   vm.dirty_ratio = 60
>   vm.max_map_count = 2097152
>   fs.file-max = 2097152
>   fs.nr_open = 2097152
>   fs.suid_dumpable = 0
>   fs.inotify.max_user_instances = 8192
>   fs.inotify.max_user_watches = 524288
>   fs.inotify.max_queued_events = 16384
>   net.core.wmem_default = 25165824
>   net.core.rmem_default = 25165824
>   net.core.wmem_max = 25165824
>   net.core.rmem_max = 25165824
>   net.ipv4.tcp_wmem = 20480 12582912 25165824
>   net.ipv4.tcp_rmem = 20480 12582912 25165824
>   net.ipv4.tcp_mem = 65536 25165824 262144
>   net.ipv4.udp_mem = 65536 25165824 262144
>   net.ipv4.udp_wmem_min = 16384
>   net.ipv4.udp_rmem_min = 16384
>   net.ipv4.tcp_window_scaling = 1
>   net.ipv4.tcp_max_syn_backlog = 10240
>   net.core.netdev_max_backlog = 65536
>   net.core.optmem_max = 25165824
>   net.ipv4.tcp_synack_retries = 2
>   net.ipv4.ip_local_port_range = 2048 65535
>   net.ipv4.tcp_rfc1337 = 1
>   net.ipv4.tcp_fin_timeout = 15
>   net.core.somaxconn = 32768
>   net.ipv4.tcp_syncookies = 1
>   net.ipv4.icmp_echo_ignore_broadcasts = 1
>   net.ipv4.icmp_ignore_bogus_error_responses = 1
>   net.ipv4.tcp_window_scaling = 1
>   net.ipv4.conf.all.log_martians = 1
>   net.ipv4.conf.default.log_martians = 1
>   net.ipv4.tcp_max_orphans = 65536
>   net.ipv4.tcp_no_metrics_save = 1
>   net.ipv4.tcp_timestamps = 1
>   net.ipv4.tcp_sack = 1
>   net.ipv4.tcp_max_tw_buckets = 14400
>   net.ipv4.tcp_tw_reuse = 1
>   net.ipv4.conf.all.accept_source_route = 0
>   net.ipv4.conf.default.accept_source_route = 0
>   net.ipv4.conf.all.rp_filter = 1
>   net.ipv4.conf.default.rp_filter = 1
>   net.ipv4.conf.all.accept_redirects = 0
>   net.ipv4.conf.default.accept_redirects = 0
>   net.ipv4.conf.all.secure_redirects = 0
>   net.ipv4.conf.default.secure_redirects = 0
>   net.ipv4.conf.all.send_redirects = 0
>   net.ipv4.conf.default.send_redirects = 0
>   net.ipv4.ip_forward = 1
>   net.ipv6.conf.lo.disable_ipv6 = 1
>   net.ipv6.conf.all.disable_ipv6 = 1
>   net.ipv6.conf.default.disable_ipv6 = 1
>   net.bridge.bridge-nf-call-ip6tables = 1
>   net.bridge.bridge-nf-call-iptables = 1
>   net.bridge.bridge-nf-call-arptables = 1
>   net.ipv4.neigh.default.gc_thresh1 = 2048
>   net.ipv4.neigh.default.gc_thresh2 = 4096
>   net.ipv4.neigh.default.gc_thresh3 = 8192
>   net.ipv4.tcp_keepalive_time = 600
>   net.ipv4.tcp_keepalive_intvl = 30
>   net.ipv4.tcp_keepalive_probes = 10
>   net.nf_conntrack_max = 1048576
>   net.netfilter.nf_conntrack_max = 1048576
>   net.netfilter.nf_conntrack_buckets = 262144
>   net.netfilter.nf_conntrack_tcp_timeout_fin_wait = 30
>   net.netfilter.nf_conntrack_tcp_timeout_time_wait = 30
>   net.netfilter.nf_conntrack_tcp_timeout_close_wait = 15
>   net.netfilter.nf_conntrack_tcp_timeout_established = 300
>   kernel.randomize_va_space = 2
>   kernel.pid_max = 65536
>   kernel.threads-max = 30938
>   kernel.core_pattern = core
>   kernel.softlockup_all_cpu_backtrace = 1
>   kernel.softlockup_panic = 1
> * Applying /etc/sysctl.d/99-sysctl.conf ...
> * Applying /etc/sysctl.d/k8s.conf ...
>   net.bridge.bridge-nf-call-ip6tables = 1
>   net.bridge.bridge-nf-call-iptables = 1
>   net.ipv4.conf.all.rp_filter = 0
> * Applying /etc/sysctl.conf ...
>   copying files to 180.76.101.214: 221/221
>   2021-09-06 08:25:48 [INFO] [sshcmd.go:49] [ssh][180.76.101.214] : cd /var/lib/sealer/data/my-cluster/rootfs  && chmod +x scripts/* && cd scripts && bash init.sh
> 
> * storage=/var/lib/docker
> * mkdir -p /var/lib/docker
> * command_exists docker
> * command -v docker
> * systemctl daemon-reload
> * systemctl restart docker.service
>   ++ grep Cg
>   ++ docker info
> * cgroupDriver=' Cgroup Driver: cgroupfs
>   Cgroup Version: 1'
> * driver=1
> * echo 'driver is 1'
>   driver is 1
> * export criDriver=1
> * criDriver=1
>   modprobe: FATAL: Module nf_conntrack_ipv4 not found in directory /lib/modules/4.18.0-240.1.1.el8_3.x86_64
> 
> * Applying /usr/lib/sysctl.d/10-default-yama-scope.conf ...
>   kernel.yama.ptrace_scope = 0
> * Applying /usr/lib/sysctl.d/50-coredump.conf ...
>   kernel.core_pattern = |/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h %e
> * Applying /usr/lib/sysctl.d/50-default.conf ...
>   kernel.sysrq = 16
>   kernel.core_uses_pid = 1
>   kernel.kptr_restrict = 1
>   net.ipv4.conf.all.rp_filter = 1
>   net.ipv4.conf.all.accept_source_route = 0
>   net.ipv4.conf.all.promote_secondaries = 1
>   net.core.default_qdisc = fq_codel
>   fs.protected_hardlinks = 1
>   fs.protected_symlinks = 1
> * Applying /usr/lib/sysctl.d/50-libkcapi-optmem_max.conf ...
>   net.core.optmem_max = 81920
> * Applying /usr/lib/sysctl.d/50-pid-max.conf ...
>   kernel.pid_max = 4194304
> * Applying /etc/sysctl.d/99-kube.conf ...
>   vm.swappiness = 0
>   vm.overcommit_memory = 1
>   vm.panic_on_oom = 0
>   vm.dirty_background_ratio = 5
>   vm.dirty_ratio = 60
>   vm.max_map_count = 2097152
>   fs.file-max = 2097152
>   fs.nr_open = 2097152
>   fs.suid_dumpable = 0
>   fs.inotify.max_user_instances = 8192
>   fs.inotify.max_user_watches = 524288
>   fs.inotify.max_queued_events = 16384
>   net.core.wmem_default = 25165824
>   net.core.rmem_default = 25165824
>   net.core.wmem_max = 25165824
>   net.core.rmem_max = 25165824
>   net.ipv4.tcp_wmem = 20480 12582912 25165824
>   net.ipv4.tcp_rmem = 20480 12582912 25165824
>   net.ipv4.tcp_mem = 65536 25165824 262144
>   net.ipv4.udp_mem = 65536 25165824 262144
>   net.ipv4.udp_wmem_min = 16384
>   net.ipv4.udp_rmem_min = 16384
>   net.ipv4.tcp_window_scaling = 1
>   net.ipv4.tcp_max_syn_backlog = 10240
>   net.core.netdev_max_backlog = 65536
>   net.core.optmem_max = 25165824
>   net.ipv4.tcp_synack_retries = 2
>   net.ipv4.ip_local_port_range = 2048 65535
>   net.ipv4.tcp_rfc1337 = 1
>   net.ipv4.tcp_fin_timeout = 15
>   net.core.somaxconn = 32768
>   net.ipv4.tcp_syncookies = 1
>   net.ipv4.icmp_echo_ignore_broadcasts = 1
>   net.ipv4.icmp_ignore_bogus_error_responses = 1
>   net.ipv4.tcp_window_scaling = 1
>   net.ipv4.conf.all.log_martians = 1
>   net.ipv4.conf.default.log_martians = 1
>   net.ipv4.tcp_max_orphans = 65536
>   net.ipv4.tcp_no_metrics_save = 1
>   net.ipv4.tcp_timestamps = 1
>   net.ipv4.tcp_sack = 1
>   net.ipv4.tcp_max_tw_buckets = 14400
>   net.ipv4.tcp_tw_reuse = 1
>   net.ipv4.conf.all.accept_source_route = 0
>   net.ipv4.conf.default.accept_source_route = 0
>   net.ipv4.conf.all.rp_filter = 1
>   net.ipv4.conf.default.rp_filter = 1
>   net.ipv4.conf.all.accept_redirects = 0
>   net.ipv4.conf.default.accept_redirects = 0
>   net.ipv4.conf.all.secure_redirects = 0
>   net.ipv4.conf.default.secure_redirects = 0
>   net.ipv4.conf.all.send_redirects = 0
>   net.ipv4.conf.default.send_redirects = 0
>   net.ipv4.ip_forward = 1
>   net.ipv6.conf.lo.disable_ipv6 = 1
>   net.ipv6.conf.all.disable_ipv6 = 1
>   net.ipv6.conf.default.disable_ipv6 = 1
>   net.bridge.bridge-nf-call-ip6tables = 1
>   net.bridge.bridge-nf-call-iptables = 1
>   net.bridge.bridge-nf-call-arptables = 1
>   net.ipv4.neigh.default.gc_thresh1 = 2048
>   net.ipv4.neigh.default.gc_thresh2 = 4096
>   net.ipv4.neigh.default.gc_thresh3 = 8192
>   net.ipv4.tcp_keepalive_time = 600
>   net.ipv4.tcp_keepalive_intvl = 30
>   net.ipv4.tcp_keepalive_probes = 10
>   net.nf_conntrack_max = 1048576
>   net.netfilter.nf_conntrack_max = 1048576
>   net.netfilter.nf_conntrack_buckets = 262144
>   net.netfilter.nf_conntrack_tcp_timeout_fin_wait = 30
>   net.netfilter.nf_conntrack_tcp_timeout_time_wait = 30
>   net.netfilter.nf_conntrack_tcp_timeout_close_wait = 15
>   net.netfilter.nf_conntrack_tcp_timeout_established = 300
>   kernel.randomize_va_space = 2
>   kernel.pid_max = 65536
>   kernel.threads-max = 30938
>   kernel.core_pattern = core
>   kernel.softlockup_all_cpu_backtrace = 1
>   kernel.softlockup_panic = 1
> * Applying /etc/sysctl.d/99-sysctl.conf ...
> * Applying /etc/sysctl.d/k8s.conf ...
>   net.bridge.bridge-nf-call-ip6tables = 1
>   net.bridge.bridge-nf-call-iptables = 1
>   net.ipv4.conf.all.rp_filter = 0
> * Applying /etc/sysctl.conf ...
>   net.ipv4.ip_forward = 1
>   2021-09-06 08:25:50 [INFO] [runtime.go:105] metadata version v1.19.8
>   2021-09-06 08:25:50 [INFO] [sshcmd.go:49] [ssh][180.76.101.214] : cd /var/lib/sealer/data/my-cluster/rootfs && echo "
>   apiVersion: kubeadm.k8s.io/v1beta1
>   kind: ClusterConfiguration
>   kubernetesVersion: v1.19.8
>   controlPlaneEndpoint: "apiserver.cluster.local:6443"
>   imageRepository: sea.hub:5000/library
>   networking:
>   # dnsDomain: cluster.local
>   podSubnet: 100.64.0.0/10
>   serviceSubnet: 10.96.0.0/22
>   apiServer:
>   certSANs:
>   
>   * 127.0.0.1
>   * apiserver.cluster.local
>   * 180.76.101.214
>   * aliyun-inc.com
>   * 10.0.0.2
>   * 10.103.97.2
>     extraArgs:
>     etcd-servers: https://180.76.101.214:2379
>     feature-gates: TTLAfterFinished=true,EphemeralContainers=true
>     audit-policy-file: "/etc/kubernetes/audit-policy.yml"
>     audit-log-path: "/var/log/kubernetes/audit.log"
>     audit-log-format: json
>     audit-log-maxbackup: '"10"'
>     audit-log-maxsize: '"100"'
>     audit-log-maxage: '"7"'
>     enable-aggregator-routing: '"true"'
>     extraVolumes:
>   * name: "audit"
>     hostPath: "/etc/kubernetes"
>     mountPath: "/etc/kubernetes"
>     pathType: DirectoryOrCreate
>   * name: "audit-log"
>     hostPath: "/var/log/kubernetes"
>     mountPath: "/var/log/kubernetes"
>     pathType: DirectoryOrCreate
>   * name: localtime
>     hostPath: /etc/localtime
>     mountPath: /etc/localtime
>     readOnly: true
>     pathType: File
>     controllerManager:
>     extraArgs:
>     feature-gates: TTLAfterFinished=true,EphemeralContainers=true
>     experimental-cluster-signing-duration: 876000h
>     extraVolumes:
>   * hostPath: /etc/localtime
>     mountPath: /etc/localtime
>     name: localtime
>     readOnly: true
>     pathType: File
>     scheduler:
>     extraArgs:
>     feature-gates: TTLAfterFinished=true,EphemeralContainers=true
>     extraVolumes:
>   * hostPath: /etc/localtime
>     mountPath: /etc/localtime
>     name: localtime
>     readOnly: true
>     pathType: File
>     etcd:
>     local:
>     extraArgs:
>     listen-metrics-urls: http://0.0.0.0:2381
> 
> apiVersion: kubeproxy.config.k8s.io/v1alpha1
> kind: KubeProxyConfiguration
> mode: "ipvs"
> ipvs:
> excludeCIDRs:
> 
> * "10.103.97.2/32"" > kubeadm-config.yaml
>   2021-09-06 08:25:51 [INFO] [kube_certs.go:234] APIserver altNames :  {map[aliyun-inc.com:aliyun-inc.com apiserver.cluster.local:apiserver.cluster.local k8s-master-node1:k8s-master-node1 kubernetes:kubernetes kubernetes.default:kubernetes.default kubernetes.default.svc:kubernetes.default.svc kubernetes.default.svc.cluster.local:kubernetes.default.svc.cluster.local localhost:localhost] map[10.0.0.2:10.0.0.2 10.103.97.2:10.103.97.2 10.96.0.1:10.96.0.1 127.0.0.1:127.0.0.1 180.76.101.214:180.76.101.214]}
>   2021-09-06 08:25:51 [INFO] [kube_certs.go:254] Etcd altnames : {map[k8s-master-node1:k8s-master-node1 localhost:localhost] map[127.0.0.1:127.0.0.1 180.76.101.214:180.76.101.214 ::1:::1]}, commonName : k8s-master-node1
>   2021-09-06 08:25:51 [INFO] [kube_certs.go:262] sa.key sa.pub already exist
>   copying files to 180.76.101.214: 22/22
>   2021-09-06 08:26:05 [INFO] [kubeconfig.go:277] [kubeconfig] Using existing kubeconfig file: "/var/lib/sealer/data/my-cluster/admin.conf"
> 
> 2021-09-06 08:26:05 [INFO] [kubeconfig.go:277] [kubeconfig] Using existing kubeconfig file: "/var/lib/sealer/data/my-cluster/controller-manager.conf"
> 
> 2021-09-06 08:26:06 [INFO] [kubeconfig.go:277] [kubeconfig] Using existing kubeconfig file: "/var/lib/sealer/data/my-cluster/scheduler.conf"
> 
> 2021-09-06 08:26:06 [INFO] [kubeconfig.go:277] [kubeconfig] Using existing kubeconfig file: "/var/lib/sealer/data/my-cluster/kubelet.conf"
> 
> 2021-09-06 08:26:06 [INFO] [sshcmd.go:49] [ssh][180.76.101.214] : mkdir -p /etc/kubernetes && cp -f /var/lib/sealer/data/my-cluster/rootfs/statics/audit-policy.yml /etc/kubernetes/audit-policy.yml
> 2021-09-06 08:26:06 [INFO] [sshcmd.go:49] [ssh][180.76.101.214] : rm -rf /var/lib/sealer/tmp/upper /var/lib/sealer/tmp/work && mkdir -p /var/lib/sealer/tmp/upper /var/lib/sealer/tmp/work && mount -t overlay overlay -o lowerdir=/var/lib/sealer/data/overlay2/156a78d174d4d3f950f15f58d93aaeb2338d48462a380e2e83931c1b83463104:/var/lib/sealer/data/my-cluster/rootfs/registry,upperdir=/var/lib/sealer/tmp/upper,workdir=/var/lib/sealer/tmp/work /var/lib/sealer/data/my-cluster/rootfs/registry
> mount: /var/lib/sealer/data/my-cluster/rootfs/registry: special device overlay does not exist.
> 2021-09-06 08:26:06 [EROR] [sshcmd.go:82] exec command failed Process exited with status 32
> 2021-09-06 08:26:06 [EROR] [run.go:55] failed to encsure registry exec command failed 180.76.101.214 rm -rf /var/lib/sealer/tmp/upper /var/lib/sealer/tmp/work && mkdir -p /var/lib/sealer/tmp/upper /var/lib/sealer/tmp/work && mount -t overlay overlay -o lowerdir=/var/lib/sealer/data/overlay2/156a78d174d4d3f950f15f58d93aaeb2338d48462a380e2e83931c1b83463104:/var/lib/sealer/data/my-cluster/rootfs/registry,upperdir=/var/lib/sealer/tmp/upper,workdir=/var/lib/sealer/tmp/work /var/lib/sealer/data/my-cluster/rootfs/registry



This problem appears to be caused by the fact that a layer of the image directory does not exist.
What is the registry.cn-qingdao.aliyuncs.com/sealer-apps/kubernetes:v1.19.9 imageID on 180.76.101.214 nodes? View it at this node using the 'sealer images' command.

**Comment by yj-cloud** [comment]
@bxy4543 @fanux  同类型问题。 版本 0.4.0
**Kubefile：**
```
FROM kubernetes:v1.19.9
COPY ./charts/nginx ./charts/nginx 
```

**部署环境：**
命令部署节点：172.30.11.90（非集群节点）
master：172.30.10.36  （**新节点，初始无任何镜像**）
```
# sealer apply -f Clusterfile
....省略都是INFO日志
mount: special device overlay does not exist
2021-09-08 15:52:51 [EROR] [sshcmd.go:82] exec command failed Process exited with status 32
2021-09-08 15:52:51 [EROR] [apply.go:39] failed to encsure registry exec command failed 172.30.10.36 rm -rf /var/lib/sealer/tmp/upper /var/lib/sealer/tmp/work && mkdir -p /var/lib/sealer/tmp/upper /var/lib/sealer/tmp/work && mount -t overlay overlay -o lowerdir=/var/lib/sealer/data/overlay2/3f7f5dd542cdc90284203a329868fc35879ed6c6581eb7952e7b3e5008d750cf:/var/lib/sealer/data/my-cluster/rootfs/registry,upperdir=/var/lib/sealer/tmp/upper,workdir=/var/lib/sealer/tmp/work /var/lib/sealer/data/my-cluster/rootfs/registry

# 去 172.30.10.36  集群master节点查看发现无 /var/lib/sealer/data/overlay2/3f7f5dd542cdc90284203a329868fc35879ed6c6581eb7952e7b3e5008d750cf 目录

#在命令部署节点上执行
# sealer inspect my-kubernetes:v1.19.9
... 
spec:
  id: 92976f73e8cb84ee53e7f04e98e42de6553ece676cad0e792e21acc2363bff3c
  layers:
  - id: sha256:b6eb4360ad3ffe577c04d53205d0efc71dd59caef47bc5899230b291f292f593
    type: COPY
    value: . .
  - type: CMD
    value: kubectl apply -f etc/tigera-operator.yaml
  - type: CMD
    value: kubectl apply -f etc/custom-resources.yaml
   ....
  - id: sha256:3f7f5dd542cdc90284203a329868fc35879ed6c6581eb7952e7b3e5008d750cf
    type: BASE
    value: registry cache

# 以上看到 3f7f5dd542cdc90284203a329868fc35879ed6c6581eb7952e7b3e5008d750cf 为 BASE
# 且命令部署节点上有目录/var/lib/sealer/data/overlay2/3f7f5dd542cdc90284203a329868fc35879ed6c6581eb7952e7b3e5008d750cf

# 在172.30.10.36  集群master节点先手动 sealer pull my-kubernetes:v1.19.9 。重新部署可成功。
```

在新的节点上部署几次集群都是同样问题

**Comment by bxy4543** [comment]
> @bxy4543 @fanux 同类型问题。 版本 0.4.0
> **Kubefile：**
> 
> ```
> FROM kubernetes:v1.19.9
> COPY ./charts/nginx ./charts/nginx 
> ```
> 
> 使用 `sealer build -b lite -t xxx .`
> **部署环境：**
> 命令部署节点：172.30.11.90（非集群节点）
> master：172.30.10.36 （**新节点，初始无任何镜像**）
> 
> ```
> # sealer apply -f Clusterfile
> ....省略都是INFO日志
> mount: special device overlay does not exist
> 2021-09-08 15:52:51 [EROR] [sshcmd.go:82] exec command failed Process exited with status 32
> 2021-09-08 15:52:51 [EROR] [apply.go:39] failed to encsure registry exec command failed 172.30.10.36 rm -rf /var/lib/sealer/tmp/upper /var/lib/sealer/tmp/work && mkdir -p /var/lib/sealer/tmp/upper /var/lib/sealer/tmp/work && mount -t overlay overlay -o lowerdir=/var/lib/sealer/data/overlay2/3f7f5dd542cdc90284203a329868fc35879ed6c6581eb7952e7b3e5008d750cf:/var/lib/sealer/data/my-cluster/rootfs/registry,upperdir=/var/lib/sealer/tmp/upper,workdir=/var/lib/sealer/tmp/work /var/lib/sealer/data/my-cluster/rootfs/registry
> 
> # 去 172.30.10.36  集群master节点查看发现无 /var/lib/sealer/data/overlay2/3f7f5dd542cdc90284203a329868fc35879ed6c6581eb7952e7b3e5008d750cf 目录
> 
> #在命令部署节点上执行
> # sealer inspect my-kubernetes:v1.19.9
> ... 
> spec:
>   id: 92976f73e8cb84ee53e7f04e98e42de6553ece676cad0e792e21acc2363bff3c
>   layers:
>   - id: sha256:b6eb4360ad3ffe577c04d53205d0efc71dd59caef47bc5899230b291f292f593
>     type: COPY
>     value: . .
>   - type: CMD
>     value: kubectl apply -f etc/tigera-operator.yaml
>   - type: CMD
>     value: kubectl apply -f etc/custom-resources.yaml
>    ....
>   - id: sha256:3f7f5dd542cdc90284203a329868fc35879ed6c6581eb7952e7b3e5008d750cf
>     type: BASE
>     value: registry cache
> 
> # 以上看到 3f7f5dd542cdc90284203a329868fc35879ed6c6581eb7952e7b3e5008d750cf 为 BASE
> # 且命令部署节点上有目录/var/lib/sealer/data/overlay2/3f7f5dd542cdc90284203a329868fc35879ed6c6581eb7952e7b3e5008d750cf
> 
> # 在172.30.10.36  集群master节点先手动 sealer pull my-kubernetes:v1.19.9 。重新部署可成功。
> ```
> 
> 在新的节点上部署几次集群都是同样问题，需要手动 `sealer pull` 集群镜像到节点

Show me your Clusterfile

**Comment by yj-cloud** [comment]
Clusterfile
```
apiVersion: sealer.aliyun.com/v1alpha1
kind: Cluster
metadata:
  name: my-cluster
spec:
  image: xxx/xx/my-kubernetes:v1.19.9
  provider: BAREMETAL
  ssh:
    # SSH login password, if you use the key to log in, you don’t need to set it
    passwd: xxxx
    ## The absolute path of the ssh private key file, for example /root/.ssh/id_rsa
    pk: ""
    #  The password of the ssh private key file, if there is none, set it to ""
    pkPasswd: ""
    # ssh login user
    user: root
  network:
    # in use NIC name
    interface: eth0
    # Network plug-in name
    cniName: calico
    podCIDR: 100.64.0.0/10
    svcCIDR: 10.80.128.0/18
    withoutCNI: false
  certSANS:
    - 172.30.10.36

  masters:
    ipList:
     - 172.30.10.36
```

**Comment by fanux** [comment]
What is your system version? Dose it support overlay2 storage driver?

**Comment by yj-cloud** [comment]
> What is your system version? Dose it support overlay2 storage driver?
```
# cat /etc/centos-release
CentOS Linux release 7.8.2003 (Core)
# uname -r
3.10.0-1127.el7.x86_64
# modprobe overlay
# echo $?
0
# cat /proc/filesystems
nodev   sysfs
nodev   rootfs
nodev   ramfs
nodev   bdev
nodev   proc
nodev   cgroup
nodev   cpuset
nodev   tmpfs
nodev   devtmpfs
nodev   debugfs
nodev   securityfs
nodev   sockfs
nodev   dax
nodev   bpf
nodev   pipefs
nodev   configfs
nodev   devpts
nodev   hugetlbfs
nodev   autofs
nodev   pstore
nodev   mqueue
        xfs
        iso9660
nodev   overlay
nodev   binfmt_misc
```

**Comment by oldthreefeng** [comment]
@yj-cloud  https://github.com/fanux/sealos/issues/582#issuecomment-797293696 , 
if your systems do dot support overlay2 storage driver, you can just choose others.

**Comment by fanux** [comment]
> @yj-cloud [fanux/sealos#582 (comment)](https://github.com/fanux/sealos/issues/582#issuecomment-797293696) ,
> if your systems do dot support overlay2 storage driver, you can just choose others.

Maybe can't..  because the sealer CloudImage using overlay2 too...

**Comment by bxy4543** [comment]
> > @yj-cloud [fanux/sealos#582 (comment)](https://github.com/fanux/sealos/issues/582#issuecomment-797293696) ,
> > if your systems do dot support overlay2 storage driver, you can just choose others.
> 
> Maybe can't.. because the sealer CloudImage using overlay2 too...

I found this problem, this is another problem, and I'll try to fix it

**Comment by bxy4543** [comment]
you can temporarily fix this problem by executing the `sealer pull Image` on the master0 node.
