### ISSUE TITLE
需求

### ISSUE THREAD

**Issue by bryant-rh** [alibaba/sealer#544]
佳华物联云：
1.希望支持集群节点arm+amd混合的情况，因为有GPU+arm机器的场景
2.支持k3s，有些资源紧张的机器需要部署k3s
3.能否提供一份基础rootfs，用户可以自己编译基础镜像，且支持双架构
4.支持k8s升级
5.支持containerd

**Comment by fanux** [comment]
https://github.com/alibaba/sealer/issues/479
