### ISSUE TITLE
the Makefile in macos is invalid

### ISSUE THREAD

**Issue by DawnGuoDev** [alibaba/sealer#549]
#### What happened:
When I run `make license` in macos, there is no license added to my code.  

#### What you expected to happen:
`make license` can run successfully in macos, because develop sealer may not on Linux.

#### How to reproduce it (as minimally and precisely as possible):
`make license` in macos.
![image](https://user-images.githubusercontent.com/28643623/131238092-4d5041d7-8e7c-4532-adfb-ef80ce3e33c8.png)

#### Anything else we need to know?:
When I change the license rule to add-license, it's OK.

**Comment by ysicing** [comment]
@DawnGuoDev maybe makefile target `license` with the same name as LICENSE, rename `license` target to `filelicense`

**Comment by DawnGuoDev** [comment]
@ysicing  Yeah, I change the license rule to add-license, and it's OK.
