### ISSUE TITLE
应用镜像还是需要在线拉取

### ISSUE THREAD

**Issue by sfeng1996** [alibaba/sealer#552]
应用镜像能够制作到集群镜像里，目前测试sealer只是将对应的应用yaml文件拷到集群镜像里，然而应用的镜像还是需要去应用的镜像仓库去拉取

**Comment by fanux** [comment]
Show your build command and your Kubefile.

**Comment by sfeng1996** [comment]
> Show your build command and your Kubefile.
Kubefile:
`FROM harbor.sfeng.com/sfeng/kubernetes-withcalico:v1.19.9
COPY nacos-store-pv0-pvc0.yaml manifests
COPY nacos-statefulset.yaml manifests
RUN kubectl create ns public-service
RUN kubectl apply -f manifests/nacos-store-pv0-pvc0.yaml
RUN kubectl apply -f manifests/nacos-statefulset.yaml
`

build command:
sealer build -b lite -t harbor.sfeng.com/sfeng/k8s-nacos:v1.0 .

**Comment by fanux** [comment]
@bxy4543 lite build support cache docker image now?

**Comment by bxy4543** [comment]
sealer version 0.4.0  fixes this issue
