### ISSUE TITLE
Make sealer path configurable

### ISSUE THREAD

**Issue by Jeffwan** [alibaba/sealer#566]
#### What happened:
```
[ec2-user@ip-172-31-52-221 ~]$ sealer
panic: failed to mkdir /var/lib/sealer/tmp, err: mkdir /var/lib/sealer: permission denied

goroutine 1 [running]:
main.main()
	/home/runner/work/sealer/sealer/src/github.com/alibaba/sealer/sealer/main.go:25 +0x4a
```

#### What you expected to happen:

I would like sealer to ask me to pass configuration path.

#### How to reproduce it (as minimally and precisely as possible):
Just install 0.4.0 sealer and run sealer

#### Environment:
- sealer version (use `sealer version`): 0.4.0
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by fanux** [comment]
sealer only support root user now, because we need to open some kernel modules and write some files like /etc/hosts ...
