### ISSUE TITLE
一些使用问题

### ISSUE THREAD

**Issue by jxhsjxhs** [alibaba/sealer#568]
1. 不太理解RPM包或者预置脚本应该咋处理。
2. Kubefile更详细的使用方法。

**Comment by fanux** [comment]
https://github.com/alibaba/sealer/tree/main/applications/yrcloudfile

**Comment by fanux** [comment]
Kubefile only has few commands FROM COPY RUN CMD, If you need to run user-defined script, using sealer shell plugin is a good choise:  https://github.com/alibaba/sealer/blob/main/docs/design/plugin.md#shell-plugin
