### ISSUE TITLE
sealer build on docker, failed to register layer

### ISSUE THREAD

**Issue by yj-cloud** [alibaba/sealer#573]
#### What happened:
尝试在容器内使用 `sealer build -b lite` 构建镜像。
```
[root@ecs6ejzdybkpr sealer]# docker run -it -v /var/lib/sealer:/var/lib/sealer -v /usr/bin/sealer:/usr/bin/sealer -v /root/sealer:/root/workspace -v /var/run/docker.sock:/var/run/docker.sock centos:7
[root@372c76d68f08 /]# cd /root/workspace/
[root@372c76d68f08 workspace]# ls
Kubefile  bin  charts
[root@372c76d68f08 workspace]# sealer build -b lite -t new-kubernetes:v1.1.9.9 .
...
...
2021-09-07 06:45:26 [EROR] [build.go:57] failed to register layer, err: unable to tar on /var/lib/sealer/data/my-cluster/mount/upper, err: dir /var/lib/sealer/data/my-cluster/mount/upper does not exist, err: stat /var/lib/sealer/data/my-cluster/mount/upper: no such file or directory
```

报错代码定位：
https://github.com/alibaba/sealer/blob/main/build/lite_builder.go#L153
https://github.com/alibaba/sealer/blob/main/utils/mount/default.go#L33
在 liteBuilder AddUpperLayerToImage 里，先执行了 Unmount 导致 `/var/lib/sealer/data/my-cluster/mount` 目录被删除，删除操作执行代码为 https://github.com/alibaba/sealer/blob/main/utils/mount/default.go#L33

#### Environment:
- sealer version (use `sealer version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by bxy4543** [comment]
overlay mounts all layers to a folder. The upper layer appears after overlay umount. Run the 'modprobe overlay' command to check whether overlay mount is supported.

**Comment by bxy4543** [comment]
overlay mounts all layers to a folder. The upper layer appears after overlay umount. 
I found this problem. Because of insufficient permissions, overlay was not used to mount the container, and privileges needed to be added to the container using '--privileged=true'.
Use:
` ` `
docker run -it  --privileged=true -v /var/lib/sealer:/var/lib/sealer -v /usr/bin/sealer:/usr/bin/sealer -v  /root/sealer:/root/workspace -v /var/run/docker.sock:/var/run/docker.sock centos:7
` ` `

**Comment by yj-cloud** [comment]
> overlay mounts all layers to a folder. The upper layer appears after overlay umount.
> I found this problem. Because of insufficient permissions, overlay was not used to mount the container, and privileges needed to be added to the container using '--privileged=true'.
> Use:
> ` ` `docker run -it --privileged=true -v /var/lib/sealer:/var/lib/sealer -v /usr/bin/sealer:/usr/bin/sealer -v /root/sealer:/root/workspace -v /var/run/docker.sock:/var/run/docker.sock centos:7` ` `

特权模式跑，还是不行呀

**Comment by bxy4543** [comment]
> > overlay mounts all layers to a folder. The upper layer appears after overlay umount.
> > I found this problem. Because of insufficient permissions, overlay was not used to mount the container, and privileges needed to be added to the container using '--privileged=true'.
> > Use:
> > ` ` `docker run -it --privileged=true -v /var/lib/sealer:/var/lib/sealer -v /usr/bin/sealer:/usr/bin/sealer -v /root/sealer:/root/workspace -v /var/run/docker.sock:/var/run/docker.sock centos:7` ` `
> 
> 特权模式跑，还是不行呀。一样的问题
> @bxy4543 可以把这个 unmount 放在最后吗？https://github.com/alibaba/sealer/blob/main/build/lite_builder.go#L138

Is the same error when using '--privileged=true'?

**Comment by jelly320** [comment]
@bxy4543 @yj-cloud 最后是怎么解决的呀~
