### ISSUE TITLE
need to delete Clusterfile when run sealer delete

### ISSUE THREAD

**Issue by kakaZhou719** [alibaba/sealer#58]
#### What happened:
run sealer delete -f /tmp/Clusterfile 
delete cluster : ok
 /tmp/Clusterfile :  still exists

#### What you expected to happen:

i think our delete cmd reconcile the cluster while the clusterfile specified was also need to be deleted
 
#### Environment:
- sealer version (use `sealer version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by fanux** [comment]
I think this is a temp file  we can delete it after apply or build. the state of cluster is in ~/.sealer/<cluster-name>/Clusterfile

**Comment by bxy4543** [comment]
fix #80
