### ISSUE TITLE
Fix markdown lint

### ISSUE THREAD

**Issue by fanux** [alibaba/sealer#585]
markdownlint not access now: https://github.com/alibaba/sealer/actions/runs/1220419777

check markdown locally:
```
$ docker run --rm \
    -v "$(pwd)/CHANGELOG.md:/CHANGELOG.md:ro" \
    avtodev/markdown-lint:v1 \
    --rules /lint/rules/changelog.js \
    --config /lint/config/changelog.yml \
    /CHANGELOG.md
```

More informations:
```
 https://github.com/marketplace/actions/markdown-linting-action 
```

**Comment by allencloud** [comment]
I am afraid that I have corrected all the markdown issue. I think we could close this. While please feel free to re-open it if needed.
