### ISSUE TITLE
load metadata failed,please check image Metadata unexpected end of JSON input

### ISSUE THREAD

**Issue by wangjxian** [alibaba/sealer#589]
执行示例的Clusterfile 

sealer apply -f Clusterfile 
会出现 这个错误。

demo里提供的这个镜像 
registry.cn-qingdao.aliyuncs.com/sealer-io/kubernetes:v1.19.9

**Comment by huyunhaode** [comment]
Can you provide the Clusterfile you use? What version of sealer are you using?

**Comment by bxy4543** [comment]
Use the latest sealer version.
