### ISSUE TITLE
Potential bug: Implicit memory aliasing in for loop. (reported by gosec)

### ISSUE THREAD

**Issue by allencloud** [alibaba/sealer#596]
#### What happened:

I executed https://github.com/securego/gosec for project sealer, and found that several issue thrown:

```
utils/iputils.go:120:29: G601: Implicit memory aliasing in for loop. (gosec)
			if err := AssemblyIPList(&i); err != nil {
			                         ^
build/lite/docker/images.go:48:23: G601: Implicit memory aliasing in for loop. (gosec)
		List = append(List, &image)
		                    ^
```

The warning `Implicit memory aliasing in for loop` means, in short, that you are taking the address of a loop variable.

This happens because in for statements the iteration variable(s) is reused. At each iteration, the value of the next element in the range expression is assigned to the iteration variable; v doesn't change, only its value changes. Hence, the expression &v is referring to the same location in memory.

The following code prints the same memory address four times:
```
for _, n := range []int{1, 2, 3, 4} {
    fmt.Printf("%p\n", &n)
}
```

And the detailed potential bugs are located in following places:
```
func DisassembleIPList(arg string) (res []string) {
	ipList := strings.Split(arg, ",")
	for _, i := range ipList {
		if strings.Contains(i, "-") {
			if err := AssemblyIPList(&i); err != nil {
				fmt.Printf("failed to get Addrs, %s", err.Error())
				continue
			}
			res = append(res, strings.Split(i, ",")...)
		}
		res = append(res, i)
	}
	return
}
```

```
func (d Docker) ImagesList() ([]*types.ImageSummary, error) {
	var List []*types.ImageSummary
	ctx := context.Background()
	cli, err := client.NewClientWithOpts(client.FromEnv, client.WithAPIVersionNegotiation())
	if err != nil {
		return nil, err
	}
	images, err := cli.ImageList(ctx, types.ImageListOptions{})
	if err != nil {
		return nil, err
	}
	for _, image := range images {
		List = append(List, &image)
	}
	return List, nil
}
```

#### Environment:
- sealer version (use `sealer version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by kakaZhou719** [comment]
we will add gosec for sealer github action, and will use it to do a full check.
issue #810
