### ISSUE TITLE
Sealer login failed to private docker registry with https

### ISSUE THREAD

**Issue by jkryanchou** [alibaba/sealer#600]
#### What happened:

I have tried `sealer login`  to our company's private docker-registry which built on Harbor  as below 

```
sealer login registry.starx.com -uadmin -pHarbor12345
```

While it failed with the errors:

```
2021-09-15 13:23:48 [EROR] [default_image.go:165] registry.starx.com authentication failed
2021-09-15 13:23:48 [EROR] [login.go:51] Get "https://registry.starx.com/v2/": x509: certificate signed by unknown authority
```

#### What you expected to happen:

I did the same login-attempt through docker-client and it succeed without any errors

```
[root@localhost sealer-examples]# docker login registry.starx.com -uadmin -pHarbor12345
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
WARNING! Your password will be stored unencrypted in /root/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
```

#### Environment:
- sealer version (use `sealer version`): {"gitVersion":"v0.4.0","gitCommit":"7341634","buildDate":"2021-08-31 10:45:26","goVersion":"go1.14.15","compiler":"gc","platform":"linux/amd64"}
- Cloud provider or hardware configuration: 
- OS (e.g: `cat /etc/os-release`):
  ```
   NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
  ```
- Kernel (e.g. `uname -a`): Linux localhost.localdomain 3.10.0-1127.el7.x86_64 #1 SMP Tue Mar 31 23:36:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: 
- Others:
   
   * My docker daemon configuration (`cat /etc/docker/daemon.json`) 
   
  ```
      {
          ... ...
          "insecure-registries": ["registry.starx.com"]
      }
   ```

**Comment by jkryanchou** [comment]
Got

**Comment by fanux** [comment]
@jkryanchou If the PR fixed the bug, close this issue~

**Comment by jkryanchou** [comment]
@fanux Got it. I would try it later.  pretty awesome.

**Comment by bxy4543** [comment]
#618 Use sealer v0.5.0 and set the environment variable `skip_ TLS_ Verify = true` to skip x509 errors.
