### ISSUE TITLE
[gosec] we should not use weak random number generator

### ISSUE THREAD

**Issue by allencloud** [alibaba/sealer#608]
#### What happened:

When we apply gosec and several enhancement should be made, for example G404: Use of weak random number generator (math/rand instead of crypto/rand) .

```
infra/aliyun/ali_ecs.go:117:18: G404: Use of weak random number generator (math/rand instead of crypto/rand) (gosec)
	buf[0] = digits[rand.Intn(len(digits))]
	                ^
infra/aliyun/ali_ecs.go:118:20: G404: Use of weak random number generator (math/rand instead of crypto/rand) (gosec)
	buf[1] = specials[rand.Intn(len(specials))]
	                  ^
infra/aliyun/ali_ecs.go:120:16: G404: Use of weak random number generator (math/rand instead of crypto/rand) (gosec)
		buf[i] = all[rand.Intn(len(all))]
```

#### What you expected to happen:

We wish to update this to use string random number generator.

#### How to reproduce it (as minimally and precisely as possible):
none

#### Anything else we need to know?:
none

#### Environment:
- sealer version (use `sealer version`): master
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by steve-fei** [comment]
resolved！
