### ISSUE TITLE
[unconvert] unnecessary conversion in golang usage

### ISSUE THREAD

**Issue by allencloud** [alibaba/sealer#609]
#### What happened:

when we apply golangci-lint with unconvert rule, it throws the error following:

```
utils/cidr.go:82:22: unnecessary conversion (unconvert)
	return net.IP([]byte(mask)).String()
```

#### What you expected to happen:

we wish that no uncovert cases happened in sealer

#### How to reproduce it (as minimally and precisely as possible):
none

#### Anything else we need to know?:
none

#### Environment:
- sealer version (use `sealer version`):  main branch 
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by fanux** [comment]
just `net.IP([]byte(mask)).String() => net.IP(mask).String()`

**Comment by Wusuluren** [comment]
I can fix it
