### ISSUE TITLE
Lite mode image cache failed!

### ISSUE THREAD

**Issue by myxxhui** [alibaba/sealer#622]
![image](https://user-images.githubusercontent.com/69575321/133746861-ec3d1895-c824-4d6f-9a9c-368d243aae2d.png)
![Uploading image.png…]()

#### What happened:
build 看起来是好的，但是镜像拉不下来
#### Environment:
- sealer version (use `sealer version`):0.4.0
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):Linux 192.168.1.188 3.10.0-1160.31.1.el7.x86_64 #1 SMP Thu Jun 10 13:32:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Others:

**Comment by kakaZhou719** [comment]
hi，@myxxhui,
could your pls provide below info for us?

- 1, your kubefile ? if use `copy imageList` ,pls provide it at the same time.
- 2, `docker info` output.
- 3, `cat /etc/docker/daemon.json ` output.
- 4, build logs.

**Comment by kakaZhou719** [comment]
hi @myxxhui,
as my investigation (grep docker /var/log/messages ), seems its too quick to pull images, while the registry cannot serve port 5000 for caching. i will fix this bug in next sealer version.

**Comment by kakaZhou719** [comment]
![image](https://user-images.githubusercontent.com/83740799/134324461-602d7e5e-1876-4ebb-85d4-c8b25738647d.png)
