### ISSUE TITLE
需要协助，没有视频教程不会使用啊

### ISSUE THREAD

**Issue by dafu999** [alibaba/sealer#626]
QQ27715744

## Issue Description

Type: *feature request*

**Comment by kakaZhou719** [comment]
could you pls provide more details ? our doc is here :https://github.com/alibaba/sealer/tree/main/docs

**Comment by fanux** [comment]
https://github.com/alibaba/sealer/blob/main/docs/user-guide/get-started.md

**Comment by fanux** [comment]
website is on the way~
