### ISSUE TITLE
不支持ssh端口修改

### ISSUE THREAD

**Issue by 46797536** [alibaba/sealer#627]
![image](https://user-images.githubusercontent.com/46241382/133871193-ada5e555-05d8-4345-a343-c74d99b74f51.png)

**Comment by lllwan** [comment]
Sealer supports custom SSH ports. You can refer to the following examples:
`apiVersion: zlink.aliyun.com/v1alpha1
kind: Cluster
metadata:
  annotations:
    ClusterfileName: Clusterfile
  creationTimestamp: null
  name: prod-jiangxi
spec:
  certSANS:
  - cai-inc.com
  - 10.0.0.1
  image: zcy-kubernetes:v1.19.9
  masters:
    ipList:
    - 10.1.1.1:2022
    - 10.1.1.2:2022
    - 10.1.1.3:2022
  network:
    podCIDR: 10.10.64.0/20
    svcCIDR: 10.10.48.0/20
  nodes:
    ipList:
    - 10.1.1.6:2022
    - 10.1.1.7:2022
    - 10.1.1.8:2022`

**Comment by fanux** [comment]
@lllwan you sealer version is?

**Comment by 46797536** [comment]
改成22端口
![image](https://user-images.githubusercontent.com/46241382/133872224-38a7b20d-1a69-4c9f-9230-16f44a596b6b.png)
执行sealer delete -f /root/.sealer/mycluster/Clusterfile
后问题依然存在

**Comment by 46797536** [comment]
![image](https://user-images.githubusercontent.com/46241382/133878034-c6199c86-6407-4f8a-9afe-581672726578.png)
第一次安装会启动docker，第二次就找不到文件

**Comment by bxy4543** [comment]
> ![image](https://user-images.githubusercontent.com/46241382/133878034-c6199c86-6407-4f8a-9afe-581672726578.png)
> 第一次安装会启动docker，第二次就找不到文件

Describe the behavior. For example: Was the first installation successful? Did you execute any other commands after the first installation? Show the /var/lib/sealer/my-cluster/rootfs directory

**Comment by lllwan** [comment]
> @lllwan you sealer version is?
It is certain that there will be problems in versions before 4.0, which has been fixed in #593 . However, it seems that this is not a SSH port problem.

**Comment by lllwan** [comment]
@46797536 Can you show me the Clusterfile

**Comment by 46797536** [comment]
![image](https://user-images.githubusercontent.com/46241382/134305707-7918b4be-e8ab-416a-9e62-27a79ed985de.png)


> @46797536 Can you show me the Clusterfile

**Comment by 46797536** [comment]
> > ![image](https://user-images.githubusercontent.com/46241382/133878034-c6199c86-6407-4f8a-9afe-581672726578.png)
> > 第一次安装会启动docker，第二次就找不到文件
> 
> Describe the behavior. For example: Was the first installation successful? Did you execute any other commands after the first installation? Show the /var/lib/sealer/my-cluster/rootfs directory

![image](https://user-images.githubusercontent.com/46241382/134306140-a088085a-af74-44b9-b764-2d7ae31dba4b.png)

**Comment by bxy4543** [comment]
connect refuse is not a port change problem, and after the execution error also need to delete the environment in the re-install.

**Comment by ggaaooppeenngg** [comment]
这个用法导致 advertiseAddress 带上了ssh的端口。
```
apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: x.x.x.x:10222
  bindPort: 6443
nodeRegistration:
  criSocket: /var/run/dockershim.sock

---

**Comment by bxy4543** [comment]
> 这个用法导致 advertiseAddress 带上了ssh的端口。
> 
> ```
> apiVersion: kubeadm.k8s.io/v1beta2
> kind: InitConfiguration
> localAPIEndpoint:
>   advertiseAddress: x.x.x.x:10222
>   bindPort: 6443
> nodeRegistration:
>   criSocket: /var/run/dockershim.sock
> ```
What‘s your sealer version?

**Comment by ggaaooppeenngg** [comment]
0.5.1 latest 都试过了，然后我换成配置 ssh 下的port，然后还是不行可能是那个 init configuration没有被换掉，然后我就没试，直接加了个ssh端口了。

**Comment by bxy4543** [comment]
> 0.5.1 latest 都试过了，然后我换成配置 ssh 下的port，然后还是不行可能是那个 init configuration没有被换掉，然后我就没试，直接加了个ssh端口了。

  0.5.2版本可以的
