### ISSUE TITLE
one flag to present two kinds of primitives may not be a good way of definition

### ISSUE THREAD

**Issue by allencloud** [alibaba/sealer#639]
#### What happened:
When I study the source code of sealer, I found the following code:
```
create cluster by cloud provider, just set the number of masters or nodes:
	sealer run registry.cn-qingdao.aliyuncs.com/sealer-io/cloudrootfs:v1.16.9-alpha.7 --masters 3 --nodes 3

create cluster to your baremetal server, appoint the iplist:
	sealer run registry.cn-qingdao.aliyuncs.com/sealer-io/cloudrootfs:v1.16.9-alpha.7 --masters 192.168.0.2,192.168.0.3,192.168.0.4 \
		--nodes 192.168.0.5,192.168.0.6,192.168.0.7

func init() {
	runArgs = &common.RunArgs{}
	rootCmd.AddCommand(runCmd)
	runCmd.Flags().StringVarP(&runArgs.Masters, "masters", "m", "", "set Count or IPList to masters")
	runCmd.Flags().StringVarP(&runArgs.Nodes, "nodes", "n", "", "set Count or IPList to nodes")
        ...
}
```

In the codes above, we could see the command flag `--masters` and `--nodes` could be used in two different way:
* to represent the number of master node
* to represent a detailed IP list of master node

For the user experience, I think this kind of design would bring some ambiguousness. It should transfer the end users command flag's inner meaning as explicitly as possible.

How about providing another flag `provider-type` as an enum which has the value of `aliyun`, `baremental` and so on?

Even we have done the design, and we do not think it is a good way to carry the `runArgs.Masters` into the sealer's handler function. We should interprete it in the command args handling layer rather all through the whole sealer code.

#### What you expected to happen:
none
#### How to reproduce it (as minimally and precisely as possible):
none

#### Anything else we need to know?:
none

#### Environment:
- sealer version (use `sealer version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by fanux** [comment]
Add `--provider alicloud` flag is fine, but if want separate IP or node count, need also add flags like `masterCount` `nodeCount` flag, I think it is not quite pithy.

**Comment by kakaZhou719** [comment]
link to pr #822.

**Comment by fanux** [comment]
I think higher version not support cloud provider in command line any more, if you want to use cloud, using Clusterfile, or 
`sealer infra -m 3 -n 3 --cpu 4 --memory 8 | sealer run`
