### ISSUE TITLE
Improve registry sdk

### ISSUE THREAD

**Issue by justadogistaken** [alibaba/sealer#69]
## Issue Description

Type: *feature request*

### Describe what feature you want
Currently, we are using an registry sdk( https://github.com/genuinetools/reg ) which hasn't been updated for two years. The registry has some problem, like not verifying auth info on initing registry client, and err messages are not described specificly.
I think it's critical to improve our registry sdk, we'd better learn from implementation of docker.

**Comment by allencloud** [comment]
which registry, could you help add that url in the issue description?

**Comment by justadogistaken** [comment]
the registry sdk url is https://github.com/genuinetools/reg
