### ISSUE TITLE
Using retry to check pod is already running instead sleep.

### ISSUE THREAD

**Issue by fanux** [alibaba/sealer#692]
https://github.com/alibaba/sealer/blob/main/build/local_builder.go#L237

**Comment by dddddai** [comment]
Hi @fanux, I'm willing to contribute.

Do you mean something like this?
```go
err := wait.PollImmediate(5*time.Second, 30*time.Second, func() (bool, error) {
	if l.IsAllPodsRunning() {
		return true, nil
	}
	return false, nil
})
if err != nil {
	return fmt.Errorf("cache docker image failed,cluster pod not running :%v", err)
}
```
If so, how long is the retry interval suppose to be?

**Comment by fanux** [comment]
`tryTimes=10  trySleepTime=3`

**Comment by fanux** [comment]
https://github.com/alibaba/sealer/pull/700/files   checkout this PR, seems it already fixed this issue~

**Comment by dddddai** [comment]
> https://github.com/alibaba/sealer/pull/700/files checkout this PR, seems it already fixed this issue~

Sorry I didn't get your point, this PR just rename package name, it doesn't remove the sleep in `CollectRegistryCache`
