### ISSUE TITLE
sealer ApplicationsImage & incremental updating

### ISSUE THREAD

**Issue by fanux** [alibaba/sealer#695]
# What is sealer ApplicationImage

Applications Image contains applications with all dependencies except the base image, so ApplicationsImage can install to an already existing Kubernetes cluster.

![image](https://user-images.githubusercontent.com/8912557/134311605-49efc418-7c7a-406a-a6fa-a23a8d304879.png)

`ApplicationImage = CloudImage - BaseImage`

# Why we need ApplicationsImage

Incremental updating & Install Applications to an already existing Kuberentes cluster.

# How to build an ApplicationImage

For example to build a Prometheus ApplicationImage:
Kubefile:
```
FROM registry.cn-qingdao.aliyuncs.com/sealer-apps/openebs-localpv:2.11.0
COPY prometheus .
CMD kubectl apply -f prometheus/crd.yaml
CMD kubectl apply -f prometheus/operator.yaml
```

```
sealer build -t prometheus:2.30.0 . --without-base
```
The prometheus:2.30.0 will not contain the embedded Kubernetes cluster.

# Difference from Docker image

The prometheus:2.30.0 ApplicationsImage contains all the DockerImage that Prometheus-stack needs, and contains helm chart or other operator manifests.

# How to Run ApplicationImage to an existing cluster

```
sealer run prometheus:2.30.0
```
That's all...

Or using Clusterfile to overwrite the config files like helm values.

# What if the cluster is not installed by sealer

Sealer hacked docker and registry to cache docker image in cluster, so if cluster not installed by sealer, how can we solve the Docker image cache issue.  We can only support sealer cluster now.

# Workflow

On build:
    Skip BaseImage and the `FROM` layer in metadata.
On Run:
   1. mount ApplicationImage Registry dir to sea.hub registry
   2. exec all CMD command

**Comment by ningpengtao-coder** [comment]
以应用为粒度做增量更新，如果保证能够正确更新。例如执行CMD helm install xxx话，增量更新时需要执行helm upgrade，是要增加条件判断语句去更新吗？

**Comment by kakaZhou719** [comment]
@ningpengtao-coder ，应该是后者的流程。就是只要我们能够保存升级的上下文和对应的容器镜像，应该就能保证在执行增量更新命令的时候成功升级。

**Comment by ningpengtao-coder** [comment]
@kakaZhou719 如果不是业务应用，仅考虑基础镜像中的某一个组件，是否可以使用这种方式增量更新（政府项目安全要求比较高，可能隔一段时间进行安全升级）。

**Comment by kakaZhou719** [comment]
@ningpengtao-coder ,嗯嗯，基础镜像中的某一个组件，指的是? 如果是集群组件的话，估计得使用 upgrade。

**Comment by ningpengtao-coder** [comment]
@kakaZhou719 打包在基础镜像中的存储插件、数据库、日志监控等。

**Comment by kakaZhou719** [comment]
@ningpengtao-coder ,那这些应该没问题的。
