### ISSUE TITLE
unsupported graph driver: vfs

### ISSUE THREAD

**Issue by 46797536** [alibaba/sealer#696]
![image](https://user-images.githubusercontent.com/46241382/134320828-6227caf9-a6ca-4f65-a388-d91626ca216d.png)
![image](https://user-images.githubusercontent.com/46241382/134320897-92a28f34-d0ee-40f6-8e96-4a3afdb77340.png)
![image](https://user-images.githubusercontent.com/46241382/134320958-893af5e2-0870-4d48-bca8-28bf283b91ad.png)

工作节点加入集群失败

**Comment by fanux** [comment]
docker info

change docker storage driver to overlay2: https://docs.docker.com/storage/storagedriver/overlayfs-driver/

**Comment by 46797536** [comment]
通过sealer安装如何控制修改这个配置

**Comment by 46797536** [comment]
建议加一个检测机制，然后根据系统环境，调整docker配置

**Comment by fanux** [comment]
Using ApplicationConfig to overwrite deamon.json https://github.com/alibaba/sealer/blob/main/docs/design/global-config.md#application-config

The daemon.json Dir : https://github.com/alibaba/sealer/blob/main/docs/api/cloudrootfs.md
