### ISSUE TITLE
failed to register layer when i run lite build

### ISSUE THREAD

**Issue by kakaZhou719** [alibaba/sealer#703]
#### What happened:

failed to register layer, err: archive/tar: write too long

![image](https://user-images.githubusercontent.com/83740799/134485510-cfe03306-60e9-4843-84a2-5f4f63e9a8de.png)

#### Environment:
- sealer version (use `sealer version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by justadogistaken** [comment]
@kakaZhou719 Does the error come out every time?

**Comment by kakaZhou719** [comment]
@justadogistaken ，no, it happened few times.
