### ISSUE TITLE
build CloudImage -b container模式下拉取私有镜像失败，已sealer login成功

### ISSUE THREAD

**Issue by BussanQ** [alibaba/sealer#724]
#### What happened:
build CloudImage -b container模式下拉取私有镜像失败，已sealer login成功
#### What you expected to happen:
执行build成功
#### Environment:
- sealer version: {"gitVersion":"v0.4.0","gitCommit":"7341634","buildDate":"2021-08-31 10:45:26","goVersion":"go1.14.15","compiler":"gc","platform":"linux/amd64"}
- OS:centos7.9
- Kernel:Linux dev3 3.10.0-1160.36.2.el7.x86_64

**Comment by fanux** [comment]
Cloud you show the failed log ?

**Comment by BussanQ** [comment]
拉取失败是因为使用自定义的docker，sealer魔改了dockerd，关闭；
不过还是不太明白sealer login 在-b container模式下怎么使用。
