### ISSUE TITLE
upgrade module workflow

### ISSUE THREAD

**Issue by shy-Xu** [alibaba/sealer#750]
## Some TODOs to develop sealer upgrade
step1.Change "sealer upgrade"  command's CLI,with a necessary argument stands for the image to upgrade to,and a optional argument stands for the cluster name,default is "my-cluster". 
step2. Get the Clusterfile corresponding to the cluster name in the step 1.then create an applier according to the Clusterfile,set the desired image as the user input image.then call applier.Apply()
step3. In the function "diff()",there are codes compare current image with desired image,(sealer/apply/default_applier.go#L254-L257).After comparison, a few functions will be added to a slice "todoList",such as "MountImage"、“MountRootfs” and a TODO function "Upgrade".
step4. To implement fuction "Upgrade" in the step3, we should let struct "Default" in the package "runtime" to implement function "Upgrade" declared at the interface "runtime.Interface".(sealer/runtime/runtime.go#L111-L113) ,this step will finish core codes for upgrading the cluster

**Comment by fanux** [comment]
1. You can use utils.GetDefaultClusterName to get the default cluster name, not `my-cluster` by default

**Comment by fanux** [comment]
2. Set desired cluster and current cluster, the only difference is Spec.Image.

**Comment by kakaZhou719** [comment]
@fanux @shy-Xu 。i have 2 questions here. please correct me if I am wrong.

1.  about upgrade process, could we use mountfs init(bash rootfs/scripts/init.sh) to install the new runtime ? I think if we got the new image, we got the new docker and kubelet, then just run mountfs will install it.

2.  about "the only difference is Spec.Image", if we install an application image on the existed cluster，the difference is Spec.Image too, how can we distinguish it ?

**Comment by shy-Xu** [comment]
@kakaZhou719 
about your first question.I have tried execute init(bash rootfs/scripts/init.sh),then a sequence of kubeadm commands, but it failed.Later,according to the steps in "https://v1-19.docs.kubernetes.io/zh/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/" , I just execute kubeadm commands and it successed. I will try your ways.
second question,I haven't considered application upgrade since the beginning, it's what we should do next and I am thinking about that. So, if you have any ideas, I am glad to communicate with you.

**Comment by shy-Xu** [comment]
about the first question.I tried the way which has workflow as this:"PullIfNotExist->MountImage(use init.sh)->MountRootfs->Guest->UnMountImage"  just now. it dosen't work,the cluster is still in old version
