### ISSUE TITLE
Image is not cached in registry when the image is exist in the machine

### ISSUE THREAD

**Issue by yj-cloud** [alibaba/sealer#758]
#### What happened:

The image s not cached in registry when the image is alredy exist in the machine. 
```
[root@master-xxxx ~]# docker run -d --restart=always --net=host --name sealer-registry -v /var/lib/sealer/data/lite-build/mount/registry:/var/lib/registry registry:2.7.1
[root@master-xxx ~]# docker pull xxx/nginx:1.21.3
1.21.3: Pulling from xxx/nginx
Digest: sha256:6fe11397c34b973f3c957f0da22b09b7f11a4802e1db47aef54c29e2813cc125
Status: Image is up to date for xxx/nginx:1.21.3
xxx/nginx:1.21.3
[root@master-xxxx ~]# du -sh /var/lib/sealer/data/lite-build/mount/registry
100K    /var/lib/sealer/data/lite-build/mount/registry
```

**It's easy to delete images before pulling applications' images. But deleting image failed, when some base image is using. Maybe the registry should support it.**

#### Environment:
- sealer version (use `sealer version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by justadogistaken** [comment]
@yj-cloud right, it won't cache.
The docker client will not file a pull request, so the registry can't cache it.
