### ISSUE TITLE
Sealer can't run kubernetes 1.20 using docker

### ISSUE THREAD

**Issue by VinceCui** [alibaba/sealer#762]
#### What happened:
Sealer can't run kubernetes 1.20 using docker

#### What you expected to happen:
Sealer can run kubernetes 1.20 using docker

#### How to reproduce it (as minimally and precisely as possible):
run kubernetes 1.20 and use docker rather than containerd

#### Environment:
- sealer version (use `sealer version`): latest
- Cloud provider or hardware configuration: AliCloud
- OS (e.g: `cat /etc/os-release`): centos
- Kernel (e.g. `uname -a`): 3.10
- Install tools: 
- Others:

**Comment by fanux** [comment]
Show the error log~

The CRI socket is https://github.com/alibaba/sealer/blob/main/runtime/template.go#L46 containerd by default when version > 1.20.0 

https://github.com/alibaba/sealer/blob/7bed510a01f35086bbeeb824e27681794290dbd6/runtime/kubeadm.go#L85

We needs support user defined kubeadm config.
