### ISSUE TITLE
Sealer run kubernetes 1.20.x using containerd , build and delete error

### ISSUE THREAD

**Issue by bryant-rh** [alibaba/sealer#778]
#### What you expected to happen:
Sealer run kubernetes 1.20.x using containerd,  when building, Report an error ：
![image](https://user-images.githubusercontent.com/43403977/138017833-747e0b6e-018f-4d29-8de4-e3c303c7d6a1.png)

and when delete ,Report an error ：
![image](https://user-images.githubusercontent.com/43403977/138017946-7339c2fa-0799-4fe2-bd29-061f38eed129.png)

The mirror I made is as follows:

registry-1.docker.io/bryantrh/kubernetes-withflannel-containerd-amd64:v1.20.11

#### Environment:
- sealer version (use `sealer version`): v0.5.0
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):  Ubuntu 18.04.5 LTS
- Kernel (e.g. `uname -a`): 4.15.0-136-generic
- Install tools:
- Others:

**Comment by kakaZhou719** [comment]
hi,@bryant-rh ,at present ,our sealer registry still use docker as its runtime.we need to be compatible with containerd not only the k8s runtime.i will open an issue later to handle this.

**Comment by bryant-rh** [comment]
> hi,@bryant-rh ,at present ,our sealer registry still use docker as its runtime.we need to be compatible with containerd not only the k8s runtime.i will open an issue later to handle this.

我通过修改基础镜像，已经解决了这个问题。即部署1.20版本的k8s，runtime采用containerd，但是修改了基础镜像init-registry.sh 脚本，依然在master安装了docker来启动私有镜像仓库，就解决了这个问题，目前我这边已经制作了k8s-1.20.11版本，runtime为containerd的基础镜像（包括支持amd和同时支持amd64&arm64）,已经在几个环境中用起来了。sealer的确很灵活
