### ISSUE TITLE
registry image pull error

### ISSUE THREAD

**Issue by gaodongfei** [alibaba/sealer#803]
#### What happened:
when i run demo, the registry image can't pull. I can pull image by using 127.0.0.1:5000 , but i cant pull image by using sea.hub or 192.168.xx .

[init] Using Kubernetes version: v1.19.8
[preflight] Running pre-flight checks
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
error execution phase preflight: [preflight] Some fatal errors occurred:
	[ERROR ImagePull]: failed to pull image sea.hub:5000/library/kube-apiserver:v1.19.8: output: Error response from daemon: Get https://sea.hub:5000/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
, error: exit status 1
#### What you expected to happen:
succeed to pull image on registry
#### Environment:
- sealer version (use `sealer version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by kakaZhou719** [comment]
we use /etc/hosts file to route the registry ip .pls check whether it is exist.or give us more logs for investigation.

**Comment by gaodongfei** [comment]
I succeed to pull image by fixing docker config. The reason to failed pull image is insecure-registry.

**Comment by kakaZhou719** [comment]
false alarm , close it.
