### ISSUE TITLE
etcdserver: leader changed

### ISSUE THREAD

**Issue by sfeng1996** [alibaba/sealer#804]
使用sealer部署整个业务集群，在部署业务的时候，会报错etcdserver: leader changed，是不是刚部署完k8s，集群还没有稳定有些kube-system下的pod并没有完全running，这时候部署业务，容易出错。
![image](https://user-images.githubusercontent.com/52435865/139617583-5f0bbc25-3a38-41c8-ae18-fcafe2f3f421.png)

sealer version:  v0.5.0
linux version: centos7.8  3.10.0-1127.el7.x86_64

**Comment by kakaZhou719** [comment]
@sfeng1996 ,yes ,maybe some pods not ready . if you run this cluster again, will it success? if so, i think we need to do some wait things.

**Comment by sfeng1996** [comment]
> @sfeng1996 ,yes ,maybe some pods not ready . if you run this cluster again, will it success? if so, i think we need to do some wait things.

是的，过一会重新apply就成功了，建议在部署完k8s后，等待集群稳定后再部署业务

**Comment by fanux** [comment]
磁盘性能差的时候比较容易出现这种情况。等待集群pod成功再执行gust我建议写成插件，因为并不是所有人都会遇到这种情况，遇到这个情况就通过插件解决，毕竟这个等待是有点影响性能的，你的PR我回复了~

**Comment by bxy4543** [comment]
https://github.com/alibaba/sealer/blob/main/docs/design/plugin.md#clustercheck-plugin
