### ISSUE TITLE
Using oss to serve static website

### ISSUE THREAD

**Issue by fanux** [alibaba/sealer#815]
1. Using a github action to push static files to oss bucket: Using `npm run build` when release a new version, then you will got `docs/site/src/.vuepress/dist`, push this dir to oss.
2. Bind a domain name to oss bucket.

https://help.aliyun.com/document_detail/31872.html
https://help.aliyun.com/document_detail/67323.htm?spm=a2c4g.11186623.0.0.71041febhRki59#concept-snk-r3c-5db

**Comment by Stevent-fei** [comment]
Completed
