### ISSUE TITLE
When the imageList docker image has dependencies, the dependent image  pull failed

### ISSUE THREAD

**Issue by wangkun-king** [alibaba/sealer#826]
#### What happened:
![image](https://user-images.githubusercontent.com/20026922/140467806-c9c45fde-7077-4bb1-adf4-dc4d06edab7c.png)

![image](https://user-images.githubusercontent.com/20026922/140468059-5740df24-29fc-4dd5-b863-d8997b5d1c69.png)
docker logs -f  sealer-registry :
![image](https://user-images.githubusercontent.com/20026922/140469259-adaca8c4-ce19-4c0e-8797-ac819f58df33.png)
![image](https://user-images.githubusercontent.com/20026922/140468662-1138f52f-0304-4c4b-afc8-8f4d06fed45a.png)
![image](https://user-images.githubusercontent.com/20026922/140468728-d32356f0-7cbe-40d0-b4c6-ddec75f9eb0f.png)

#### What you expected to happen:
pull fmweb image success
#### Environment:
- sealer version (use sealer version): v0.5.1
- Cloud provider or hardware configuration: 4 core 8g
- OS (e.g: cat /etc/os-release): CentOS Linux 7 (Core)
- Kernel (e.g. uname -a):Linux k8s-master01 3.10.0-1127.el7.x86_64 fix: ci lint for mod registry and image #1 SMP Tue Mar 31 23:36:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by kakaZhou719** [comment]
@wangkun-king ,could you please check more details via "docs/site/src/docs/help/faq.md" . i think we lost some layers. you can try `docker system prune -a` clean your old images.

**Comment by wangkun-king** [comment]
> could you please check more details via "docs/site/src/docs/help/faq.md" . i think we lost some layers. you can try `docker system prune -a` clean your old images.

[root@k8s-node03 ~]# docker version
Client: Docker Engine - Community
 Version:           19.03.14
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        5eb3275
 Built:             Tue Dec  1 19:14:24 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.14-sealer
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       711cc111cf
  Built:            Wed Jun  2 09:07:15 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.9
  GitCommit:        ea765aba0d05254012b0b9e595e995c09186427f
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

[root@k8s-node03 ~]# cat /etc/docker/daemon.json
{
  "max-concurrent-downloads": 20,
  "log-driver": "json-file",
  "log-level": "warn",
  "log-opts": {
    "max-size": "10m",
    "max-file": "3"
  },
  "insecure-registries": [
    "sea.hub",
    "sea.hub:5000"
  ],
  "mirror-registries": [
   {
    "domain": "*",
    "mirrors": ["http://sea.hub:5000"]
   }
  ],
  "data-root": "/var/lib/docker"
}

[root@sealer ~]# docker system prune -a
WARNING! This will remove:
  - all stopped containers
  - all networks not used by at least one container
  - all images without at least one container associated to them
  - all build cache

Are you sure you want to continue? [y/N] y
Deleted Images:
untagged: registry:2.7.1
untagged: registry:2.7.1
deleted: sha256:0d0107588605f17177f6d11bad900de6a7bcf2b7aa0f72f5e2dd04102cb34fda
deleted: sha256:a46656c7787a223c5f81952140e422d5eac3b23939e01bc98b9b104896a60cbb
deleted: sha256:4e426c176d3691b72c406fa95b3aefa77878ddbc0af004927eae36f4406d636e
deleted: sha256:b2d5eeeaba3a22b9b8aa97261957974a6bd65274ebd43e1d81d0a7b8b752b116
....
deleted: sha256:a84b4e945affc390a49fe16b1e47251671dfc628c111de3a4c5b2e0b09d2649a
deleted: sha256:4bc4490d37ab1d9664581bcbb9c198cd5c4e7eaf0c5b1607c5ec44a11eaf922f
deleted: sha256:21b5c6b4b2751d9e70a183749330b4b9e11687a0cb4995f33ee5812846128294
deleted: sha256:c2ddc1bc2645ab5d982c60434d8bbc6aecee1bd4e8eee0df7fd08c96df2d58bb

Total reclaimed space: 1.435GB

rebuild cluster image:
![image](https://user-images.githubusercontent.com/20026922/140477852-676d0017-de81-4079-aa08-046563f198eb.png)
![image](https://user-images.githubusercontent.com/20026922/140478146-f1f121af-0ace-4d88-9366-e9b029c6c69d.png)
![image](https://user-images.githubusercontent.com/20026922/140480278-a21d7556-ab47-4199-922c-f902a559734c.png)

![image](https://user-images.githubusercontent.com/20026922/140480897-d86bee39-39ce-49bc-a4d5-c9203710b997.png)
...

I think The layers of the dependent tomcat image are all cached

**Comment by kakaZhou719** [comment]
@wangkun-king ,nice work. whether the new image runs successfully？

**Comment by wangkun-king** [comment]
> @wangkun-king ,nice work. whether the new image runs successfully？

Unfortunately, still cannot pull successfully
Only pull tomcat image first and then pull fmweb image to succeed
![image](https://user-images.githubusercontent.com/20026922/140487040-a282475c-9904-4383-b7be-fcb2c53bd6d1.png)
![image](https://user-images.githubusercontent.com/20026922/140487249-c0d1d7db-15cc-469f-8686-055011ea0ea0.png)

**Comment by kakaZhou719** [comment]
@wangkun-king, do you mean only pull fmweb failed. if we pull tomcat first and then pull fmweb, will be successful?if so that a question. i guess the manifest of fmweb dont exist on the master-0, could please check it ?

**Comment by wangkun-king** [comment]
> @wangkun-king, do you mean only pull fmweb failed. if we pull tomcat first and then pull fmweb, will be successful?if so that a question. i guess the manifest of fmweb dont exist on the master-0, could please check it ?

how to do check it?

**Comment by wangkun-king** [comment]
manifest of fmweb may be this
![image](https://user-images.githubusercontent.com/20026922/140603493-6841a504-d7f2-4bf0-a669-587ceb9e8448.png)

when execute docker pull xxxxx/fmweb:1.0.0  sealer-registry log as follows:
![image](https://user-images.githubusercontent.com/20026922/140603634-71ff0594-b65c-4d37-a4f6-37eba75a1146.png)

When I replaced fmweb with tomcat, curl succeeded
![image](https://user-images.githubusercontent.com/20026922/140603587-2cb15cfc-d222-4f74-8108-a6814531a60f.png)

**Comment by kakaZhou719** [comment]
@wangkun-king , please check the difference of failed pull and success pull , diff the layers and the manifests to see which layers we lost in the blob.

examples like below : 

docker image layer list include layers and manifests:

![image](https://user-images.githubusercontent.com/83740799/140673420-4be73170-242c-445e-af12-6b5a4420f10f.png)

docker image blobs:

![image](https://user-images.githubusercontent.com/83740799/140673811-78ee159c-b1b1-4368-b305-73611284aae5.png)

**Comment by wangkun-king** [comment]
![image](https://user-images.githubusercontent.com/20026922/140845731-0809b5e1-eccc-41aa-82c7-910acebad537.png)
![image](https://user-images.githubusercontent.com/20026922/140845887-2e4609fa-c6b2-4d0b-b593-3a30a2328596.png)
![image](https://user-images.githubusercontent.com/20026922/140845923-24313cd5-b8b4-458a-98b5-06e046933f8f.png)
![image](https://user-images.githubusercontent.com/20026922/140846037-ec924d38-71f1-45f3-99c8-f417b01123ff.png)
![image](https://user-images.githubusercontent.com/20026922/140846090-ce7cfa2f-3bf4-46f6-8c7c-b0d4a9d4e3b8.png)

**Comment by wangkun-king** [comment]
@kakaZhou719 
![image](https://user-images.githubusercontent.com/20026922/140846823-c453c593-3b26-4b18-acc1-33334f9a6209.png)
![image](https://user-images.githubusercontent.com/20026922/140847264-6c39ac79-8bd5-4b27-839a-f29700bb3b08.png)
![image](https://user-images.githubusercontent.com/20026922/140847304-3b06c4d3-c8f0-4179-8eab-d6968316a1ab.png)
![image](https://user-images.githubusercontent.com/20026922/140847342-382b8f86-ec74-4c39-9a01-0f2414e23eee.png)
![image](https://user-images.githubusercontent.com/20026922/140847397-a81375d7-18f0-42ca-b39b-fc0d536f79ef.png)
![image](https://user-images.githubusercontent.com/20026922/140847424-b9e8da5c-dbca-4ba3-b538-594054e8b84d.png)

**Comment by kakaZhou719** [comment]
@wangkun-king, looks like we actually lost the tomcat layers . this is a problem . you can temporarily circumvent the problem by adjusting the imageList order: fmweb first and set tomcat as secondary .

and i wrote the faq section yesterday ,that how to trouble shoot the lost layers using "docker inspect". please try it .

**Comment by wangkun-king** [comment]
@kakaZhou719 
But I have multiple images that depend on the tomcat image,
Adjusting the imageList order does not solve my problem

![image](https://user-images.githubusercontent.com/20026922/140857180-b543cd36-7a3e-4b6a-88fa-133c621841a1.png)

**Comment by fanux** [comment]
fixed in 0.6.1
