### ISSUE TITLE
[Build] When image in imageList unreachable, sealer just warn, i think it should fail.

### ISSUE THREAD

**Issue by VinceCui** [alibaba/sealer#833]
#### What happened:

When image in imageList unreachable, sealer just warn, i think it should fail.

#### Environment:

- sealer version (use `sealer version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by kakaZhou719** [comment]
right ,if we lost some image ,the cloud image is incomplete.if some image already in the build host, we will lost some image layer too.
