### ISSUE TITLE
[Build] Suggest COPY like linux cp, for example, support directory copy

### ISSUE THREAD

**Issue by VinceCui** [alibaba/sealer#834]
## Issue Description

Now, when  i use COPY dir/file1 ./bin in Kubefile, i will get ./bin/dir/file1.

Should sealer make COPY like linux cp?

Use cases:
1. COPY dir/file1 ./bin, i will get ./bin/file1
2. COPY dir ./bin, i will get ./bin/dir
3. COPY dir/* ./bin, all files in dir will be put in ./bin/

Type: *feature request*

**Comment by kakaZhou719** [comment]
hi @VinceCui ,

1. COPY dir/file1 ./bin, i will get ./bin/file1: already add in the master branch.
2. COPY dir ./bin, i will get ./bin/dir: already add in the master branch.
3 . COPY dir/* ./bin, all files in dir will be put in ./bin/:    this will add in the next release.
