### ISSUE TITLE
gloabl-config example is incorrect, The env should be String array

### ISSUE THREAD

**Issue by wangkun-king** [alibaba/sealer#836]
#### What happened:
I tried to use env but failed
![image](https://user-images.githubusercontent.com/20026922/140880467-bbd63614-a6e0-440b-a447-8d0e859a740c.png)
![image](https://user-images.githubusercontent.com/20026922/140880575-14a858b1-a7bc-4b69-9123-f06fe9273575.png)
failed to decode cluster from clusterfile.yaml, decode cluster failed error unmarshaling JSON: while decoding JSON: json: cannot unmarshal object into Go struct field ClusterSpec.spec.env of type []string
https://github.com/alibaba/sealer/blob/main/docs/design/global-config.md#application-config

#### Environment:

- sealer version (use `sealer version`):v0.5.1
- Cloud provider or hardware configuration:4 core 8g
- OS (e.g: `cat /etc/os-release`): CentOS Linux 7 (Core)
- Kernel (e.g. `uname -a`):Linux sealer 3.10.0-1127.el7.x86_64 #1 SMP Tue Mar 31 23:36:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by fanux** [comment]
The env feature is on the way~

**Comment by fanux** [comment]
Will fixed in 0.6.0. Clusterfile v2
