### ISSUE TITLE
Sealer scratch based Cloud Image (distro-less) able to specify compatible KubeVersion required

### ISSUE THREAD

**Issue by nashtsai** [alibaba/sealer#844]
## Issue Description
Sealer scratch based Cloud Image (distro-less) able to specify compatible KubeVersion required to avoid incompatible Kube API usage.

Type: *feature request*

### Describe what feature you want
The idea is borrowed from Helm chart `kubeVersion` field (https://helm.sh/docs/topics/charts/#the-kubeversion-field) that is able to constraint on Kubernetes versions, and upon Sealer installation process this manifest info is validated before installation action.

### Additional context
N/A

**Comment by kakaZhou719** [comment]
@nashtsai ,we have Metadata file built in our rootfs show the kubeversion. some cached docker images also saved with the kube version. that means we need to upgrade them all to avoid incompatible Kube API usage.

**Comment by nashtsai** [comment]
> @nashtsai ,we have Metadata file built in our rootfs show the kubeversion. some cached docker images also saved with the kube version. that means we need to upgrade them all to avoid incompatible Kube API usage.

I believe that's Sealer internal stuff, is this feature request been accepted or not?

**Comment by fanux** [comment]
@kakaZhou719 Application Image need to know compatible KubeVersion list like helm chart kubeVersion.

@nashtsai We need this feature, I will add it into appropriate milestone latter.
