### ISSUE TITLE
Wrong Clusterfile in cloudrootfs

### ISSUE THREAD

**Issue by fanux** [alibaba/sealer#85]
#### What happened:
![image](https://user-images.githubusercontent.com/8912557/118099403-c18dd280-b407-11eb-809d-97580e80d59a.png)

#### How to reproduce it (as minimally and precisely as possible):
Run a cloud image witch don't have registry namespace.

**Comment by justadogistaken** [comment]
I guess you didn't update the branch? there is no "seadent" already.

**Comment by fanux** [comment]
@bxy4543 wrong Cloudrootfs in cloudImage

**Comment by fanux** [comment]
sealer run cloudrootfs:v1.16.9-apha.7

need using command line image name to overwrite the default Clusterfile image name.
