### ISSUE TITLE
Support configuring Docker service to trust Sealer Docker Registry Service 

### ISSUE THREAD

**Issue by luckyfengyong** [alibaba/sealer#852]
## Issue Description

Type: *feature request*

Currently the cluster image developer has to handle the configuration of Docker service in the cluster nodes by themselves to allow pulling image from Sealer Docker Registry Service. Otherwise, installation fails due to failing to pull images.

### Describe what feature you want

Configuring Docker service to trust Sealer Docker Registry Service is a kind of common task required by most cluster image developer. Sealer could implement it as a part of base image or other utilities to make developer's life easier :-).

**Comment by bxy4543** [comment]
#885
