### ISSUE TITLE
plugin cannot read the on field

### ISSUE THREAD

**Issue by wangkun-king** [alibaba/sealer#867]
#### What happened:
Read the plugin on eld in the clusterfile.yaml file is empty
![image](https://user-images.githubusercontent.com/20026922/142141614-61d09837-b360-460b-a737-82d56849c69d.png)

![image](https://user-images.githubusercontent.com/20026922/142141513-130e1384-a948-49a6-807d-94695ffcd734.png)

The yamltojson method reads the on field as a true field
![image](https://user-images.githubusercontent.com/20026922/142141986-4c65a284-ca68-4674-8b00-55b7c5e17773.png)
may be "on" is keyword

#### Environment:

- sealer version (use `sealer version`): latest source
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): macos 12.0.1
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by bxy4543** [comment]
![image](https://user-images.githubusercontent.com/69408038/142810955-4082a731-d2d8-4916-97b0-26fac64c6f3e.png)
This may be related to yaml/v2 and yaml/v3

**Comment by bxy4543** [comment]
I found some with similar problems:
https://github.com/kubernetes/kubernetes/issues/102308#issuecomment-852485282
https://github.com/go-yaml/yaml/issues/214
The YAML 1.1 spec explicitly supported unquoted values like "on/off" or "yes/no" as booleans.
You can temporarily fix this problem by using the quote 'on' field

![image](https://user-images.githubusercontent.com/69408038/142988841-08e17177-26c9-45cf-b52c-f630cb742946.png)
