### ISSUE TITLE
sealer upgrade failed because of nil pointer

### ISSUE THREAD

**Issue by shy-Xu** [alibaba/sealer#876]
#### What happened:
Firstly,I execute "sealer run kubernetes:v1.19.8 -m x.x.x.x -p x" to create a cluster,then I execute "sealer upgrade registry.cn-beijing.aliyuncs.com/sealer-io/kubernetes:v1.19.9_develop" and it failed.
The problem is at sealer/apply/applytype/local.go#L141,the value of currentMetadata is nil

**Comment by shy-Xu** [comment]
I think the path of the currentMetadata file is correct,but it should be the path on the machine of the k8s cluster, not the local path

**Comment by kakaZhou719** [comment]
fixed
