### ISSUE TITLE
bug: sensitive information exposed

### ISSUE THREAD

**Issue by justadogistaken** [alibaba/sealer#883]
For making contaienr images cached more user-friendly, we will  encode username:password in base64, and add it to header; It's fine when the protocol is https, but our local registry endpoint is under http. And we config the sea.hub:5000 as insecure by default, I guess it may bring some risks for sensitive information exposure. 

```
{
  "mirror-registries":[
    {
      "domain": "*",
      "mirrors": ["http://sea.hub:5000"]
    }
  ],
  "insecure-registries": ["sea.hub:5000"]
}
```

**Comment by fanux** [comment]
https is on the way~
