### ISSUE TITLE
the number layerIDs 0 and LayerDescriptor 4 are mismatch

### ISSUE THREAD

**Issue by sundong1982** [alibaba/sealer#896]
sealer pull registry.cn-hangzhou.aliyuncs.com/xxxx/openjdk:11-jre-slim-buster

Error: the number layerIDs 0 and LayerDescriptor 4 are mismatch
Usage:
  sealer pull [flags]

Examples:
sealer pull registry.cn-qingdao.aliyuncs.com/sealer-io/kubernetes:v1.19.8

**Comment by bxy4543** [comment]
sealer only supports pull sealer image and supports pushing sealer images to the docker repository.

**Comment by sundong1982** [comment]
thx
