### ISSUE TITLE
kyverno can't affect Pods created by Kubefile CMD

### ISSUE THREAD

**Issue by shy-Xu** [alibaba/sealer#897]
#### What happened:
The kyverno can't affect Pods created by Kubefile CMD.
For example, when build a cloud image based on kubernetes-raw_docker-kyverno:v1.19.8

The Kubefile:
FROM kubernetes-raw_docker-kyverno:v1.19.8
CMD kubectl run ubuntuPod --image=ubuntu

Build success, then use this cloud image to run a cluster, run success, too. The ubuntuPod created but cann't running, that's all right. What's strange is when I execute "kubectl describe pod ubuntuPod",  output shows that ubuntuPod wants to pull image "ubuntu", not "sea.hub:5000/library/ubuntu". It seems that kyverno not affect this pod.

To compare, after "sealer run" finish, execute "kubectl run ubuntuTest --image=ubuntu" at master node, then "kubectl describe pod ubuntuTest", output shows that ubuntuTest wants to pull image "sea.hub:5000/library/ubuntu"

#### What you expected to happen:
The pod ubuntuPod pull image "sea.hub:5000/library/ubuntu" instead of "ubuntu"

**Comment by fanux** [comment]
kyverno already start?

**Comment by shy-Xu** [comment]
Yes,there is a script to monitor kyverno state until it's running

**Comment by shy-Xu** [comment]
The actual effect is no problem. Pods use other images cann't run, it's what we want. Just the output information confuses me.

**Comment by shy-Xu** [comment]
Pods use images cached into registry can run, that's no problem, too.

**Comment by shy-Xu** [comment]
I have fixed this bug
