### ISSUE TITLE
sealer images print more header

### ISSUE THREAD

**Issue by cuisongliu** [alibaba/sealer#9]
## Issue Description

Type: *feature request*

### Describe what feature you want

print image tag and size

**Comment by fanux** [comment]
I think we need count image size when building it. And save it in metadata.

**Comment by fanux** [comment]
@justadogistaken

**Comment by kakaZhou719** [comment]
![image](https://user-images.githubusercontent.com/83740799/139657654-682599e5-8d55-4a02-98f8-da74ccfd6e2c.png)
