### ISSUE TITLE
[feature]support adding custom cleanup scripts when deleting k8s cluster

### ISSUE THREAD

**Issue by TheBeatles1994** [alibaba/sealer#917]
## Issue Description

Type: *feature request*

### Describe what feature you want

There are still some LVM logical volumes(created by csi plugin) or residual files(created by app) in the environment after sealer has cleaned up the k8s cluster. So I want a feature that support executing **custom** cleanup scripts in each node after deleting k8s cluster.

**Comment by fanux** [comment]
@Stevent-fei call the "scripts/post_clean.sh" scripts if existed when clean the cluster.

@TheBeatles1994 so you can copy a post_clean.sh script to clean your LVM volumes.

```
FROM openlocal:latest
COPY post_clean.sh scripts
```
