### ISSUE TITLE
sealer integration nydus to improve image distribution performance

### ISSUE THREAD

**Issue by fanux** [alibaba/sealer#937]

**Comment by fanux** [comment]
Interface design:

```
type Blob struct {
   ...
}

type Image interface {
     CreateBlob(dir string) (Blob,error) // create a blob from dir
     MountBlob(dstDir string, blobs Blob...) error // mount blobs to dstDir
     Unmount(dstDir string) error
}
```

Build workflow:
1. create a dir like: `hash1`
2. write some files to `hash1` dir
3. create blob from `hash1` dir (CreateBlob) : Blob1
4. mount Blob1 to `hash2` dir (MountBlob)
5. write some files to `hash2` dir
6. create blob from `hash2`, this blob should not contains Blob1: Blob2

**Comment by nan1994** [comment]
4.mount Blob1 to hash2 dir (MountBlob)；
why need mount Blob1 to hash2 dir before write some files to hash2 dir？

**Comment by nan1994** [comment]
> Interface design:
> 
> ```
> type Blob struct {
>    ...
> }
> 
> type Image interface {
>      CreateBlob(dir string) (Blob,error) // create a blob from dir
>      MountBlob(dstDir string, blobs Blob...) error // mount blobs to dstDir
>      Unmount(dstDir string) error
> }
> ```
> 
> Build workflow:
> 
> 1. create a dir like: `hash1`
> 2. write some files to `hash1` dir
> 3. create blob from `hash1` dir (CreateBlob) : Blob1
> 4. mount Blob1 to `hash2` dir (MountBlob)
> 5. write some files to `hash2` dir
> 6. create blob from `hash2`, this blob should not contains Blob1: Blob2

4.mount Blob1 to hash2 dir (MountBlob)；
why need mount Blob1 to hash2 dir before write some files to hash2 dir？

**Comment by fanux** [comment]
For example :
 
COPY helm /usr/bin  # Blob1
RUN helm install xxx # hash2 command dependon the Blob1 files

**Comment by hsiangkao** [comment]
struct MetaBlob {
   // full pathname of bootstrap, which is used to contain RAFS filesystem metadata.
   bootstrap_pathname: String,
   // a vector to contain all blobs to mount the RAFS filesystem.
   // a blob is a CAS system to contain chunk-deduplicated data.
   blobs_pathname: Vec<String>,
}
