### ISSUE TITLE
infra  aliyun/huawei cloud module optimization suggestion

### ISSUE THREAD

**Issue by cuisongliu** [alibaba/sealer#945]
## Issue Description

Type: *feature request*

### Describe what feature you want
1. disk category: some zone not spport essd mode(in aliyun all category is cloud_efficiency,cloud_essd,cloud_ssd)
3. seize mode for runInstance
4. imageID ,diff platform not same image
5. for different roleType the instance type not same（ex. master used 8c48g but node used 4c32g the instanceType not same ）
6. support arm ecs

**Comment by fanux** [comment]
Base on https://github.com/alibaba/sealer/blob/main/docs/design/clusterfile-v2.md#how-to-using-cloud-infra
