### ISSUE TITLE
Clusterfile v2 tests

### ISSUE THREAD

**Issue by fanux** [alibaba/sealer#946]
e2e tests:

1. lite build as default build mod. Using SaveImage as default cache image method.
2. Build ARM CloudImage on AMD and run it on ARM.
3. CloudImage ARM & AMD: 
     AMD: 
         sealer-docker image `kubernetes-clusterv2:v1.19.8`
         kyverno image           `kubernetes-kyverno:v1.19.8`
     ARM:
         sealer-docker image `kubernetes-arm64:v1.19.7`
         kyverno image `kubernetes-kyverno-arm64:v1.19.7`
 
4. Clusterfile v2 Plugin test, hostname, label, shell, plugin out of tree
5. Clusterfile v1=> v2 adapter

Experience：
1. Stability
2. Documents
3. Performance
4. Logging

**Comment by kakaZhou719** [comment]
user experience:  pull docker image use io stream to display output messages, refer to "github.com/docker/docker/pkg/jsonmessage".  sealer load image also need this.

**Comment by kakaZhou719** [comment]
user experience:  sealer delete node show "delete cluster", we need to review our cmd hint messages .

**Comment by kakaZhou719** [comment]
question about "3. CloudImage ARM & AMD",   should we add calico image to make it out of the box?
