### ISSUE TITLE
如何从一个已经存在的集群生成一个镜像？

### ISSUE THREAD

**Issue by gdlbl** [alibaba/sealer#948]
我现在已经有了一个v1.22.0的k8s集群，部署了3个master节点做HA，还有3个工作节点，另外我还安装了istio、knative、kubevela以及自己的一些应用。请问我能否利用sealer从当前运行的集群直接生成一个镜像？类似docker export或者docker save那样。

**Comment by fanux** [comment]
At present, snapshots and recovery are not within the scope of sealer. It is recommended to use kubefile to build CloudImage, just like docker does not recommend commit to export docker image.
