### ISSUE TITLE
About image save module handle blobs bigger than 4M

### ISSUE THREAD

**Issue by shy-Xu** [alibaba/sealer#958]
## Issue Description
According to source code of ditribution/distribution/v3/registry, blob bigger than 4M will be pulled again even local filesystem already has it. Shall we delete this limit?

**Comment by shy-Xu** [comment]
Related file: ditribution/distribution/v3/registry/storage/io.go

**Comment by fanux** [comment]
If you delete it, but how? Should not modify vendor.
