### ISSUE TITLE
Support print file:line in log

### ISSUE THREAD

**Issue by touchuyht** [alibaba/sealer#96]
I suggest print log with file:line header which is useful for development and debugging. I copied some log from kubeedge which uses klog to print a detailed log. 
     Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
     5 I0510 13:25:09.138707    4537 server.go:65] Version: v1.6.0-beta.0.147+46b6e52b139902-dirty
     6 I0510 13:25:09.142670    4537 module.go:34] Module cloudhub registered successfully
     7 I0510 13:25:09.457349    4537 module.go:34] Module edgecontroller registered successfully
     8 I0510 13:25:09.457453    4537 module.go:34] Module devicecontroller registered successfully
     9 I0510 13:25:09.457493    4537 module.go:34] Module synccontroller registered successfully
    10 W0510 13:25:09.457547    4537 module.go:37] Module cloudStream is disabled, do not register
    11 W0510 13:25:09.457565    4537 module.go:37] Module router is disabled, do not register
## Issue Description

Type: *feature request*

### Describe what feature you want
Need more detailed log error information as file:line style.

**Comment by fanux** [comment]
Yes, but should not print the full path.
