### ISSUE TITLE
need translate chinese to English

### ISSUE THREAD

**Issue by cuisongliu** [alibaba/sealer#964]
#### What happened:

https://github.com/alibaba/sealer/tree/main/seautil 

need translate chinese to english

#### Environment:

- sealer version (use `sealer version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by Encounter77** [comment]
i am here
