### ISSUE TITLE
can't  support set deployment.spec.template.spec.containers[0].env.valueFrom.fieldRef.fieldPath from metadata.labels in kuboard-ui

### ISSUE THREAD

**Issue by jiajiangnan** [alibaba/sealer#979]
#### What happened:

1、can't  support set deployment.spec.template.spec.containers[0].env.valueFrom.fieldRef.fieldPath from metadata.labels in kuboard-ui

#### What you expected to happen:

1、support set deployment.spec.template.spec.containers[0].env.valueFrom.fieldRef.fieldPath from metadata.labels in kuboard-ui

**Comment by fanux** [comment]
I think this is caused by Kubernetes version compatibility. Make sure the kuboard version compatible with kubernetes:v1.19.8
